// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeAlert = `-- name: AcknowledgeAlert :one
UPDATE alerts
SET status = 'acknowledged',
    acknowledged_at = now(),
    escalation_state = $3,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND status = 'triggered'
RETURNING id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, closed_at, created_at, updated_at
`

type AcknowledgeAlertParams struct {
	ID              uuid.UUID `json:"id"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	EscalationState []byte    `json:"escalation_state"`
}

func (q *Queries) AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, acknowledgeAlert, arg.ID, arg.OrganizationID, arg.EscalationState)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.IntegrationKeyID,
		&i.Status,
		&i.DedupKey,
		&i.Summary,
		&i.Description,
		&i.Priority,
		&i.EventCount,
		&i.EscalationState,
		&i.AcknowledgedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTriggeredAlert = `-- name: CreateTriggeredAlert :one
INSERT INTO alerts (
    id,
    organization_id,
    service_id,
    integration_key_id,
    status,
    dedup_key,
    summary,
    description,
    priority,
    escalation_state
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'triggered',
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, closed_at, created_at, updated_at
`

type CreateTriggeredAlertParams struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	ServiceID        uuid.UUID   `json:"service_id"`
	IntegrationKeyID pgtype.UUID `json:"integration_key_id"`
	DedupKey         string      `json:"dedup_key"`
	Summary          string      `json:"summary"`
	Description      pgtype.Text `json:"description"`
	Priority         string      `json:"priority"`
	EscalationState  []byte      `json:"escalation_state"`
}

func (q *Queries) CreateTriggeredAlert(ctx context.Context, arg CreateTriggeredAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createTriggeredAlert,
		arg.ID,
		arg.OrganizationID,
		arg.ServiceID,
		arg.IntegrationKeyID,
		arg.DedupKey,
		arg.Summary,
		arg.Description,
		arg.Priority,
		arg.EscalationState,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.IntegrationKeyID,
		&i.Status,
		&i.DedupKey,
		&i.Summary,
		&i.Description,
		&i.Priority,
		&i.EventCount,
		&i.EscalationState,
		&i.AcknowledgedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlertByID = `-- name: GetAlertByID :one
SELECT id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, closed_at, created_at, updated_at
FROM alerts
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetAlertByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetAlertByID(ctx context.Context, arg GetAlertByIDParams) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlertByID, arg.ID, arg.OrganizationID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.IntegrationKeyID,
		&i.Status,
		&i.DedupKey,
		&i.Summary,
		&i.Description,
		&i.Priority,
		&i.EventCount,
		&i.EscalationState,
		&i.AcknowledgedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAlertEscalationState = `-- name: UpdateAlertEscalationState :one
UPDATE alerts
SET escalation_state = $3,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
RETURNING id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, closed_at, created_at, updated_at
`

type UpdateAlertEscalationStateParams struct {
	ID              uuid.UUID `json:"id"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	EscalationState []byte    `json:"escalation_state"`
}

func (q *Queries) UpdateAlertEscalationState(ctx context.Context, arg UpdateAlertEscalationStateParams) (Alert, error) {
	row := q.db.QueryRow(ctx, updateAlertEscalationState, arg.ID, arg.OrganizationID, arg.EscalationState)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.IntegrationKeyID,
		&i.Status,
		&i.DedupKey,
		&i.Summary,
		&i.Description,
		&i.Priority,
		&i.EventCount,
		&i.EscalationState,
		&i.AcknowledgedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
