// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeAlert = `-- name: AcknowledgeAlert :one
UPDATE alerts
SET status = 'acknowledged',
    acknowledged_at = now(),
    acknowledged_by_user_id = $4,
    escalation_state = $3,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND status = 'triggered'
RETURNING id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, acknowledged_by_user_id, closed_at, resolved_at, resolved_integration, incident_id, created_at, updated_at
`

type AcknowledgeAlertParams struct {
	ID                   uuid.UUID   `json:"id"`
	OrganizationID       uuid.UUID   `json:"organization_id"`
	EscalationState      []byte      `json:"escalation_state"`
	AcknowledgedByUserID pgtype.UUID `json:"acknowledged_by_user_id"`
}

func (q *Queries) AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, acknowledgeAlert,
		arg.ID,
		arg.OrganizationID,
		arg.EscalationState,
		arg.AcknowledgedByUserID,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.IntegrationKeyID,
		&i.Status,
		&i.DedupKey,
		&i.Summary,
		&i.Description,
		&i.Priority,
		&i.EventCount,
		&i.EscalationState,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ClosedAt,
		&i.ResolvedAt,
		&i.ResolvedIntegration,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const assignAlertToIncident = `-- name: AssignAlertToIncident :one
UPDATE alerts
SET incident_id = $3,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND incident_id IS NULL
  AND status IN ('triggered', 'acknowledged')
RETURNING id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, acknowledged_by_user_id, closed_at, resolved_at, resolved_integration, incident_id, created_at, updated_at
`

type AssignAlertToIncidentParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	IncidentID     pgtype.UUID `json:"incident_id"`
}

func (q *Queries) AssignAlertToIncident(ctx context.Context, arg AssignAlertToIncidentParams) (Alert, error) {
	row := q.db.QueryRow(ctx, assignAlertToIncident, arg.ID, arg.OrganizationID, arg.IncidentID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.IntegrationKeyID,
		&i.Status,
		&i.DedupKey,
		&i.Summary,
		&i.Description,
		&i.Priority,
		&i.EventCount,
		&i.EscalationState,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ClosedAt,
		&i.ResolvedAt,
		&i.ResolvedIntegration,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const closeAlert = `-- name: CloseAlert :one
UPDATE alerts
SET status = 'closed',
    closed_at = now(),
    escalation_state = $3,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND status IN ('triggered', 'acknowledged')
RETURNING id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, acknowledged_by_user_id, closed_at, resolved_at, resolved_integration, incident_id, created_at, updated_at
`

type CloseAlertParams struct {
	ID              uuid.UUID `json:"id"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	EscalationState []byte    `json:"escalation_state"`
}

func (q *Queries) CloseAlert(ctx context.Context, arg CloseAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, closeAlert, arg.ID, arg.OrganizationID, arg.EscalationState)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.IntegrationKeyID,
		&i.Status,
		&i.DedupKey,
		&i.Summary,
		&i.Description,
		&i.Priority,
		&i.EventCount,
		&i.EscalationState,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ClosedAt,
		&i.ResolvedAt,
		&i.ResolvedIntegration,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countRecentOpenAlertsByService = `-- name: CountRecentOpenAlertsByService :one
SELECT count(*)::integer AS count
FROM alerts
WHERE service_id = $1
  AND organization_id = $2
  AND status IN ('triggered', 'acknowledged')
  AND created_at >= now() - ($3::integer * interval '1 second')
`

type CountRecentOpenAlertsByServiceParams struct {
	ServiceID      uuid.UUID `json:"service_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	WindowSeconds  int32     `json:"window_seconds"`
}

func (q *Queries) CountRecentOpenAlertsByService(ctx context.Context, arg CountRecentOpenAlertsByServiceParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRecentOpenAlertsByService, arg.ServiceID, arg.OrganizationID, arg.WindowSeconds)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createTriggeredAlert = `-- name: CreateTriggeredAlert :one
INSERT INTO alerts (
    id,
    organization_id,
    service_id,
    integration_key_id,
    status,
    dedup_key,
    summary,
    description,
    priority,
    escalation_state
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'triggered',
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, acknowledged_by_user_id, closed_at, resolved_at, resolved_integration, incident_id, created_at, updated_at
`

type CreateTriggeredAlertParams struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	ServiceID        uuid.UUID   `json:"service_id"`
	IntegrationKeyID pgtype.UUID `json:"integration_key_id"`
	DedupKey         string      `json:"dedup_key"`
	Summary          string      `json:"summary"`
	Description      pgtype.Text `json:"description"`
	Priority         string      `json:"priority"`
	EscalationState  []byte      `json:"escalation_state"`
}

func (q *Queries) CreateTriggeredAlert(ctx context.Context, arg CreateTriggeredAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createTriggeredAlert,
		arg.ID,
		arg.OrganizationID,
		arg.ServiceID,
		arg.IntegrationKeyID,
		arg.DedupKey,
		arg.Summary,
		arg.Description,
		arg.Priority,
		arg.EscalationState,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.IntegrationKeyID,
		&i.Status,
		&i.DedupKey,
		&i.Summary,
		&i.Description,
		&i.Priority,
		&i.EventCount,
		&i.EscalationState,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ClosedAt,
		&i.ResolvedAt,
		&i.ResolvedIntegration,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlertByID = `-- name: GetAlertByID :one
SELECT id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, acknowledged_by_user_id, closed_at, resolved_at, resolved_integration, incident_id, created_at, updated_at
FROM alerts
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetAlertByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetAlertByID(ctx context.Context, arg GetAlertByIDParams) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlertByID, arg.ID, arg.OrganizationID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.IntegrationKeyID,
		&i.Status,
		&i.DedupKey,
		&i.Summary,
		&i.Description,
		&i.Priority,
		&i.EventCount,
		&i.EscalationState,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ClosedAt,
		&i.ResolvedAt,
		&i.ResolvedIntegration,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenAlertByServiceDedupKey = `-- name: GetOpenAlertByServiceDedupKey :one
SELECT id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, acknowledged_by_user_id, closed_at, resolved_at, resolved_integration, incident_id, created_at, updated_at
FROM alerts
WHERE service_id = $1
  AND dedup_key = $2
  AND status IN ('triggered', 'acknowledged')
  AND updated_at >= now() - ($3::integer * interval '1 second')
LIMIT 1
`

type GetOpenAlertByServiceDedupKeyParams struct {
	ServiceID          uuid.UUID `json:"service_id"`
	DedupKey           string    `json:"dedup_key"`
	DedupWindowSeconds int32     `json:"dedup_window_seconds"`
}

func (q *Queries) GetOpenAlertByServiceDedupKey(ctx context.Context, arg GetOpenAlertByServiceDedupKeyParams) (Alert, error) {
	row := q.db.QueryRow(ctx, getOpenAlertByServiceDedupKey, arg.ServiceID, arg.DedupKey, arg.DedupWindowSeconds)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.IntegrationKeyID,
		&i.Status,
		&i.DedupKey,
		&i.Summary,
		&i.Description,
		&i.Priority,
		&i.EventCount,
		&i.EscalationState,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ClosedAt,
		&i.ResolvedAt,
		&i.ResolvedIntegration,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenAlertByServiceDedupKeyForResolve = `-- name: GetOpenAlertByServiceDedupKeyForResolve :one
SELECT id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, acknowledged_by_user_id, closed_at, resolved_at, resolved_integration, incident_id, created_at, updated_at
FROM alerts
WHERE service_id = $1
  AND dedup_key = $2
  AND status IN ('triggered', 'acknowledged')
LIMIT 1
`

type GetOpenAlertByServiceDedupKeyForResolveParams struct {
	ServiceID uuid.UUID `json:"service_id"`
	DedupKey  string    `json:"dedup_key"`
}

func (q *Queries) GetOpenAlertByServiceDedupKeyForResolve(ctx context.Context, arg GetOpenAlertByServiceDedupKeyForResolveParams) (Alert, error) {
	row := q.db.QueryRow(ctx, getOpenAlertByServiceDedupKeyForResolve, arg.ServiceID, arg.DedupKey)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.IntegrationKeyID,
		&i.Status,
		&i.DedupKey,
		&i.Summary,
		&i.Description,
		&i.Priority,
		&i.EventCount,
		&i.EscalationState,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ClosedAt,
		&i.ResolvedAt,
		&i.ResolvedIntegration,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementOpenAlertEventCount = `-- name: IncrementOpenAlertEventCount :one
UPDATE alerts
SET event_count = event_count + 1,
    updated_at = now()
WHERE service_id = $1
  AND dedup_key = $2
  AND status IN ('triggered', 'acknowledged')
  AND updated_at >= now() - ($3::integer * interval '1 second')
RETURNING id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, acknowledged_by_user_id, closed_at, resolved_at, resolved_integration, incident_id, created_at, updated_at
`

type IncrementOpenAlertEventCountParams struct {
	ServiceID          uuid.UUID `json:"service_id"`
	DedupKey           string    `json:"dedup_key"`
	DedupWindowSeconds int32     `json:"dedup_window_seconds"`
}

func (q *Queries) IncrementOpenAlertEventCount(ctx context.Context, arg IncrementOpenAlertEventCountParams) (Alert, error) {
	row := q.db.QueryRow(ctx, incrementOpenAlertEventCount, arg.ServiceID, arg.DedupKey, arg.DedupWindowSeconds)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.IntegrationKeyID,
		&i.Status,
		&i.DedupKey,
		&i.Summary,
		&i.Description,
		&i.Priority,
		&i.EventCount,
		&i.EscalationState,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ClosedAt,
		&i.ResolvedAt,
		&i.ResolvedIntegration,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlertsForOrgAdmin = `-- name: ListAlertsForOrgAdmin :many
SELECT id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, acknowledged_by_user_id, closed_at, resolved_at, resolved_integration, incident_id, created_at, updated_at
FROM alerts
WHERE organization_id = $1
  AND (
    $3::text IS NULL
    OR status = $3
  )
ORDER BY created_at DESC
LIMIT $2
`

type ListAlertsForOrgAdminParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Limit          int32       `json:"limit"`
	StatusFilter   pgtype.Text `json:"status_filter"`
}

func (q *Queries) ListAlertsForOrgAdmin(ctx context.Context, arg ListAlertsForOrgAdminParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsForOrgAdmin, arg.OrganizationID, arg.Limit, arg.StatusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ServiceID,
			&i.IntegrationKeyID,
			&i.Status,
			&i.DedupKey,
			&i.Summary,
			&i.Description,
			&i.Priority,
			&i.EventCount,
			&i.EscalationState,
			&i.AcknowledgedAt,
			&i.AcknowledgedByUserID,
			&i.ClosedAt,
			&i.ResolvedAt,
			&i.ResolvedIntegration,
			&i.IncidentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsForTeamMember = `-- name: ListAlertsForTeamMember :many
SELECT a.id, a.organization_id, a.service_id, a.integration_key_id, a.status, a.dedup_key, a.summary, a.description, a.priority, a.event_count, a.escalation_state, a.acknowledged_at, a.acknowledged_by_user_id, a.closed_at, a.resolved_at, a.resolved_integration, a.incident_id, a.created_at, a.updated_at
FROM alerts a
INNER JOIN services s
  ON s.id = a.service_id
 AND s.organization_id = a.organization_id
INNER JOIN team_memberships tm
  ON tm.team_id = s.team_id
 AND tm.user_id = $2
 AND tm.organization_id = a.organization_id
WHERE a.organization_id = $1
  AND (
    $4::text IS NULL
    OR a.status = $4
  )
ORDER BY a.created_at DESC
LIMIT $3
`

type ListAlertsForTeamMemberParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	UserID         uuid.UUID   `json:"user_id"`
	Limit          int32       `json:"limit"`
	StatusFilter   pgtype.Text `json:"status_filter"`
}

func (q *Queries) ListAlertsForTeamMember(ctx context.Context, arg ListAlertsForTeamMemberParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsForTeamMember,
		arg.OrganizationID,
		arg.UserID,
		arg.Limit,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ServiceID,
			&i.IntegrationKeyID,
			&i.Status,
			&i.DedupKey,
			&i.Summary,
			&i.Description,
			&i.Priority,
			&i.EventCount,
			&i.EscalationState,
			&i.AcknowledgedAt,
			&i.AcknowledgedByUserID,
			&i.ClosedAt,
			&i.ResolvedAt,
			&i.ResolvedIntegration,
			&i.IncidentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentUnassignedAlertsByService = `-- name: ListRecentUnassignedAlertsByService :many
SELECT id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, acknowledged_by_user_id, closed_at, resolved_at, resolved_integration, incident_id, created_at, updated_at
FROM alerts
WHERE service_id = $1
  AND organization_id = $2
  AND status IN ('triggered', 'acknowledged')
  AND incident_id IS NULL
  AND created_at >= now() - ($3::integer * interval '1 second')
ORDER BY created_at ASC
`

type ListRecentUnassignedAlertsByServiceParams struct {
	ServiceID      uuid.UUID `json:"service_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	WindowSeconds  int32     `json:"window_seconds"`
}

func (q *Queries) ListRecentUnassignedAlertsByService(ctx context.Context, arg ListRecentUnassignedAlertsByServiceParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listRecentUnassignedAlertsByService, arg.ServiceID, arg.OrganizationID, arg.WindowSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ServiceID,
			&i.IntegrationKeyID,
			&i.Status,
			&i.DedupKey,
			&i.Summary,
			&i.Description,
			&i.Priority,
			&i.EventCount,
			&i.EscalationState,
			&i.AcknowledgedAt,
			&i.AcknowledgedByUserID,
			&i.ClosedAt,
			&i.ResolvedAt,
			&i.ResolvedIntegration,
			&i.IncidentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reEscalateAlert = `-- name: ReEscalateAlert :one
UPDATE alerts
SET status = 'triggered',
    acknowledged_at = NULL,
    acknowledged_by_user_id = NULL,
    escalation_state = $3,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND status IN ('triggered', 'acknowledged')
RETURNING id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, acknowledged_by_user_id, closed_at, resolved_at, resolved_integration, incident_id, created_at, updated_at
`

type ReEscalateAlertParams struct {
	ID              uuid.UUID `json:"id"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	EscalationState []byte    `json:"escalation_state"`
}

func (q *Queries) ReEscalateAlert(ctx context.Context, arg ReEscalateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, reEscalateAlert, arg.ID, arg.OrganizationID, arg.EscalationState)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.IntegrationKeyID,
		&i.Status,
		&i.DedupKey,
		&i.Summary,
		&i.Description,
		&i.Priority,
		&i.EventCount,
		&i.EscalationState,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ClosedAt,
		&i.ResolvedAt,
		&i.ResolvedIntegration,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveOpenAlert = `-- name: ResolveOpenAlert :one
UPDATE alerts
SET status = 'closed',
    closed_at = now(),
    resolved_at = now(),
    resolved_integration = $4,
    escalation_state = $3,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND status IN ('triggered', 'acknowledged')
RETURNING id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, acknowledged_by_user_id, closed_at, resolved_at, resolved_integration, incident_id, created_at, updated_at
`

type ResolveOpenAlertParams struct {
	ID                  uuid.UUID   `json:"id"`
	OrganizationID      uuid.UUID   `json:"organization_id"`
	EscalationState     []byte      `json:"escalation_state"`
	ResolvedIntegration pgtype.Text `json:"resolved_integration"`
}

func (q *Queries) ResolveOpenAlert(ctx context.Context, arg ResolveOpenAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, resolveOpenAlert,
		arg.ID,
		arg.OrganizationID,
		arg.EscalationState,
		arg.ResolvedIntegration,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.IntegrationKeyID,
		&i.Status,
		&i.DedupKey,
		&i.Summary,
		&i.Description,
		&i.Priority,
		&i.EventCount,
		&i.EscalationState,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ClosedAt,
		&i.ResolvedAt,
		&i.ResolvedIntegration,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAlertEscalationState = `-- name: UpdateAlertEscalationState :one
UPDATE alerts
SET escalation_state = $3,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
RETURNING id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, acknowledged_by_user_id, closed_at, resolved_at, resolved_integration, incident_id, created_at, updated_at
`

type UpdateAlertEscalationStateParams struct {
	ID              uuid.UUID `json:"id"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	EscalationState []byte    `json:"escalation_state"`
}

func (q *Queries) UpdateAlertEscalationState(ctx context.Context, arg UpdateAlertEscalationStateParams) (Alert, error) {
	row := q.db.QueryRow(ctx, updateAlertEscalationState, arg.ID, arg.OrganizationID, arg.EscalationState)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.IntegrationKeyID,
		&i.Status,
		&i.DedupKey,
		&i.Summary,
		&i.Description,
		&i.Priority,
		&i.EventCount,
		&i.EscalationState,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ClosedAt,
		&i.ResolvedAt,
		&i.ResolvedIntegration,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
