// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const computeAlertAnalyticsRollup = `-- name: ComputeAlertAnalyticsRollup :one
SELECT
    AVG(
        CASE
            WHEN a.acknowledged_at IS NOT NULL
            THEN EXTRACT(EPOCH FROM (a.acknowledged_at - a.created_at))
        END
    ) AS mtta_seconds,
    SUM(
        CASE WHEN a.acknowledged_at IS NOT NULL THEN 1 ELSE 0 END
    )::integer AS acknowledged_count,
    AVG(
        CASE
            WHEN COALESCE(a.resolved_at, a.closed_at) IS NOT NULL
            THEN EXTRACT(EPOCH FROM (COALESCE(a.resolved_at, a.closed_at) - a.created_at))
        END
    ) AS mttr_seconds,
    SUM(
        CASE WHEN COALESCE(a.resolved_at, a.closed_at) IS NOT NULL THEN 1 ELSE 0 END
    )::integer AS resolved_count
FROM alerts a
INNER JOIN services s
    ON s.id = a.service_id
   AND s.organization_id = a.organization_id
WHERE a.organization_id = $1
  AND a.created_at >= $2
  AND (
    $3::uuid IS NULL
    OR s.team_id = $3
  )
  AND (
    $4::uuid IS NULL
    OR a.service_id = $4
  )
  AND (
    $5::boolean IS NOT TRUE
    OR NOT EXISTS (
      SELECT 1
      FROM maintenance_windows mw
      WHERE mw.service_id = a.service_id
        AND mw.organization_id = a.organization_id
        AND mw.starts_at <= a.created_at
        AND mw.ends_at > a.created_at
    )
  )
`

type ComputeAlertAnalyticsRollupParams struct {
	OrganizationID                 uuid.UUID          `json:"organization_id"`
	WindowStart                    pgtype.Timestamptz `json:"window_start"`
	TeamID                         pgtype.UUID        `json:"team_id"`
	ServiceID                      pgtype.UUID        `json:"service_id"`
	ExcludeMaintenanceWindowAlerts bool               `json:"exclude_maintenance_window_alerts"`
}

type ComputeAlertAnalyticsRollupRow struct {
	MttaSeconds       float64 `json:"mtta_seconds"`
	AcknowledgedCount int32   `json:"acknowledged_count"`
	MttrSeconds       float64 `json:"mttr_seconds"`
	ResolvedCount     int32   `json:"resolved_count"`
}

func (q *Queries) ComputeAlertAnalyticsRollup(ctx context.Context, arg ComputeAlertAnalyticsRollupParams) (ComputeAlertAnalyticsRollupRow, error) {
	row := q.db.QueryRow(ctx, computeAlertAnalyticsRollup,
		arg.OrganizationID,
		arg.WindowStart,
		arg.TeamID,
		arg.ServiceID,
		arg.ExcludeMaintenanceWindowAlerts,
	)
	var i ComputeAlertAnalyticsRollupRow
	err := row.Scan(
		&i.MttaSeconds,
		&i.AcknowledgedCount,
		&i.MttrSeconds,
		&i.ResolvedCount,
	)
	return i, err
}

const getOrganizationAnalyticsSettings = `-- name: GetOrganizationAnalyticsSettings :one
SELECT organization_id, exclude_maintenance_window_alerts, created_at, updated_at
FROM organization_analytics_settings
WHERE organization_id = $1
`

func (q *Queries) GetOrganizationAnalyticsSettings(ctx context.Context, organizationID uuid.UUID) (OrganizationAnalyticsSetting, error) {
	row := q.db.QueryRow(ctx, getOrganizationAnalyticsSettings, organizationID)
	var i OrganizationAnalyticsSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.ExcludeMaintenanceWindowAlerts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrganizationAnalyticsSettings = `-- name: UpsertOrganizationAnalyticsSettings :one
INSERT INTO organization_analytics_settings (
    organization_id,
    exclude_maintenance_window_alerts
) VALUES (
    $1,
    $2
)
ON CONFLICT (organization_id) DO UPDATE SET
    exclude_maintenance_window_alerts = EXCLUDED.exclude_maintenance_window_alerts,
    updated_at = now()
RETURNING organization_id, exclude_maintenance_window_alerts, created_at, updated_at
`

type UpsertOrganizationAnalyticsSettingsParams struct {
	OrganizationID                 uuid.UUID `json:"organization_id"`
	ExcludeMaintenanceWindowAlerts bool      `json:"exclude_maintenance_window_alerts"`
}

func (q *Queries) UpsertOrganizationAnalyticsSettings(ctx context.Context, arg UpsertOrganizationAnalyticsSettingsParams) (OrganizationAnalyticsSetting, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationAnalyticsSettings, arg.OrganizationID, arg.ExcludeMaintenanceWindowAlerts)
	var i OrganizationAnalyticsSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.ExcludeMaintenanceWindowAlerts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
