// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: escalation_step_targets.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEscalationStepTarget = `-- name: CreateEscalationStepTarget :one
INSERT INTO escalation_step_targets (
    id,
    escalation_step_id,
    organization_id,
    target_type,
    user_id,
    schedule_id,
    webhook_url,
    channels
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, escalation_step_id, organization_id, target_type, user_id, schedule_id, webhook_url, channels, created_at
`

type CreateEscalationStepTargetParams struct {
	ID               uuid.UUID   `json:"id"`
	EscalationStepID uuid.UUID   `json:"escalation_step_id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	TargetType       string      `json:"target_type"`
	UserID           pgtype.UUID `json:"user_id"`
	ScheduleID       pgtype.UUID `json:"schedule_id"`
	WebhookUrl       pgtype.Text `json:"webhook_url"`
	Channels         []byte      `json:"channels"`
}

func (q *Queries) CreateEscalationStepTarget(ctx context.Context, arg CreateEscalationStepTargetParams) (EscalationStepTarget, error) {
	row := q.db.QueryRow(ctx, createEscalationStepTarget,
		arg.ID,
		arg.EscalationStepID,
		arg.OrganizationID,
		arg.TargetType,
		arg.UserID,
		arg.ScheduleID,
		arg.WebhookUrl,
		arg.Channels,
	)
	var i EscalationStepTarget
	err := row.Scan(
		&i.ID,
		&i.EscalationStepID,
		&i.OrganizationID,
		&i.TargetType,
		&i.UserID,
		&i.ScheduleID,
		&i.WebhookUrl,
		&i.Channels,
		&i.CreatedAt,
	)
	return i, err
}

const listEscalationStepTargetsByStepID = `-- name: ListEscalationStepTargetsByStepID :many
SELECT id, escalation_step_id, organization_id, target_type, user_id, schedule_id, webhook_url, channels, created_at
FROM escalation_step_targets
WHERE escalation_step_id = $1
  AND organization_id = $2
ORDER BY created_at
`

type ListEscalationStepTargetsByStepIDParams struct {
	EscalationStepID uuid.UUID `json:"escalation_step_id"`
	OrganizationID   uuid.UUID `json:"organization_id"`
}

func (q *Queries) ListEscalationStepTargetsByStepID(ctx context.Context, arg ListEscalationStepTargetsByStepIDParams) ([]EscalationStepTarget, error) {
	rows, err := q.db.Query(ctx, listEscalationStepTargetsByStepID, arg.EscalationStepID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EscalationStepTarget{}
	for rows.Next() {
		var i EscalationStepTarget
		if err := rows.Scan(
			&i.ID,
			&i.EscalationStepID,
			&i.OrganizationID,
			&i.TargetType,
			&i.UserID,
			&i.ScheduleID,
			&i.WebhookUrl,
			&i.Channels,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
