// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: escalation_policies.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createEscalationPolicy = `-- name: CreateEscalationPolicy :one
INSERT INTO escalation_policies (
    id,
    organization_id,
    service_id,
    name
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, organization_id, service_id, name, created_at, updated_at
`

type CreateEscalationPolicyParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	ServiceID      uuid.UUID `json:"service_id"`
	Name           string    `json:"name"`
}

func (q *Queries) CreateEscalationPolicy(ctx context.Context, arg CreateEscalationPolicyParams) (EscalationPolicy, error) {
	row := q.db.QueryRow(ctx, createEscalationPolicy,
		arg.ID,
		arg.OrganizationID,
		arg.ServiceID,
		arg.Name,
	)
	var i EscalationPolicy
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEscalationPolicy = `-- name: DeleteEscalationPolicy :exec
DELETE FROM escalation_policies
WHERE id = $1
  AND organization_id = $2
`

type DeleteEscalationPolicyParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteEscalationPolicy(ctx context.Context, arg DeleteEscalationPolicyParams) error {
	_, err := q.db.Exec(ctx, deleteEscalationPolicy, arg.ID, arg.OrganizationID)
	return err
}

const getEscalationPolicyByID = `-- name: GetEscalationPolicyByID :one
SELECT id, organization_id, service_id, name, created_at, updated_at
FROM escalation_policies
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetEscalationPolicyByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetEscalationPolicyByID(ctx context.Context, arg GetEscalationPolicyByIDParams) (EscalationPolicy, error) {
	row := q.db.QueryRow(ctx, getEscalationPolicyByID, arg.ID, arg.OrganizationID)
	var i EscalationPolicy
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEscalationPoliciesByServiceID = `-- name: ListEscalationPoliciesByServiceID :many
SELECT id, organization_id, service_id, name, created_at, updated_at
FROM escalation_policies
WHERE service_id = $1
  AND organization_id = $2
ORDER BY created_at
`

type ListEscalationPoliciesByServiceIDParams struct {
	ServiceID      uuid.UUID `json:"service_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) ListEscalationPoliciesByServiceID(ctx context.Context, arg ListEscalationPoliciesByServiceIDParams) ([]EscalationPolicy, error) {
	rows, err := q.db.Query(ctx, listEscalationPoliciesByServiceID, arg.ServiceID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EscalationPolicy{}
	for rows.Next() {
		var i EscalationPolicy
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ServiceID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEscalationPolicy = `-- name: UpdateEscalationPolicy :one
UPDATE escalation_policies
SET name = $3,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
RETURNING id, organization_id, service_id, name, created_at, updated_at
`

type UpdateEscalationPolicyParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
}

func (q *Queries) UpdateEscalationPolicy(ctx context.Context, arg UpdateEscalationPolicyParams) (EscalationPolicy, error) {
	row := q.db.QueryRow(ctx, updateEscalationPolicy, arg.ID, arg.OrganizationID, arg.Name)
	var i EscalationPolicy
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
