// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package db

import (
	"context"
)

const coreSchemaReady = `-- name: CoreSchemaReady :one
SELECT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'organizations'
) AS ready
`

func (q *Queries) CoreSchemaReady(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, coreSchemaReady)
	var ready bool
	err := row.Scan(&ready)
	return ready, err
}

const pingDatabase = `-- name: PingDatabase :one
SELECT 1::integer AS ok
`

func (q *Queries) PingDatabase(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, pingDatabase)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}

const sessionsSchemaReady = `-- name: SessionsSchemaReady :one
SELECT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'sessions'
) AS ready
`

func (q *Queries) SessionsSchemaReady(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, sessionsSchemaReady)
	var ready bool
	err := row.Scan(&ready)
	return ready, err
}
