// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (
    id,
    organization_id,
    team_id,
    title,
    status,
    created_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'investigating',
    $5
)
RETURNING id, organization_id, team_id, title, status, created_by_user_id, resolved_at, slack_channel_id, slack_thread_ts, created_at, updated_at
`

type CreateIncidentParams struct {
	ID              uuid.UUID `json:"id"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	TeamID          uuid.UUID `json:"team_id"`
	Title           string    `json:"title"`
	CreatedByUserID uuid.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.ID,
		arg.OrganizationID,
		arg.TeamID,
		arg.Title,
		arg.CreatedByUserID,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Title,
		&i.Status,
		&i.CreatedByUserID,
		&i.ResolvedAt,
		&i.SlackChannelID,
		&i.SlackThreadTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIncidentRoleAssignment = `-- name: CreateIncidentRoleAssignment :one
INSERT INTO incident_role_assignments (
    id,
    incident_id,
    organization_id,
    role_definition_id,
    user_id,
    assigned_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, incident_id, organization_id, role_definition_id, user_id, assigned_by_user_id, created_at
`

type CreateIncidentRoleAssignmentParams struct {
	ID               uuid.UUID `json:"id"`
	IncidentID       uuid.UUID `json:"incident_id"`
	OrganizationID   uuid.UUID `json:"organization_id"`
	RoleDefinitionID uuid.UUID `json:"role_definition_id"`
	UserID           uuid.UUID `json:"user_id"`
	AssignedByUserID uuid.UUID `json:"assigned_by_user_id"`
}

func (q *Queries) CreateIncidentRoleAssignment(ctx context.Context, arg CreateIncidentRoleAssignmentParams) (IncidentRoleAssignment, error) {
	row := q.db.QueryRow(ctx, createIncidentRoleAssignment,
		arg.ID,
		arg.IncidentID,
		arg.OrganizationID,
		arg.RoleDefinitionID,
		arg.UserID,
		arg.AssignedByUserID,
	)
	var i IncidentRoleAssignment
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.OrganizationID,
		&i.RoleDefinitionID,
		&i.UserID,
		&i.AssignedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createIncidentRoleDefinition = `-- name: CreateIncidentRoleDefinition :one
INSERT INTO incident_role_definitions (
    id,
    organization_id,
    name,
    sort_order
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, organization_id, name, sort_order, created_at, updated_at
`

type CreateIncidentRoleDefinitionParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	SortOrder      int32     `json:"sort_order"`
}

func (q *Queries) CreateIncidentRoleDefinition(ctx context.Context, arg CreateIncidentRoleDefinitionParams) (IncidentRoleDefinition, error) {
	row := q.db.QueryRow(ctx, createIncidentRoleDefinition,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.SortOrder,
	)
	var i IncidentRoleDefinition
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTimelineEvent = `-- name: CreateTimelineEvent :one
INSERT INTO timeline_events (
    id,
    incident_id,
    organization_id,
    actor_id,
    event_type,
    body,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, incident_id, organization_id, actor_id, event_type, body, metadata, created_at
`

type CreateTimelineEventParams struct {
	ID             uuid.UUID   `json:"id"`
	IncidentID     uuid.UUID   `json:"incident_id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	ActorID        pgtype.UUID `json:"actor_id"`
	EventType      string      `json:"event_type"`
	Body           string      `json:"body"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) CreateTimelineEvent(ctx context.Context, arg CreateTimelineEventParams) (TimelineEvent, error) {
	row := q.db.QueryRow(ctx, createTimelineEvent,
		arg.ID,
		arg.IncidentID,
		arg.OrganizationID,
		arg.ActorID,
		arg.EventType,
		arg.Body,
		arg.Metadata,
	)
	var i TimelineEvent
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.OrganizationID,
		&i.ActorID,
		&i.EventType,
		&i.Body,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIncidentRoleAssignment = `-- name: DeleteIncidentRoleAssignment :exec
DELETE FROM incident_role_assignments
WHERE id = $1
  AND organization_id = $2
`

type DeleteIncidentRoleAssignmentParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteIncidentRoleAssignment(ctx context.Context, arg DeleteIncidentRoleAssignmentParams) error {
	_, err := q.db.Exec(ctx, deleteIncidentRoleAssignment, arg.ID, arg.OrganizationID)
	return err
}

const deleteIncidentRoleDefinition = `-- name: DeleteIncidentRoleDefinition :exec
DELETE FROM incident_role_definitions
WHERE id = $1
  AND organization_id = $2
`

type DeleteIncidentRoleDefinitionParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteIncidentRoleDefinition(ctx context.Context, arg DeleteIncidentRoleDefinitionParams) error {
	_, err := q.db.Exec(ctx, deleteIncidentRoleDefinition, arg.ID, arg.OrganizationID)
	return err
}

const getIncidentByID = `-- name: GetIncidentByID :one
SELECT id, organization_id, team_id, title, status, created_by_user_id, resolved_at, slack_channel_id, slack_thread_ts, created_at, updated_at
FROM incidents
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetIncidentByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetIncidentByID(ctx context.Context, arg GetIncidentByIDParams) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncidentByID, arg.ID, arg.OrganizationID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Title,
		&i.Status,
		&i.CreatedByUserID,
		&i.ResolvedAt,
		&i.SlackChannelID,
		&i.SlackThreadTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncidentRoleAssignmentByID = `-- name: GetIncidentRoleAssignmentByID :one
SELECT id, incident_id, organization_id, role_definition_id, user_id, assigned_by_user_id, created_at
FROM incident_role_assignments
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetIncidentRoleAssignmentByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetIncidentRoleAssignmentByID(ctx context.Context, arg GetIncidentRoleAssignmentByIDParams) (IncidentRoleAssignment, error) {
	row := q.db.QueryRow(ctx, getIncidentRoleAssignmentByID, arg.ID, arg.OrganizationID)
	var i IncidentRoleAssignment
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.OrganizationID,
		&i.RoleDefinitionID,
		&i.UserID,
		&i.AssignedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getIncidentRoleDefinitionByID = `-- name: GetIncidentRoleDefinitionByID :one
SELECT id, organization_id, name, sort_order, created_at, updated_at
FROM incident_role_definitions
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetIncidentRoleDefinitionByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetIncidentRoleDefinitionByID(ctx context.Context, arg GetIncidentRoleDefinitionByIDParams) (IncidentRoleDefinition, error) {
	row := q.db.QueryRow(ctx, getIncidentRoleDefinitionByID, arg.ID, arg.OrganizationID)
	var i IncidentRoleDefinition
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenIncidentForTeam = `-- name: GetOpenIncidentForTeam :one
SELECT id, organization_id, team_id, title, status, created_by_user_id, resolved_at, slack_channel_id, slack_thread_ts, created_at, updated_at
FROM incidents
WHERE organization_id = $1
  AND team_id = $2
  AND status <> 'resolved'
ORDER BY created_at DESC
LIMIT 1
`

type GetOpenIncidentForTeamParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	TeamID         uuid.UUID `json:"team_id"`
}

func (q *Queries) GetOpenIncidentForTeam(ctx context.Context, arg GetOpenIncidentForTeamParams) (Incident, error) {
	row := q.db.QueryRow(ctx, getOpenIncidentForTeam, arg.OrganizationID, arg.TeamID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Title,
		&i.Status,
		&i.CreatedByUserID,
		&i.ResolvedAt,
		&i.SlackChannelID,
		&i.SlackThreadTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenIncidentForTeamWithServiceAlerts = `-- name: GetOpenIncidentForTeamWithServiceAlerts :one
SELECT DISTINCT i.id, i.organization_id, i.team_id, i.title, i.status, i.created_by_user_id, i.resolved_at, i.slack_channel_id, i.slack_thread_ts, i.created_at, i.updated_at
FROM incidents i
INNER JOIN alerts a
  ON a.incident_id = i.id
 AND a.organization_id = i.organization_id
WHERE i.organization_id = $1
  AND i.team_id = $2
  AND i.status <> 'resolved'
  AND a.service_id = $3
ORDER BY i.created_at DESC
LIMIT 1
`

type GetOpenIncidentForTeamWithServiceAlertsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	TeamID         uuid.UUID `json:"team_id"`
	ServiceID      uuid.UUID `json:"service_id"`
}

func (q *Queries) GetOpenIncidentForTeamWithServiceAlerts(ctx context.Context, arg GetOpenIncidentForTeamWithServiceAlertsParams) (Incident, error) {
	row := q.db.QueryRow(ctx, getOpenIncidentForTeamWithServiceAlerts, arg.OrganizationID, arg.TeamID, arg.ServiceID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Title,
		&i.Status,
		&i.CreatedByUserID,
		&i.ResolvedAt,
		&i.SlackChannelID,
		&i.SlackThreadTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTimelineEventByID = `-- name: GetTimelineEventByID :one
SELECT id, incident_id, organization_id, actor_id, event_type, body, metadata, created_at
FROM timeline_events
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetTimelineEventByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetTimelineEventByID(ctx context.Context, arg GetTimelineEventByIDParams) (TimelineEvent, error) {
	row := q.db.QueryRow(ctx, getTimelineEventByID, arg.ID, arg.OrganizationID)
	var i TimelineEvent
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.OrganizationID,
		&i.ActorID,
		&i.EventType,
		&i.Body,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAlertsByIncidentID = `-- name: ListAlertsByIncidentID :many
SELECT id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, acknowledged_by_user_id, closed_at, resolved_at, resolved_integration, incident_id, created_at, updated_at
FROM alerts
WHERE incident_id = $1
  AND organization_id = $2
ORDER BY created_at ASC
`

type ListAlertsByIncidentIDParams struct {
	IncidentID     pgtype.UUID `json:"incident_id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
}

func (q *Queries) ListAlertsByIncidentID(ctx context.Context, arg ListAlertsByIncidentIDParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsByIncidentID, arg.IncidentID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ServiceID,
			&i.IntegrationKeyID,
			&i.Status,
			&i.DedupKey,
			&i.Summary,
			&i.Description,
			&i.Priority,
			&i.EventCount,
			&i.EscalationState,
			&i.AcknowledgedAt,
			&i.AcknowledgedByUserID,
			&i.ClosedAt,
			&i.ResolvedAt,
			&i.ResolvedIntegration,
			&i.IncidentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentRoleAssignmentsByIncidentID = `-- name: ListIncidentRoleAssignmentsByIncidentID :many
SELECT id, incident_id, organization_id, role_definition_id, user_id, assigned_by_user_id, created_at
FROM incident_role_assignments
WHERE incident_id = $1
  AND organization_id = $2
ORDER BY created_at ASC
`

type ListIncidentRoleAssignmentsByIncidentIDParams struct {
	IncidentID     uuid.UUID `json:"incident_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) ListIncidentRoleAssignmentsByIncidentID(ctx context.Context, arg ListIncidentRoleAssignmentsByIncidentIDParams) ([]IncidentRoleAssignment, error) {
	rows, err := q.db.Query(ctx, listIncidentRoleAssignmentsByIncidentID, arg.IncidentID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentRoleAssignment{}
	for rows.Next() {
		var i IncidentRoleAssignment
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.OrganizationID,
			&i.RoleDefinitionID,
			&i.UserID,
			&i.AssignedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentRoleDefinitions = `-- name: ListIncidentRoleDefinitions :many
SELECT id, organization_id, name, sort_order, created_at, updated_at
FROM incident_role_definitions
WHERE organization_id = $1
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListIncidentRoleDefinitions(ctx context.Context, organizationID uuid.UUID) ([]IncidentRoleDefinition, error) {
	rows, err := q.db.Query(ctx, listIncidentRoleDefinitions, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentRoleDefinition{}
	for rows.Next() {
		var i IncidentRoleDefinition
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentsForOrgAdmin = `-- name: ListIncidentsForOrgAdmin :many
SELECT id, organization_id, team_id, title, status, created_by_user_id, resolved_at, slack_channel_id, slack_thread_ts, created_at, updated_at
FROM incidents
WHERE organization_id = $1
  AND (
    $3::text IS NULL
    OR status = $3
  )
  AND (
    $4::uuid IS NULL
    OR team_id = $4
  )
ORDER BY created_at DESC
LIMIT $2
`

type ListIncidentsForOrgAdminParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Limit          int32       `json:"limit"`
	StatusFilter   pgtype.Text `json:"status_filter"`
	TeamIDFilter   pgtype.UUID `json:"team_id_filter"`
}

func (q *Queries) ListIncidentsForOrgAdmin(ctx context.Context, arg ListIncidentsForOrgAdminParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidentsForOrgAdmin,
		arg.OrganizationID,
		arg.Limit,
		arg.StatusFilter,
		arg.TeamIDFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TeamID,
			&i.Title,
			&i.Status,
			&i.CreatedByUserID,
			&i.ResolvedAt,
			&i.SlackChannelID,
			&i.SlackThreadTs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentsForTeamMember = `-- name: ListIncidentsForTeamMember :many
SELECT i.id, i.organization_id, i.team_id, i.title, i.status, i.created_by_user_id, i.resolved_at, i.slack_channel_id, i.slack_thread_ts, i.created_at, i.updated_at
FROM incidents i
INNER JOIN team_memberships tm
  ON tm.team_id = i.team_id
 AND tm.user_id = $2
 AND tm.organization_id = i.organization_id
WHERE i.organization_id = $1
  AND (
    $4::text IS NULL
    OR i.status = $4
  )
  AND (
    $5::uuid IS NULL
    OR i.team_id = $5
  )
ORDER BY i.created_at DESC
LIMIT $3
`

type ListIncidentsForTeamMemberParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	UserID         uuid.UUID   `json:"user_id"`
	Limit          int32       `json:"limit"`
	StatusFilter   pgtype.Text `json:"status_filter"`
	TeamIDFilter   pgtype.UUID `json:"team_id_filter"`
}

func (q *Queries) ListIncidentsForTeamMember(ctx context.Context, arg ListIncidentsForTeamMemberParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidentsForTeamMember,
		arg.OrganizationID,
		arg.UserID,
		arg.Limit,
		arg.StatusFilter,
		arg.TeamIDFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TeamID,
			&i.Title,
			&i.Status,
			&i.CreatedByUserID,
			&i.ResolvedAt,
			&i.SlackChannelID,
			&i.SlackThreadTs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineEventsByIncidentID = `-- name: ListTimelineEventsByIncidentID :many
SELECT id, incident_id, organization_id, actor_id, event_type, body, metadata, created_at
FROM timeline_events
WHERE incident_id = $1
  AND organization_id = $2
ORDER BY created_at ASC
`

type ListTimelineEventsByIncidentIDParams struct {
	IncidentID     uuid.UUID `json:"incident_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) ListTimelineEventsByIncidentID(ctx context.Context, arg ListTimelineEventsByIncidentIDParams) ([]TimelineEvent, error) {
	rows, err := q.db.Query(ctx, listTimelineEventsByIncidentID, arg.IncidentID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimelineEvent{}
	for rows.Next() {
		var i TimelineEvent
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.OrganizationID,
			&i.ActorID,
			&i.EventType,
			&i.Body,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncidentRoleDefinition = `-- name: UpdateIncidentRoleDefinition :one
UPDATE incident_role_definitions
SET name = $3,
    sort_order = $4,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
RETURNING id, organization_id, name, sort_order, created_at, updated_at
`

type UpdateIncidentRoleDefinitionParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	SortOrder      int32     `json:"sort_order"`
}

func (q *Queries) UpdateIncidentRoleDefinition(ctx context.Context, arg UpdateIncidentRoleDefinitionParams) (IncidentRoleDefinition, error) {
	row := q.db.QueryRow(ctx, updateIncidentRoleDefinition,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.SortOrder,
	)
	var i IncidentRoleDefinition
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIncidentSlackChannelID = `-- name: UpdateIncidentSlackChannelID :one
UPDATE incidents
SET slack_channel_id = $3,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
RETURNING id, organization_id, team_id, title, status, created_by_user_id, resolved_at, slack_channel_id, slack_thread_ts, created_at, updated_at
`

type UpdateIncidentSlackChannelIDParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	SlackChannelID pgtype.Text `json:"slack_channel_id"`
}

func (q *Queries) UpdateIncidentSlackChannelID(ctx context.Context, arg UpdateIncidentSlackChannelIDParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncidentSlackChannelID, arg.ID, arg.OrganizationID, arg.SlackChannelID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Title,
		&i.Status,
		&i.CreatedByUserID,
		&i.ResolvedAt,
		&i.SlackChannelID,
		&i.SlackThreadTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIncidentSlackThreadTS = `-- name: UpdateIncidentSlackThreadTS :one
UPDATE incidents
SET slack_thread_ts = $3,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
RETURNING id, organization_id, team_id, title, status, created_by_user_id, resolved_at, slack_channel_id, slack_thread_ts, created_at, updated_at
`

type UpdateIncidentSlackThreadTSParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	SlackThreadTs  pgtype.Text `json:"slack_thread_ts"`
}

func (q *Queries) UpdateIncidentSlackThreadTS(ctx context.Context, arg UpdateIncidentSlackThreadTSParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncidentSlackThreadTS, arg.ID, arg.OrganizationID, arg.SlackThreadTs)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Title,
		&i.Status,
		&i.CreatedByUserID,
		&i.ResolvedAt,
		&i.SlackChannelID,
		&i.SlackThreadTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIncidentStatus = `-- name: UpdateIncidentStatus :one
UPDATE incidents
SET status = $3,
    resolved_at = CASE
        WHEN $3 = 'resolved' THEN now()
        ELSE NULL
    END,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
RETURNING id, organization_id, team_id, title, status, created_by_user_id, resolved_at, slack_channel_id, slack_thread_ts, created_at, updated_at
`

type UpdateIncidentStatusParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Status         string    `json:"status"`
}

func (q *Queries) UpdateIncidentStatus(ctx context.Context, arg UpdateIncidentStatusParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncidentStatus, arg.ID, arg.OrganizationID, arg.Status)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Title,
		&i.Status,
		&i.CreatedByUserID,
		&i.ResolvedAt,
		&i.SlackChannelID,
		&i.SlackThreadTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
