// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integration_keys.sql

package db

import (
	"context"
)

const getActiveIntegrationKeyByTokenHash = `-- name: GetActiveIntegrationKeyByTokenHash :one
SELECT id, service_id, organization_id, token, prefix, plugin_name, config, revoked_at, created_at, updated_at
FROM integration_keys
WHERE token = $1
  AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveIntegrationKeyByTokenHash(ctx context.Context, token string) (IntegrationKey, error) {
	row := q.db.QueryRow(ctx, getActiveIntegrationKeyByTokenHash, token)
	var i IntegrationKey
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.OrganizationID,
		&i.Token,
		&i.Prefix,
		&i.PluginName,
		&i.Config,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
