// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mobile_devices.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listMobileDevicesForUser = `-- name: ListMobileDevicesForUser :many
SELECT id, organization_id, user_id, refresh_token_id, expo_push_token, push_token_prefix, platform, device_label, revoked_at, last_registered_at, created_at, updated_at
FROM mobile_devices
WHERE organization_id = $1
  AND user_id = $2
ORDER BY last_registered_at DESC
`

type ListMobileDevicesForUserParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) ListMobileDevicesForUser(ctx context.Context, arg ListMobileDevicesForUserParams) ([]MobileDevice, error) {
	rows, err := q.db.Query(ctx, listMobileDevicesForUser, arg.OrganizationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MobileDevice{}
	for rows.Next() {
		var i MobileDevice
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.RefreshTokenID,
			&i.ExpoPushToken,
			&i.PushTokenPrefix,
			&i.Platform,
			&i.DeviceLabel,
			&i.RevokedAt,
			&i.LastRegisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeMobileDevice = `-- name: RevokeMobileDevice :one
UPDATE mobile_devices
SET revoked_at = now(),
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND user_id = $3
  AND revoked_at IS NULL
RETURNING id, organization_id, user_id, refresh_token_id, expo_push_token, push_token_prefix, platform, device_label, revoked_at, last_registered_at, created_at, updated_at
`

type RevokeMobileDeviceParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeMobileDevice(ctx context.Context, arg RevokeMobileDeviceParams) (MobileDevice, error) {
	row := q.db.QueryRow(ctx, revokeMobileDevice, arg.ID, arg.OrganizationID, arg.UserID)
	var i MobileDevice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.RefreshTokenID,
		&i.ExpoPushToken,
		&i.PushTokenPrefix,
		&i.Platform,
		&i.DeviceLabel,
		&i.RevokedAt,
		&i.LastRegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMobileDevice = `-- name: UpsertMobileDevice :one
INSERT INTO mobile_devices (
    id,
    organization_id,
    user_id,
    refresh_token_id,
    expo_push_token,
    push_token_prefix,
    platform,
    device_label,
    last_registered_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    now()
)
ON CONFLICT (expo_push_token) DO UPDATE
SET user_id = EXCLUDED.user_id,
    organization_id = EXCLUDED.organization_id,
    refresh_token_id = EXCLUDED.refresh_token_id,
    push_token_prefix = EXCLUDED.push_token_prefix,
    platform = EXCLUDED.platform,
    device_label = EXCLUDED.device_label,
    revoked_at = NULL,
    last_registered_at = now(),
    updated_at = now()
RETURNING id, organization_id, user_id, refresh_token_id, expo_push_token, push_token_prefix, platform, device_label, revoked_at, last_registered_at, created_at, updated_at
`

type UpsertMobileDeviceParams struct {
	ID              uuid.UUID   `json:"id"`
	OrganizationID  uuid.UUID   `json:"organization_id"`
	UserID          uuid.UUID   `json:"user_id"`
	RefreshTokenID  pgtype.UUID `json:"refresh_token_id"`
	ExpoPushToken   string      `json:"expo_push_token"`
	PushTokenPrefix string      `json:"push_token_prefix"`
	Platform        pgtype.Text `json:"platform"`
	DeviceLabel     pgtype.Text `json:"device_label"`
}

func (q *Queries) UpsertMobileDevice(ctx context.Context, arg UpsertMobileDeviceParams) (MobileDevice, error) {
	row := q.db.QueryRow(ctx, upsertMobileDevice,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.RefreshTokenID,
		arg.ExpoPushToken,
		arg.PushTokenPrefix,
		arg.Platform,
		arg.DeviceLabel,
	)
	var i MobileDevice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.RefreshTokenID,
		&i.ExpoPushToken,
		&i.PushTokenPrefix,
		&i.Platform,
		&i.DeviceLabel,
		&i.RevokedAt,
		&i.LastRegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
