// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mobile_auth_codes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMobileAuthCode = `-- name: CreateMobileAuthCode :one
INSERT INTO mobile_auth_codes (
    id,
    user_id,
    organization_id,
    code_hash,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, organization_id, code_hash, expires_at, used_at, created_at, updated_at
`

type CreateMobileAuthCodeParams struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	CodeHash       string             `json:"code_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateMobileAuthCode(ctx context.Context, arg CreateMobileAuthCodeParams) (MobileAuthCode, error) {
	row := q.db.QueryRow(ctx, createMobileAuthCode,
		arg.ID,
		arg.UserID,
		arg.OrganizationID,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i MobileAuthCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMobileAuthCodeByHash = `-- name: GetMobileAuthCodeByHash :one
SELECT id, user_id, organization_id, code_hash, expires_at, used_at, created_at, updated_at
FROM mobile_auth_codes
WHERE code_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
LIMIT 1
`

func (q *Queries) GetMobileAuthCodeByHash(ctx context.Context, codeHash string) (MobileAuthCode, error) {
	row := q.db.QueryRow(ctx, getMobileAuthCodeByHash, codeHash)
	var i MobileAuthCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markMobileAuthCodeUsed = `-- name: MarkMobileAuthCodeUsed :exec
UPDATE mobile_auth_codes
SET used_at = now(),
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND used_at IS NULL
`

type MarkMobileAuthCodeUsedParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) MarkMobileAuthCodeUsed(ctx context.Context, arg MarkMobileAuthCodeUsedParams) error {
	_, err := q.db.Exec(ctx, markMobileAuthCodeUsed, arg.ID, arg.OrganizationID)
	return err
}
