// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID                   uuid.UUID          `json:"id"`
	OrganizationID       uuid.UUID          `json:"organization_id"`
	ServiceID            uuid.UUID          `json:"service_id"`
	IntegrationKeyID     pgtype.UUID        `json:"integration_key_id"`
	Status               string             `json:"status"`
	DedupKey             string             `json:"dedup_key"`
	Summary              string             `json:"summary"`
	Description          pgtype.Text        `json:"description"`
	Priority             string             `json:"priority"`
	EventCount           int32              `json:"event_count"`
	EscalationState      []byte             `json:"escalation_state"`
	AcknowledgedAt       pgtype.Timestamptz `json:"acknowledged_at"`
	AcknowledgedByUserID pgtype.UUID        `json:"acknowledged_by_user_id"`
	ClosedAt             pgtype.Timestamptz `json:"closed_at"`
	ResolvedAt           pgtype.Timestamptz `json:"resolved_at"`
	ResolvedIntegration  pgtype.Text        `json:"resolved_integration"`
	IncidentID           pgtype.UUID        `json:"incident_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type AuditEvent struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ActorID        pgtype.UUID        `json:"actor_id"`
	Action         string             `json:"action"`
	TargetType     pgtype.Text        `json:"target_type"`
	TargetID       pgtype.UUID        `json:"target_id"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type EscalationPolicy struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ServiceID      uuid.UUID          `json:"service_id"`
	Name           string             `json:"name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type EscalationStep struct {
	ID                 uuid.UUID          `json:"id"`
	EscalationPolicyID uuid.UUID          `json:"escalation_policy_id"`
	OrganizationID     uuid.UUID          `json:"organization_id"`
	StepOrder          int32              `json:"step_order"`
	DelayMinutes       int32              `json:"delay_minutes"`
	RepeatLastStep     bool               `json:"repeat_last_step"`
	MaxRepeats         pgtype.Int4        `json:"max_repeats"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type EscalationStepTarget struct {
	ID               uuid.UUID          `json:"id"`
	EscalationStepID uuid.UUID          `json:"escalation_step_id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	TargetType       string             `json:"target_type"`
	UserID           pgtype.UUID        `json:"user_id"`
	ScheduleID       pgtype.UUID        `json:"schedule_id"`
	WebhookUrl       pgtype.Text        `json:"webhook_url"`
	Channels         []byte             `json:"channels"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type HeartbeatMonitor struct {
	ID              uuid.UUID          `json:"id"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	ServiceID       uuid.UUID          `json:"service_id"`
	Name            string             `json:"name"`
	IntervalSeconds int32              `json:"interval_seconds"`
	GraceSeconds    int32              `json:"grace_seconds"`
	TokenHash       string             `json:"token_hash"`
	Prefix          string             `json:"prefix"`
	Status          string             `json:"status"`
	LastPingAt      pgtype.Timestamptz `json:"last_ping_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Incident struct {
	ID              uuid.UUID          `json:"id"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	TeamID          uuid.UUID          `json:"team_id"`
	Title           string             `json:"title"`
	Status          string             `json:"status"`
	CreatedByUserID uuid.UUID          `json:"created_by_user_id"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	SlackChannelID  pgtype.Text        `json:"slack_channel_id"`
	SlackThreadTs   pgtype.Text        `json:"slack_thread_ts"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type IncidentRoleAssignment struct {
	ID               uuid.UUID          `json:"id"`
	IncidentID       uuid.UUID          `json:"incident_id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	RoleDefinitionID uuid.UUID          `json:"role_definition_id"`
	UserID           uuid.UUID          `json:"user_id"`
	AssignedByUserID uuid.UUID          `json:"assigned_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type IncidentRoleDefinition struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Name           string             `json:"name"`
	SortOrder      int32              `json:"sort_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type IntegrationKey struct {
	ID             uuid.UUID          `json:"id"`
	ServiceID      uuid.UUID          `json:"service_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Token          string             `json:"token"`
	Prefix         string             `json:"prefix"`
	PluginName     string             `json:"plugin_name"`
	Config         []byte             `json:"config"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type MaintenanceWindow struct {
	ID                    uuid.UUID          `json:"id"`
	OrganizationID        uuid.UUID          `json:"organization_id"`
	ServiceID             uuid.UUID          `json:"service_id"`
	Description           string             `json:"description"`
	StartsAt              pgtype.Timestamptz `json:"starts_at"`
	EndsAt                pgtype.Timestamptz `json:"ends_at"`
	SuppressNotifications bool               `json:"suppress_notifications"`
	SuppressIngestion     bool               `json:"suppress_ingestion"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type MobileAuthCode struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	CodeHash       string             `json:"code_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	UsedAt         pgtype.Timestamptz `json:"used_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type MobileDevice struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenID   pgtype.UUID        `json:"refresh_token_id"`
	ExpoPushToken    string             `json:"expo_push_token"`
	PushTokenPrefix  string             `json:"push_token_prefix"`
	Platform         pgtype.Text        `json:"platform"`
	DeviceLabel      pgtype.Text        `json:"device_label"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	LastRegisteredAt pgtype.Timestamptz `json:"last_registered_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type NotificationAttempt struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	AlertID          uuid.UUID          `json:"alert_id"`
	EscalationStepID pgtype.UUID        `json:"escalation_step_id"`
	Channel          string             `json:"channel"`
	Status           string             `json:"status"`
	Recipient        []byte             `json:"recipient"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	SentAt           pgtype.Timestamptz `json:"sent_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationSamlSetting struct {
	OrganizationID         uuid.UUID          `json:"organization_id"`
	Enabled                bool               `json:"enabled"`
	IdpEntityID            string             `json:"idp_entity_id"`
	IdpSsoUrl              string             `json:"idp_sso_url"`
	IdpCertificatePem      string             `json:"idp_certificate_pem"`
	SpCertificatePem       string             `json:"sp_certificate_pem"`
	SpPrivateKeyCiphertext []byte             `json:"sp_private_key_ciphertext"`
	SpEncryptionKeyID      string             `json:"sp_encryption_key_id"`
	CertificateHint        string             `json:"certificate_hint"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationSlackSetting struct {
	OrganizationID     uuid.UUID          `json:"organization_id"`
	BotTokenCiphertext []byte             `json:"bot_token_ciphertext"`
	EncryptionKeyID    string             `json:"encryption_key_id"`
	TokenHint          string             `json:"token_hint"`
	WorkspaceID        pgtype.Text        `json:"workspace_id"`
	WorkspaceName      pgtype.Text        `json:"workspace_name"`
	BotUserID          pgtype.Text        `json:"bot_user_id"`
	Scope              pgtype.Text        `json:"scope"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Override struct {
	ID               uuid.UUID          `json:"id"`
	ScheduleID       uuid.UUID          `json:"schedule_id"`
	RotationID       uuid.UUID          `json:"rotation_id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	UserID           uuid.UUID          `json:"user_id"`
	ReplacedUserID   pgtype.UUID        `json:"replaced_user_id"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	CreatedByUserID  uuid.UUID          `json:"created_by_user_id"`
	ApprovedByUserID pgtype.UUID        `json:"approved_by_user_id"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PasswordResetToken struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	TokenHash      string             `json:"token_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	UsedAt         pgtype.Timestamptz `json:"used_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	TokenHash      string             `json:"token_hash"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Rotation struct {
	ID             uuid.UUID          `json:"id"`
	ScheduleID     uuid.UUID          `json:"schedule_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Name           string             `json:"name"`
	Layer          int32              `json:"layer"`
	Rrule          string             `json:"rrule"`
	Participants   []byte             `json:"participants"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Schedule struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	TeamID         uuid.UUID          `json:"team_id"`
	Name           string             `json:"name"`
	Timezone       string             `json:"timezone"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Service struct {
	ID                                      uuid.UUID          `json:"id"`
	OrganizationID                          uuid.UUID          `json:"organization_id"`
	TeamID                                  uuid.UUID          `json:"team_id"`
	Name                                    string             `json:"name"`
	DedupWindowSeconds                      int32              `json:"dedup_window_seconds"`
	AutoPromoteEnabled                      bool               `json:"auto_promote_enabled"`
	AutoPromoteAlertThreshold               int32              `json:"auto_promote_alert_threshold"`
	AutoPromoteWindowSeconds                int32              `json:"auto_promote_window_seconds"`
	AutoPromoteSuppressEscalationPriorities []string           `json:"auto_promote_suppress_escalation_priorities"`
	DeletedAt                               pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt                               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                               pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Team struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Name           string             `json:"name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TeamMembership struct {
	ID             uuid.UUID          `json:"id"`
	TeamID         uuid.UUID          `json:"team_id"`
	UserID         uuid.UUID          `json:"user_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TimelineEvent struct {
	ID             uuid.UUID          `json:"id"`
	IncidentID     uuid.UUID          `json:"incident_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ActorID        pgtype.UUID        `json:"actor_id"`
	EventType      string             `json:"event_type"`
	Body           string             `json:"body"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Email          string             `json:"email"`
	PasswordHash   pgtype.Text        `json:"password_hash"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type UserContactMethod struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Channel        string             `json:"channel"`
	Config         []byte             `json:"config"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type UserNotificationRule struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Priority       string             `json:"priority"`
	Steps          []byte             `json:"steps"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
