// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_slack_settings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getOrganizationSlackSettings = `-- name: GetOrganizationSlackSettings :one
SELECT organization_id, bot_token_ciphertext, encryption_key_id, token_hint, created_at, updated_at
FROM organization_slack_settings
WHERE organization_id = $1
LIMIT 1
`

func (q *Queries) GetOrganizationSlackSettings(ctx context.Context, organizationID uuid.UUID) (OrganizationSlackSetting, error) {
	row := q.db.QueryRow(ctx, getOrganizationSlackSettings, organizationID)
	var i OrganizationSlackSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.BotTokenCiphertext,
		&i.EncryptionKeyID,
		&i.TokenHint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrganizationSlackSettings = `-- name: UpsertOrganizationSlackSettings :one
INSERT INTO organization_slack_settings (
    organization_id,
    bot_token_ciphertext,
    encryption_key_id,
    token_hint
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (organization_id) DO UPDATE
SET bot_token_ciphertext = EXCLUDED.bot_token_ciphertext,
    encryption_key_id = EXCLUDED.encryption_key_id,
    token_hint = EXCLUDED.token_hint,
    updated_at = now()
RETURNING organization_id, bot_token_ciphertext, encryption_key_id, token_hint, created_at, updated_at
`

type UpsertOrganizationSlackSettingsParams struct {
	OrganizationID     uuid.UUID `json:"organization_id"`
	BotTokenCiphertext []byte    `json:"bot_token_ciphertext"`
	EncryptionKeyID    string    `json:"encryption_key_id"`
	TokenHint          string    `json:"token_hint"`
}

func (q *Queries) UpsertOrganizationSlackSettings(ctx context.Context, arg UpsertOrganizationSlackSettingsParams) (OrganizationSlackSetting, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationSlackSettings,
		arg.OrganizationID,
		arg.BotTokenCiphertext,
		arg.EncryptionKeyID,
		arg.TokenHint,
	)
	var i OrganizationSlackSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.BotTokenCiphertext,
		&i.EncryptionKeyID,
		&i.TokenHint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
