// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_ticketing_settings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getOrganizationTicketingSettings = `-- name: GetOrganizationTicketingSettings :one
SELECT organization_id, plugin_name, config, api_token_ciphertext, encryption_key_id, token_hint, created_at, updated_at
FROM organization_ticketing_settings
WHERE organization_id = $1
LIMIT 1
`

func (q *Queries) GetOrganizationTicketingSettings(ctx context.Context, organizationID uuid.UUID) (OrganizationTicketingSetting, error) {
	row := q.db.QueryRow(ctx, getOrganizationTicketingSettings, organizationID)
	var i OrganizationTicketingSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.PluginName,
		&i.Config,
		&i.ApiTokenCiphertext,
		&i.EncryptionKeyID,
		&i.TokenHint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrganizationTicketingSettings = `-- name: UpsertOrganizationTicketingSettings :one
INSERT INTO organization_ticketing_settings (
    organization_id,
    plugin_name,
    config,
    api_token_ciphertext,
    encryption_key_id,
    token_hint
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (organization_id) DO UPDATE
SET plugin_name = EXCLUDED.plugin_name,
    config = EXCLUDED.config,
    api_token_ciphertext = EXCLUDED.api_token_ciphertext,
    encryption_key_id = EXCLUDED.encryption_key_id,
    token_hint = EXCLUDED.token_hint,
    updated_at = now()
RETURNING organization_id, plugin_name, config, api_token_ciphertext, encryption_key_id, token_hint, created_at, updated_at
`

type UpsertOrganizationTicketingSettingsParams struct {
	OrganizationID     uuid.UUID `json:"organization_id"`
	PluginName         string    `json:"plugin_name"`
	Config             []byte    `json:"config"`
	ApiTokenCiphertext []byte    `json:"api_token_ciphertext"`
	EncryptionKeyID    string    `json:"encryption_key_id"`
	TokenHint          string    `json:"token_hint"`
}

func (q *Queries) UpsertOrganizationTicketingSettings(ctx context.Context, arg UpsertOrganizationTicketingSettingsParams) (OrganizationTicketingSetting, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationTicketingSettings,
		arg.OrganizationID,
		arg.PluginName,
		arg.Config,
		arg.ApiTokenCiphertext,
		arg.EncryptionKeyID,
		arg.TokenHint,
	)
	var i OrganizationTicketingSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.PluginName,
		&i.Config,
		&i.ApiTokenCiphertext,
		&i.EncryptionKeyID,
		&i.TokenHint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
