// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bootstrapOrganizationWithAdmin = `-- name: BootstrapOrganizationWithAdmin :one
WITH new_org AS (
    INSERT INTO organizations (id, name)
    VALUES ($1, $2)
    RETURNING id, name, created_at, updated_at
),
new_user AS (
    INSERT INTO users (id, organization_id, email, password_hash, role)
    VALUES ($3, (SELECT id FROM new_org), $4, $5, 'admin')
    RETURNING id, organization_id, email, password_hash, role, scim_external_id, deprovisioned_at, created_at, updated_at
)
SELECT
    new_org.id AS organization_id,
    new_org.name AS organization_name,
    new_user.id AS user_id,
    new_user.email AS user_email,
    new_user.role AS user_role
FROM new_org,
     new_user
`

type BootstrapOrganizationWithAdminParams struct {
	OrgID        uuid.UUID   `json:"org_id"`
	OrgName      string      `json:"org_name"`
	UserID       uuid.UUID   `json:"user_id"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

type BootstrapOrganizationWithAdminRow struct {
	OrganizationID   uuid.UUID `json:"organization_id"`
	OrganizationName string    `json:"organization_name"`
	UserID           uuid.UUID `json:"user_id"`
	UserEmail        string    `json:"user_email"`
	UserRole         string    `json:"user_role"`
}

func (q *Queries) BootstrapOrganizationWithAdmin(ctx context.Context, arg BootstrapOrganizationWithAdminParams) (BootstrapOrganizationWithAdminRow, error) {
	row := q.db.QueryRow(ctx, bootstrapOrganizationWithAdmin,
		arg.OrgID,
		arg.OrgName,
		arg.UserID,
		arg.Email,
		arg.PasswordHash,
	)
	var i BootstrapOrganizationWithAdminRow
	err := row.Scan(
		&i.OrganizationID,
		&i.OrganizationName,
		&i.UserID,
		&i.UserEmail,
		&i.UserRole,
	)
	return i, err
}

const countOrganizations = `-- name: CountOrganizations :one
SELECT count(*)::bigint AS count
FROM organizations
`

func (q *Queries) CountOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    id,
    name
) VALUES (
    $1,
    $2
)
RETURNING id, name, created_at, updated_at
`

type CreateOrganizationParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.ID, arg.Name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFirstOrganization = `-- name: GetFirstOrganization :one
SELECT id, name, created_at, updated_at
FROM organizations
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetFirstOrganization(ctx context.Context) (Organization, error) {
	row := q.db.QueryRow(ctx, getFirstOrganization)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, created_at, updated_at
FROM organizations
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
