// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overrides.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOverride = `-- name: CreateOverride :one
INSERT INTO overrides (
    id,
    schedule_id,
    rotation_id,
    organization_id,
    user_id,
    replaced_user_id,
    starts_at,
    ends_at,
    created_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, schedule_id, rotation_id, organization_id, user_id, replaced_user_id, starts_at, ends_at, created_by_user_id, approved_by_user_id, deleted_at, created_at, updated_at
`

type CreateOverrideParams struct {
	ID              uuid.UUID          `json:"id"`
	ScheduleID      uuid.UUID          `json:"schedule_id"`
	RotationID      uuid.UUID          `json:"rotation_id"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	UserID          uuid.UUID          `json:"user_id"`
	ReplacedUserID  pgtype.UUID        `json:"replaced_user_id"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
	CreatedByUserID uuid.UUID          `json:"created_by_user_id"`
}

func (q *Queries) CreateOverride(ctx context.Context, arg CreateOverrideParams) (Override, error) {
	row := q.db.QueryRow(ctx, createOverride,
		arg.ID,
		arg.ScheduleID,
		arg.RotationID,
		arg.OrganizationID,
		arg.UserID,
		arg.ReplacedUserID,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedByUserID,
	)
	var i Override
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.RotationID,
		&i.OrganizationID,
		&i.UserID,
		&i.ReplacedUserID,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOverrideByID = `-- name: GetOverrideByID :one
SELECT id, schedule_id, rotation_id, organization_id, user_id, replaced_user_id, starts_at, ends_at, created_by_user_id, approved_by_user_id, deleted_at, created_at, updated_at
FROM overrides
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
LIMIT 1
`

type GetOverrideByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetOverrideByID(ctx context.Context, arg GetOverrideByIDParams) (Override, error) {
	row := q.db.QueryRow(ctx, getOverrideByID, arg.ID, arg.OrganizationID)
	var i Override
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.RotationID,
		&i.OrganizationID,
		&i.UserID,
		&i.ReplacedUserID,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveOverridesByScheduleAt = `-- name: ListActiveOverridesByScheduleAt :many
SELECT id, schedule_id, rotation_id, organization_id, user_id, replaced_user_id, starts_at, ends_at, created_by_user_id, approved_by_user_id, deleted_at, created_at, updated_at
FROM overrides
WHERE schedule_id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
  AND starts_at <= $3
  AND ends_at > $3
ORDER BY rotation_id, created_at DESC
`

type ListActiveOverridesByScheduleAtParams struct {
	ScheduleID     uuid.UUID          `json:"schedule_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
}

func (q *Queries) ListActiveOverridesByScheduleAt(ctx context.Context, arg ListActiveOverridesByScheduleAtParams) ([]Override, error) {
	rows, err := q.db.Query(ctx, listActiveOverridesByScheduleAt, arg.ScheduleID, arg.OrganizationID, arg.StartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Override{}
	for rows.Next() {
		var i Override
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.RotationID,
			&i.OrganizationID,
			&i.UserID,
			&i.ReplacedUserID,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedByUserID,
			&i.ApprovedByUserID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveOverridesByScheduleID = `-- name: ListActiveOverridesByScheduleID :many
SELECT id, schedule_id, rotation_id, organization_id, user_id, replaced_user_id, starts_at, ends_at, created_by_user_id, approved_by_user_id, deleted_at, created_at, updated_at
FROM overrides
WHERE schedule_id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
ORDER BY starts_at, created_at
`

type ListActiveOverridesByScheduleIDParams struct {
	ScheduleID     uuid.UUID `json:"schedule_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) ListActiveOverridesByScheduleID(ctx context.Context, arg ListActiveOverridesByScheduleIDParams) ([]Override, error) {
	rows, err := q.db.Query(ctx, listActiveOverridesByScheduleID, arg.ScheduleID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Override{}
	for rows.Next() {
		var i Override
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.RotationID,
			&i.OrganizationID,
			&i.UserID,
			&i.ReplacedUserID,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedByUserID,
			&i.ApprovedByUserID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOverride = `-- name: SoftDeleteOverride :one
UPDATE overrides
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
RETURNING id, schedule_id, rotation_id, organization_id, user_id, replaced_user_id, starts_at, ends_at, created_by_user_id, approved_by_user_id, deleted_at, created_at, updated_at
`

type SoftDeleteOverrideParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) SoftDeleteOverride(ctx context.Context, arg SoftDeleteOverrideParams) (Override, error) {
	row := q.db.QueryRow(ctx, softDeleteOverride, arg.ID, arg.OrganizationID)
	var i Override
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.RotationID,
		&i.OrganizationID,
		&i.UserID,
		&i.ReplacedUserID,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
