// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) (Alert, error)
	BootstrapOrganizationWithAdmin(ctx context.Context, arg BootstrapOrganizationWithAdminParams) (BootstrapOrganizationWithAdminRow, error)
	CloseAlert(ctx context.Context, arg CloseAlertParams) (Alert, error)
	CoreSchemaReady(ctx context.Context) (bool, error)
	CountNotificationAttemptsByAlertID(ctx context.Context, arg CountNotificationAttemptsByAlertIDParams) (int64, error)
	CountOrganizations(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error)
	CreateEscalationPolicy(ctx context.Context, arg CreateEscalationPolicyParams) (EscalationPolicy, error)
	CreateEscalationStep(ctx context.Context, arg CreateEscalationStepParams) (EscalationStep, error)
	CreateEscalationStepTarget(ctx context.Context, arg CreateEscalationStepTargetParams) (EscalationStepTarget, error)
	CreateHeartbeatMonitor(ctx context.Context, arg CreateHeartbeatMonitorParams) (HeartbeatMonitor, error)
	CreateNotificationAttempt(ctx context.Context, arg CreateNotificationAttemptParams) (NotificationAttempt, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateOverride(ctx context.Context, arg CreateOverrideParams) (Override, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreateRotation(ctx context.Context, arg CreateRotationParams) (Rotation, error)
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateTeamMembership(ctx context.Context, arg CreateTeamMembershipParams) (TeamMembership, error)
	CreateTriggeredAlert(ctx context.Context, arg CreateTriggeredAlertParams) (Alert, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteEscalationPolicy(ctx context.Context, arg DeleteEscalationPolicyParams) error
	DeleteEscalationStepsByPolicyID(ctx context.Context, arg DeleteEscalationStepsByPolicyIDParams) error
	DeleteHeartbeatMonitor(ctx context.Context, arg DeleteHeartbeatMonitorParams) error
	DeleteRotation(ctx context.Context, arg DeleteRotationParams) error
	DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) error
	DeleteSession(ctx context.Context, arg DeleteSessionParams) error
	GetActiveSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetAlertByID(ctx context.Context, arg GetAlertByIDParams) (Alert, error)
	GetEscalationPolicyByID(ctx context.Context, arg GetEscalationPolicyByIDParams) (EscalationPolicy, error)
	GetEscalationStepByPolicyAndOrder(ctx context.Context, arg GetEscalationStepByPolicyAndOrderParams) (EscalationStep, error)
	GetFirstOrganization(ctx context.Context) (Organization, error)
	GetHeartbeatMonitorByID(ctx context.Context, arg GetHeartbeatMonitorByIDParams) (HeartbeatMonitor, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationSlackSettings(ctx context.Context, organizationID uuid.UUID) (OrganizationSlackSetting, error)
	GetOverrideByID(ctx context.Context, arg GetOverrideByIDParams) (Override, error)
	GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetRotationByID(ctx context.Context, arg GetRotationByIDParams) (Rotation, error)
	GetScheduleByID(ctx context.Context, arg GetScheduleByIDParams) (Schedule, error)
	GetServiceByID(ctx context.Context, arg GetServiceByIDParams) (Service, error)
	GetSessionByID(ctx context.Context, arg GetSessionByIDParams) (Session, error)
	GetTeamByID(ctx context.Context, arg GetTeamByIDParams) (Team, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByEmailForAuth(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	GetUserContactMethodByChannel(ctx context.Context, arg GetUserContactMethodByChannelParams) (UserContactMethod, error)
	HasTeamMembership(ctx context.Context, arg HasTeamMembershipParams) (bool, error)
	InvalidateUnusedPasswordResetTokensForUser(ctx context.Context, userID uuid.UUID) error
	ListActiveOverridesByScheduleAt(ctx context.Context, arg ListActiveOverridesByScheduleAtParams) ([]Override, error)
	ListActiveOverridesByScheduleID(ctx context.Context, arg ListActiveOverridesByScheduleIDParams) ([]Override, error)
	ListAuditEventsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]AuditEvent, error)
	ListEscalationPoliciesByServiceID(ctx context.Context, arg ListEscalationPoliciesByServiceIDParams) ([]EscalationPolicy, error)
	ListEscalationStepTargetsByStepID(ctx context.Context, arg ListEscalationStepTargetsByStepIDParams) ([]EscalationStepTarget, error)
	ListEscalationStepsByPolicyID(ctx context.Context, arg ListEscalationStepsByPolicyIDParams) ([]EscalationStep, error)
	ListHeartbeatMonitorsByServiceID(ctx context.Context, arg ListHeartbeatMonitorsByServiceIDParams) ([]HeartbeatMonitor, error)
	ListNotificationAttemptsByAlertID(ctx context.Context, arg ListNotificationAttemptsByAlertIDParams) ([]NotificationAttempt, error)
	ListRotationsByScheduleID(ctx context.Context, arg ListRotationsByScheduleIDParams) ([]Rotation, error)
	ListSchedulesByTeamID(ctx context.Context, arg ListSchedulesByTeamIDParams) ([]Schedule, error)
	MarkPasswordResetTokenUsed(ctx context.Context, id uuid.UUID) error
	PingDatabase(ctx context.Context) (int32, error)
	ReEscalateAlert(ctx context.Context, arg ReEscalateAlertParams) (Alert, error)
	RecordHeartbeatPing(ctx context.Context, tokenHash string) (HeartbeatMonitor, error)
	RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	SessionsSchemaReady(ctx context.Context) (bool, error)
	SoftDeleteOverride(ctx context.Context, arg SoftDeleteOverrideParams) (Override, error)
	UpdateAlertEscalationState(ctx context.Context, arg UpdateAlertEscalationStateParams) (Alert, error)
	UpdateEscalationPolicy(ctx context.Context, arg UpdateEscalationPolicyParams) (EscalationPolicy, error)
	UpdateHeartbeatMonitor(ctx context.Context, arg UpdateHeartbeatMonitorParams) (HeartbeatMonitor, error)
	UpdateRotation(ctx context.Context, arg UpdateRotationParams) (Rotation, error)
	UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error)
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error
	UpsertOrganizationSlackSettings(ctx context.Context, arg UpsertOrganizationSlackSettingsParams) (OrganizationSlackSetting, error)
	UpsertUserContactMethod(ctx context.Context, arg UpsertUserContactMethodParams) (UserContactMethod, error)
}

var _ Querier = (*Queries)(nil)
