// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (
    id,
    organization_id,
    team_id,
    name,
    timezone
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, organization_id, team_id, name, timezone, created_at, updated_at
`

type CreateScheduleParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	TeamID         uuid.UUID `json:"team_id"`
	Name           string    `json:"name"`
	Timezone       string    `json:"timezone"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.ID,
		arg.OrganizationID,
		arg.TeamID,
		arg.Name,
		arg.Timezone,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules
WHERE id = $1
  AND organization_id = $2
`

type DeleteScheduleParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) error {
	_, err := q.db.Exec(ctx, deleteSchedule, arg.ID, arg.OrganizationID)
	return err
}

const getScheduleByID = `-- name: GetScheduleByID :one
SELECT id, organization_id, team_id, name, timezone, created_at, updated_at
FROM schedules
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetScheduleByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetScheduleByID(ctx context.Context, arg GetScheduleByIDParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, getScheduleByID, arg.ID, arg.OrganizationID)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchedulesByTeamID = `-- name: ListSchedulesByTeamID :many
SELECT id, organization_id, team_id, name, timezone, created_at, updated_at
FROM schedules
WHERE team_id = $1
  AND organization_id = $2
ORDER BY created_at
`

type ListSchedulesByTeamIDParams struct {
	TeamID         uuid.UUID `json:"team_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) ListSchedulesByTeamID(ctx context.Context, arg ListSchedulesByTeamIDParams) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesByTeamID, arg.TeamID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TeamID,
			&i.Name,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesForUserTeams = `-- name: ListSchedulesForUserTeams :many
SELECT
    s.id, s.organization_id, s.team_id, s.name, s.timezone, s.created_at, s.updated_at,
    t.name AS team_name
FROM schedules s
INNER JOIN teams t
  ON t.id = s.team_id
 AND t.organization_id = s.organization_id
INNER JOIN team_memberships tm
  ON tm.team_id = s.team_id
 AND tm.user_id = $1
 AND tm.organization_id = s.organization_id
WHERE s.organization_id = $2
ORDER BY t.name, s.name
`

type ListSchedulesForUserTeamsParams struct {
	UserID         uuid.UUID `json:"user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type ListSchedulesForUserTeamsRow struct {
	Schedule Schedule `json:"schedule"`
	TeamName string   `json:"team_name"`
}

func (q *Queries) ListSchedulesForUserTeams(ctx context.Context, arg ListSchedulesForUserTeamsParams) ([]ListSchedulesForUserTeamsRow, error) {
	rows, err := q.db.Query(ctx, listSchedulesForUserTeams, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchedulesForUserTeamsRow{}
	for rows.Next() {
		var i ListSchedulesForUserTeamsRow
		if err := rows.Scan(
			&i.Schedule.ID,
			&i.Schedule.OrganizationID,
			&i.Schedule.TeamID,
			&i.Schedule.Name,
			&i.Schedule.Timezone,
			&i.Schedule.CreatedAt,
			&i.Schedule.UpdatedAt,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE schedules
SET name = $3,
    timezone = $4,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
RETURNING id, organization_id, team_id, name, timezone, created_at, updated_at
`

type UpdateScheduleParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	Timezone       string    `json:"timezone"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, updateSchedule,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Timezone,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
