// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scim_groups.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createScimGroup = `-- name: CreateScimGroup :one
INSERT INTO scim_groups (
    id,
    organization_id,
    external_id,
    display_name,
    team_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, organization_id, external_id, display_name, team_id, created_at, updated_at
`

type CreateScimGroupParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	ExternalID     string    `json:"external_id"`
	DisplayName    string    `json:"display_name"`
	TeamID         uuid.UUID `json:"team_id"`
}

func (q *Queries) CreateScimGroup(ctx context.Context, arg CreateScimGroupParams) (ScimGroup, error) {
	row := q.db.QueryRow(ctx, createScimGroup,
		arg.ID,
		arg.OrganizationID,
		arg.ExternalID,
		arg.DisplayName,
		arg.TeamID,
	)
	var i ScimGroup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ExternalID,
		&i.DisplayName,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScimGroup = `-- name: DeleteScimGroup :exec
DELETE FROM scim_groups
WHERE id = $1
  AND organization_id = $2
`

type DeleteScimGroupParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteScimGroup(ctx context.Context, arg DeleteScimGroupParams) error {
	_, err := q.db.Exec(ctx, deleteScimGroup, arg.ID, arg.OrganizationID)
	return err
}

const getScimGroupByExternalID = `-- name: GetScimGroupByExternalID :one
SELECT id, organization_id, external_id, display_name, team_id, created_at, updated_at
FROM scim_groups
WHERE organization_id = $1
  AND external_id = $2
LIMIT 1
`

type GetScimGroupByExternalIDParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ExternalID     string    `json:"external_id"`
}

func (q *Queries) GetScimGroupByExternalID(ctx context.Context, arg GetScimGroupByExternalIDParams) (ScimGroup, error) {
	row := q.db.QueryRow(ctx, getScimGroupByExternalID, arg.OrganizationID, arg.ExternalID)
	var i ScimGroup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ExternalID,
		&i.DisplayName,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScimGroupByID = `-- name: GetScimGroupByID :one
SELECT id, organization_id, external_id, display_name, team_id, created_at, updated_at
FROM scim_groups
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetScimGroupByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetScimGroupByID(ctx context.Context, arg GetScimGroupByIDParams) (ScimGroup, error) {
	row := q.db.QueryRow(ctx, getScimGroupByID, arg.ID, arg.OrganizationID)
	var i ScimGroup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ExternalID,
		&i.DisplayName,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScimGroupsByOrganizationID = `-- name: ListScimGroupsByOrganizationID :many
SELECT id, organization_id, external_id, display_name, team_id, created_at, updated_at
FROM scim_groups
WHERE organization_id = $1
ORDER BY display_name ASC
`

func (q *Queries) ListScimGroupsByOrganizationID(ctx context.Context, organizationID uuid.UUID) ([]ScimGroup, error) {
	rows, err := q.db.Query(ctx, listScimGroupsByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScimGroup{}
	for rows.Next() {
		var i ScimGroup
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ExternalID,
			&i.DisplayName,
			&i.TeamID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScimGroupDisplayName = `-- name: UpdateScimGroupDisplayName :one
UPDATE scim_groups
SET display_name = $3,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
RETURNING id, organization_id, external_id, display_name, team_id, created_at, updated_at
`

type UpdateScimGroupDisplayNameParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	DisplayName    string    `json:"display_name"`
}

func (q *Queries) UpdateScimGroupDisplayName(ctx context.Context, arg UpdateScimGroupDisplayNameParams) (ScimGroup, error) {
	row := q.db.QueryRow(ctx, updateScimGroupDisplayName, arg.ID, arg.OrganizationID, arg.DisplayName)
	var i ScimGroup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ExternalID,
		&i.DisplayName,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
