// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (
    id,
    organization_id,
    team_id,
    name
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, organization_id, team_id, name, dedup_window_seconds, auto_promote_enabled, auto_promote_alert_threshold, auto_promote_window_seconds, auto_promote_suppress_escalation_priorities, deleted_at, created_at, updated_at
`

type CreateServiceParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	TeamID         uuid.UUID `json:"team_id"`
	Name           string    `json:"name"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.ID,
		arg.OrganizationID,
		arg.TeamID,
		arg.Name,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.DedupWindowSeconds,
		&i.AutoPromoteEnabled,
		&i.AutoPromoteAlertThreshold,
		&i.AutoPromoteWindowSeconds,
		&i.AutoPromoteSuppressEscalationPriorities,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, organization_id, team_id, name, dedup_window_seconds, auto_promote_enabled, auto_promote_alert_threshold, auto_promote_window_seconds, auto_promote_suppress_escalation_priorities, deleted_at, created_at, updated_at
FROM services
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
LIMIT 1
`

type GetServiceByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetServiceByID(ctx context.Context, arg GetServiceByIDParams) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, arg.ID, arg.OrganizationID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.DedupWindowSeconds,
		&i.AutoPromoteEnabled,
		&i.AutoPromoteAlertThreshold,
		&i.AutoPromoteWindowSeconds,
		&i.AutoPromoteSuppressEscalationPriorities,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServicesByOrganizationID = `-- name: ListServicesByOrganizationID :many
SELECT id, organization_id, team_id, name, dedup_window_seconds, auto_promote_enabled, auto_promote_alert_threshold, auto_promote_window_seconds, auto_promote_suppress_escalation_priorities, deleted_at, created_at, updated_at
FROM services
WHERE organization_id = $1
  AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListServicesByOrganizationID(ctx context.Context, organizationID uuid.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TeamID,
			&i.Name,
			&i.DedupWindowSeconds,
			&i.AutoPromoteEnabled,
			&i.AutoPromoteAlertThreshold,
			&i.AutoPromoteWindowSeconds,
			&i.AutoPromoteSuppressEscalationPriorities,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteService = `-- name: SoftDeleteService :one
UPDATE services
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
RETURNING id, organization_id, team_id, name, dedup_window_seconds, auto_promote_enabled, auto_promote_alert_threshold, auto_promote_window_seconds, auto_promote_suppress_escalation_priorities, deleted_at, created_at, updated_at
`

type SoftDeleteServiceParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) SoftDeleteService(ctx context.Context, arg SoftDeleteServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, softDeleteService, arg.ID, arg.OrganizationID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.DedupWindowSeconds,
		&i.AutoPromoteEnabled,
		&i.AutoPromoteAlertThreshold,
		&i.AutoPromoteWindowSeconds,
		&i.AutoPromoteSuppressEscalationPriorities,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name = COALESCE($3::text, name),
    team_id = COALESCE($4::uuid, team_id),
    auto_promote_enabled = COALESCE($5::boolean, auto_promote_enabled),
    auto_promote_alert_threshold = COALESCE($6::integer, auto_promote_alert_threshold),
    auto_promote_window_seconds = COALESCE($7::integer, auto_promote_window_seconds),
    auto_promote_suppress_escalation_priorities = COALESCE($8::text[], auto_promote_suppress_escalation_priorities),
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
RETURNING id, organization_id, team_id, name, dedup_window_seconds, auto_promote_enabled, auto_promote_alert_threshold, auto_promote_window_seconds, auto_promote_suppress_escalation_priorities, deleted_at, created_at, updated_at
`

type UpdateServiceParams struct {
	ID                                      uuid.UUID   `json:"id"`
	OrganizationID                          uuid.UUID   `json:"organization_id"`
	Name                                    pgtype.Text `json:"name"`
	TeamID                                  pgtype.UUID `json:"team_id"`
	AutoPromoteEnabled                      pgtype.Bool `json:"auto_promote_enabled"`
	AutoPromoteAlertThreshold               pgtype.Int4 `json:"auto_promote_alert_threshold"`
	AutoPromoteWindowSeconds                pgtype.Int4 `json:"auto_promote_window_seconds"`
	AutoPromoteSuppressEscalationPriorities []string    `json:"auto_promote_suppress_escalation_priorities"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.TeamID,
		arg.AutoPromoteEnabled,
		arg.AutoPromoteAlertThreshold,
		arg.AutoPromoteWindowSeconds,
		arg.AutoPromoteSuppressEscalationPriorities,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.DedupWindowSeconds,
		&i.AutoPromoteEnabled,
		&i.AutoPromoteAlertThreshold,
		&i.AutoPromoteWindowSeconds,
		&i.AutoPromoteSuppressEscalationPriorities,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
