// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status_pages.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStatusPage = `-- name: CreateStatusPage :one
INSERT INTO status_pages (
    id,
    organization_id,
    slug,
    title,
    enabled,
    frame_ancestors_csp
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, organization_id, slug, title, enabled, frame_ancestors_csp, created_at, updated_at
`

type CreateStatusPageParams struct {
	ID                uuid.UUID   `json:"id"`
	OrganizationID    uuid.UUID   `json:"organization_id"`
	Slug              string      `json:"slug"`
	Title             string      `json:"title"`
	Enabled           bool        `json:"enabled"`
	FrameAncestorsCsp pgtype.Text `json:"frame_ancestors_csp"`
}

func (q *Queries) CreateStatusPage(ctx context.Context, arg CreateStatusPageParams) (StatusPage, error) {
	row := q.db.QueryRow(ctx, createStatusPage,
		arg.ID,
		arg.OrganizationID,
		arg.Slug,
		arg.Title,
		arg.Enabled,
		arg.FrameAncestorsCsp,
	)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Title,
		&i.Enabled,
		&i.FrameAncestorsCsp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStatusPageComponent = `-- name: CreateStatusPageComponent :one
INSERT INTO status_page_components (
    id,
    status_page_id,
    organization_id,
    name,
    description,
    status,
    position,
    service_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, status_page_id, organization_id, name, description, status, position, service_id, created_at, updated_at
`

type CreateStatusPageComponentParams struct {
	ID             uuid.UUID   `json:"id"`
	StatusPageID   uuid.UUID   `json:"status_page_id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	Status         string      `json:"status"`
	Position       int32       `json:"position"`
	ServiceID      pgtype.UUID `json:"service_id"`
}

func (q *Queries) CreateStatusPageComponent(ctx context.Context, arg CreateStatusPageComponentParams) (StatusPageComponent, error) {
	row := q.db.QueryRow(ctx, createStatusPageComponent,
		arg.ID,
		arg.StatusPageID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Position,
		arg.ServiceID,
	)
	var i StatusPageComponent
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Position,
		&i.ServiceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStatusPageIncident = `-- name: CreateStatusPageIncident :one
INSERT INTO status_page_incidents (
    id,
    status_page_id,
    organization_id,
    incident_id,
    title,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, status_page_id, organization_id, incident_id, title, status, resolved_at, created_at, updated_at
`

type CreateStatusPageIncidentParams struct {
	ID             uuid.UUID   `json:"id"`
	StatusPageID   uuid.UUID   `json:"status_page_id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	IncidentID     pgtype.UUID `json:"incident_id"`
	Title          string      `json:"title"`
	Status         string      `json:"status"`
}

func (q *Queries) CreateStatusPageIncident(ctx context.Context, arg CreateStatusPageIncidentParams) (StatusPageIncident, error) {
	row := q.db.QueryRow(ctx, createStatusPageIncident,
		arg.ID,
		arg.StatusPageID,
		arg.OrganizationID,
		arg.IncidentID,
		arg.Title,
		arg.Status,
	)
	var i StatusPageIncident
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.OrganizationID,
		&i.IncidentID,
		&i.Title,
		&i.Status,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStatusPageIncidentUpdate = `-- name: CreateStatusPageIncidentUpdate :one
INSERT INTO status_page_incident_updates (
    id,
    status_page_incident_id,
    organization_id,
    body,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, status_page_incident_id, organization_id, body, status, created_at
`

type CreateStatusPageIncidentUpdateParams struct {
	ID                   uuid.UUID `json:"id"`
	StatusPageIncidentID uuid.UUID `json:"status_page_incident_id"`
	OrganizationID       uuid.UUID `json:"organization_id"`
	Body                 string    `json:"body"`
	Status               string    `json:"status"`
}

func (q *Queries) CreateStatusPageIncidentUpdate(ctx context.Context, arg CreateStatusPageIncidentUpdateParams) (StatusPageIncidentUpdate, error) {
	row := q.db.QueryRow(ctx, createStatusPageIncidentUpdate,
		arg.ID,
		arg.StatusPageIncidentID,
		arg.OrganizationID,
		arg.Body,
		arg.Status,
	)
	var i StatusPageIncidentUpdate
	err := row.Scan(
		&i.ID,
		&i.StatusPageIncidentID,
		&i.OrganizationID,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createStatusPageSubscription = `-- name: CreateStatusPageSubscription :one
INSERT INTO status_page_subscriptions (
    id,
    status_page_id,
    organization_id,
    email
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (status_page_id, email) DO UPDATE
SET unsubscribed_at = NULL
RETURNING id, status_page_id, organization_id, email, unsubscribed_at, created_at
`

type CreateStatusPageSubscriptionParams struct {
	ID             uuid.UUID `json:"id"`
	StatusPageID   uuid.UUID `json:"status_page_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Email          string    `json:"email"`
}

func (q *Queries) CreateStatusPageSubscription(ctx context.Context, arg CreateStatusPageSubscriptionParams) (StatusPageSubscription, error) {
	row := q.db.QueryRow(ctx, createStatusPageSubscription,
		arg.ID,
		arg.StatusPageID,
		arg.OrganizationID,
		arg.Email,
	)
	var i StatusPageSubscription
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.OrganizationID,
		&i.Email,
		&i.UnsubscribedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStatusPageComponent = `-- name: DeleteStatusPageComponent :exec
DELETE FROM status_page_components
WHERE id = $1
  AND organization_id = $2
`

type DeleteStatusPageComponentParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteStatusPageComponent(ctx context.Context, arg DeleteStatusPageComponentParams) error {
	_, err := q.db.Exec(ctx, deleteStatusPageComponent, arg.ID, arg.OrganizationID)
	return err
}

const getStatusPageByOrganizationID = `-- name: GetStatusPageByOrganizationID :one
SELECT id, organization_id, slug, title, enabled, frame_ancestors_csp, created_at, updated_at
FROM status_pages
WHERE organization_id = $1
LIMIT 1
`

func (q *Queries) GetStatusPageByOrganizationID(ctx context.Context, organizationID uuid.UUID) (StatusPage, error) {
	row := q.db.QueryRow(ctx, getStatusPageByOrganizationID, organizationID)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Title,
		&i.Enabled,
		&i.FrameAncestorsCsp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStatusPageBySlug = `-- name: GetStatusPageBySlug :one
SELECT id, organization_id, slug, title, enabled, frame_ancestors_csp, created_at, updated_at
FROM status_pages
WHERE slug = $1
  AND enabled = true
LIMIT 1
`

func (q *Queries) GetStatusPageBySlug(ctx context.Context, slug string) (StatusPage, error) {
	row := q.db.QueryRow(ctx, getStatusPageBySlug, slug)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Title,
		&i.Enabled,
		&i.FrameAncestorsCsp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStatusPageComponentByID = `-- name: GetStatusPageComponentByID :one
SELECT id, status_page_id, organization_id, name, description, status, position, service_id, created_at, updated_at
FROM status_page_components
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetStatusPageComponentByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetStatusPageComponentByID(ctx context.Context, arg GetStatusPageComponentByIDParams) (StatusPageComponent, error) {
	row := q.db.QueryRow(ctx, getStatusPageComponentByID, arg.ID, arg.OrganizationID)
	var i StatusPageComponent
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Position,
		&i.ServiceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStatusPageIncidentByID = `-- name: GetStatusPageIncidentByID :one
SELECT id, status_page_id, organization_id, incident_id, title, status, resolved_at, created_at, updated_at
FROM status_page_incidents
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetStatusPageIncidentByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetStatusPageIncidentByID(ctx context.Context, arg GetStatusPageIncidentByIDParams) (StatusPageIncident, error) {
	row := q.db.QueryRow(ctx, getStatusPageIncidentByID, arg.ID, arg.OrganizationID)
	var i StatusPageIncident
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.OrganizationID,
		&i.IncidentID,
		&i.Title,
		&i.Status,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertStatusPageIncidentComponent = `-- name: InsertStatusPageIncidentComponent :exec
INSERT INTO status_page_incident_components (
    status_page_incident_id,
    status_page_component_id,
    organization_id
) VALUES (
    $1,
    $2,
    $3
)
`

type InsertStatusPageIncidentComponentParams struct {
	StatusPageIncidentID  uuid.UUID `json:"status_page_incident_id"`
	StatusPageComponentID uuid.UUID `json:"status_page_component_id"`
	OrganizationID        uuid.UUID `json:"organization_id"`
}

func (q *Queries) InsertStatusPageIncidentComponent(ctx context.Context, arg InsertStatusPageIncidentComponentParams) error {
	_, err := q.db.Exec(ctx, insertStatusPageIncidentComponent, arg.StatusPageIncidentID, arg.StatusPageComponentID, arg.OrganizationID)
	return err
}

const listActiveStatusPageIncidents = `-- name: ListActiveStatusPageIncidents :many
SELECT id, status_page_id, organization_id, incident_id, title, status, resolved_at, created_at, updated_at
FROM status_page_incidents
WHERE status_page_id = $1
  AND organization_id = $2
  AND status <> 'resolved'
ORDER BY created_at DESC
`

type ListActiveStatusPageIncidentsParams struct {
	StatusPageID   uuid.UUID `json:"status_page_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) ListActiveStatusPageIncidents(ctx context.Context, arg ListActiveStatusPageIncidentsParams) ([]StatusPageIncident, error) {
	rows, err := q.db.Query(ctx, listActiveStatusPageIncidents, arg.StatusPageID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPageIncident{}
	for rows.Next() {
		var i StatusPageIncident
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.OrganizationID,
			&i.IncidentID,
			&i.Title,
			&i.Status,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicStatusPageComponents = `-- name: ListPublicStatusPageComponents :many
SELECT id, status_page_id, organization_id, name, description, status, position, created_at, updated_at
FROM status_page_components
WHERE status_page_id = $1
  AND organization_id = $2
ORDER BY position ASC, created_at ASC
`

type ListPublicStatusPageComponentsParams struct {
	StatusPageID   uuid.UUID `json:"status_page_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type ListPublicStatusPageComponentsRow struct {
	ID             uuid.UUID          `json:"id"`
	StatusPageID   uuid.UUID          `json:"status_page_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	Status         string             `json:"status"`
	Position       int32              `json:"position"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPublicStatusPageComponents(ctx context.Context, arg ListPublicStatusPageComponentsParams) ([]ListPublicStatusPageComponentsRow, error) {
	rows, err := q.db.Query(ctx, listPublicStatusPageComponents, arg.StatusPageID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicStatusPageComponentsRow{}
	for rows.Next() {
		var i ListPublicStatusPageComponentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicStatusPageIncidentUpdates = `-- name: ListPublicStatusPageIncidentUpdates :many
SELECT id, status_page_incident_id, organization_id, body, status, created_at
FROM status_page_incident_updates
WHERE status_page_incident_id = $1
  AND organization_id = $2
ORDER BY created_at ASC
`

type ListPublicStatusPageIncidentUpdatesParams struct {
	StatusPageIncidentID uuid.UUID `json:"status_page_incident_id"`
	OrganizationID       uuid.UUID `json:"organization_id"`
}

func (q *Queries) ListPublicStatusPageIncidentUpdates(ctx context.Context, arg ListPublicStatusPageIncidentUpdatesParams) ([]StatusPageIncidentUpdate, error) {
	rows, err := q.db.Query(ctx, listPublicStatusPageIncidentUpdates, arg.StatusPageIncidentID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPageIncidentUpdate{}
	for rows.Next() {
		var i StatusPageIncidentUpdate
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageIncidentID,
			&i.OrganizationID,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicStatusPageIncidents = `-- name: ListPublicStatusPageIncidents :many
SELECT id, status_page_id, organization_id, title, status, resolved_at, created_at, updated_at
FROM status_page_incidents
WHERE status_page_id = $1
  AND organization_id = $2
  AND status <> 'resolved'
ORDER BY created_at DESC
`

type ListPublicStatusPageIncidentsParams struct {
	StatusPageID   uuid.UUID `json:"status_page_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type ListPublicStatusPageIncidentsRow struct {
	ID             uuid.UUID          `json:"id"`
	StatusPageID   uuid.UUID          `json:"status_page_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPublicStatusPageIncidents(ctx context.Context, arg ListPublicStatusPageIncidentsParams) ([]ListPublicStatusPageIncidentsRow, error) {
	rows, err := q.db.Query(ctx, listPublicStatusPageIncidents, arg.StatusPageID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicStatusPageIncidentsRow{}
	for rows.Next() {
		var i ListPublicStatusPageIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.OrganizationID,
			&i.Title,
			&i.Status,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicStatusPageResolvedIncidents = `-- name: ListPublicStatusPageResolvedIncidents :many
SELECT id, status_page_id, organization_id, title, status, resolved_at, created_at, updated_at
FROM status_page_incidents
WHERE status_page_id = $1
  AND organization_id = $2
  AND status = 'resolved'
  AND resolved_at >= now() - ($3::integer * interval '1 day')
ORDER BY resolved_at DESC
`

type ListPublicStatusPageResolvedIncidentsParams struct {
	StatusPageID       uuid.UUID `json:"status_page_id"`
	OrganizationID     uuid.UUID `json:"organization_id"`
	ResolvedWindowDays int32     `json:"resolved_window_days"`
}

type ListPublicStatusPageResolvedIncidentsRow struct {
	ID             uuid.UUID          `json:"id"`
	StatusPageID   uuid.UUID          `json:"status_page_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPublicStatusPageResolvedIncidents(ctx context.Context, arg ListPublicStatusPageResolvedIncidentsParams) ([]ListPublicStatusPageResolvedIncidentsRow, error) {
	rows, err := q.db.Query(ctx, listPublicStatusPageResolvedIncidents, arg.StatusPageID, arg.OrganizationID, arg.ResolvedWindowDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicStatusPageResolvedIncidentsRow{}
	for rows.Next() {
		var i ListPublicStatusPageResolvedIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.OrganizationID,
			&i.Title,
			&i.Status,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusPageComponents = `-- name: ListStatusPageComponents :many
SELECT id, status_page_id, organization_id, name, description, status, position, service_id, created_at, updated_at
FROM status_page_components
WHERE status_page_id = $1
  AND organization_id = $2
ORDER BY position ASC, created_at ASC
`

type ListStatusPageComponentsParams struct {
	StatusPageID   uuid.UUID `json:"status_page_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) ListStatusPageComponents(ctx context.Context, arg ListStatusPageComponentsParams) ([]StatusPageComponent, error) {
	rows, err := q.db.Query(ctx, listStatusPageComponents, arg.StatusPageID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPageComponent{}
	for rows.Next() {
		var i StatusPageComponent
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Position,
			&i.ServiceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusPageIncidentComponentIDs = `-- name: ListStatusPageIncidentComponentIDs :many
SELECT status_page_component_id
FROM status_page_incident_components
WHERE status_page_incident_id = $1
  AND organization_id = $2
ORDER BY created_at ASC
`

type ListStatusPageIncidentComponentIDsParams struct {
	StatusPageIncidentID uuid.UUID `json:"status_page_incident_id"`
	OrganizationID       uuid.UUID `json:"organization_id"`
}

func (q *Queries) ListStatusPageIncidentComponentIDs(ctx context.Context, arg ListStatusPageIncidentComponentIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listStatusPageIncidentComponentIDs, arg.StatusPageIncidentID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var status_page_component_id uuid.UUID
		if err := rows.Scan(&status_page_component_id); err != nil {
			return nil, err
		}
		items = append(items, status_page_component_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusPageIncidentUpdates = `-- name: ListStatusPageIncidentUpdates :many
SELECT id, status_page_incident_id, organization_id, body, status, created_at
FROM status_page_incident_updates
WHERE status_page_incident_id = $1
  AND organization_id = $2
ORDER BY created_at ASC
`

type ListStatusPageIncidentUpdatesParams struct {
	StatusPageIncidentID uuid.UUID `json:"status_page_incident_id"`
	OrganizationID       uuid.UUID `json:"organization_id"`
}

func (q *Queries) ListStatusPageIncidentUpdates(ctx context.Context, arg ListStatusPageIncidentUpdatesParams) ([]StatusPageIncidentUpdate, error) {
	rows, err := q.db.Query(ctx, listStatusPageIncidentUpdates, arg.StatusPageIncidentID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPageIncidentUpdate{}
	for rows.Next() {
		var i StatusPageIncidentUpdate
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageIncidentID,
			&i.OrganizationID,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusPageSubscriptions = `-- name: ListStatusPageSubscriptions :many
SELECT id, status_page_id, organization_id, email, unsubscribed_at, created_at
FROM status_page_subscriptions
WHERE status_page_id = $1
  AND organization_id = $2
  AND unsubscribed_at IS NULL
ORDER BY created_at ASC
`

type ListStatusPageSubscriptionsParams struct {
	StatusPageID   uuid.UUID `json:"status_page_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) ListStatusPageSubscriptions(ctx context.Context, arg ListStatusPageSubscriptionsParams) ([]StatusPageSubscription, error) {
	rows, err := q.db.Query(ctx, listStatusPageSubscriptions, arg.StatusPageID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPageSubscription{}
	for rows.Next() {
		var i StatusPageSubscription
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.OrganizationID,
			&i.Email,
			&i.UnsubscribedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceStatusPageIncidentComponents = `-- name: ReplaceStatusPageIncidentComponents :exec
DELETE FROM status_page_incident_components
WHERE status_page_incident_id = $1
  AND organization_id = $2
`

type ReplaceStatusPageIncidentComponentsParams struct {
	StatusPageIncidentID uuid.UUID `json:"status_page_incident_id"`
	OrganizationID       uuid.UUID `json:"organization_id"`
}

func (q *Queries) ReplaceStatusPageIncidentComponents(ctx context.Context, arg ReplaceStatusPageIncidentComponentsParams) error {
	_, err := q.db.Exec(ctx, replaceStatusPageIncidentComponents, arg.StatusPageIncidentID, arg.OrganizationID)
	return err
}

const unsubscribeStatusPageSubscription = `-- name: UnsubscribeStatusPageSubscription :one
UPDATE status_page_subscriptions
SET unsubscribed_at = COALESCE(unsubscribed_at, now())
WHERE id = $1
  AND organization_id = $2
RETURNING id, status_page_id, organization_id, email, unsubscribed_at, created_at
`

type UnsubscribeStatusPageSubscriptionParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) UnsubscribeStatusPageSubscription(ctx context.Context, arg UnsubscribeStatusPageSubscriptionParams) (StatusPageSubscription, error) {
	row := q.db.QueryRow(ctx, unsubscribeStatusPageSubscription, arg.ID, arg.OrganizationID)
	var i StatusPageSubscription
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.OrganizationID,
		&i.Email,
		&i.UnsubscribedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateStatusPage = `-- name: UpdateStatusPage :one
UPDATE status_pages
SET slug = $3,
    title = $4,
    enabled = $5,
    frame_ancestors_csp = $6,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
RETURNING id, organization_id, slug, title, enabled, frame_ancestors_csp, created_at, updated_at
`

type UpdateStatusPageParams struct {
	ID                uuid.UUID   `json:"id"`
	OrganizationID    uuid.UUID   `json:"organization_id"`
	Slug              string      `json:"slug"`
	Title             string      `json:"title"`
	Enabled           bool        `json:"enabled"`
	FrameAncestorsCsp pgtype.Text `json:"frame_ancestors_csp"`
}

func (q *Queries) UpdateStatusPage(ctx context.Context, arg UpdateStatusPageParams) (StatusPage, error) {
	row := q.db.QueryRow(ctx, updateStatusPage,
		arg.ID,
		arg.OrganizationID,
		arg.Slug,
		arg.Title,
		arg.Enabled,
		arg.FrameAncestorsCsp,
	)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Title,
		&i.Enabled,
		&i.FrameAncestorsCsp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStatusPageComponent = `-- name: UpdateStatusPageComponent :one
UPDATE status_page_components
SET name = $3,
    description = $4,
    status = $5,
    position = $6,
    service_id = $7,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
RETURNING id, status_page_id, organization_id, name, description, status, position, service_id, created_at, updated_at
`

type UpdateStatusPageComponentParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	Status         string      `json:"status"`
	Position       int32       `json:"position"`
	ServiceID      pgtype.UUID `json:"service_id"`
}

func (q *Queries) UpdateStatusPageComponent(ctx context.Context, arg UpdateStatusPageComponentParams) (StatusPageComponent, error) {
	row := q.db.QueryRow(ctx, updateStatusPageComponent,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Position,
		arg.ServiceID,
	)
	var i StatusPageComponent
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Position,
		&i.ServiceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStatusPageIncidentStatus = `-- name: UpdateStatusPageIncidentStatus :one
UPDATE status_page_incidents
SET status = $3,
    resolved_at = CASE
        WHEN $3 = 'resolved' THEN now()
        ELSE NULL
    END,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
RETURNING id, status_page_id, organization_id, incident_id, title, status, resolved_at, created_at, updated_at
`

type UpdateStatusPageIncidentStatusParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Status         string    `json:"status"`
}

func (q *Queries) UpdateStatusPageIncidentStatus(ctx context.Context, arg UpdateStatusPageIncidentStatusParams) (StatusPageIncident, error) {
	row := q.db.QueryRow(ctx, updateStatusPageIncidentStatus, arg.ID, arg.OrganizationID, arg.Status)
	var i StatusPageIncident
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.OrganizationID,
		&i.IncidentID,
		&i.Title,
		&i.Status,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
