// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_memberships.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTeamMembership = `-- name: CreateTeamMembership :one
INSERT INTO team_memberships (
    id,
    team_id,
    user_id,
    organization_id
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, team_id, user_id, organization_id, created_at, updated_at
`

type CreateTeamMembershipParams struct {
	ID             uuid.UUID `json:"id"`
	TeamID         uuid.UUID `json:"team_id"`
	UserID         uuid.UUID `json:"user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) CreateTeamMembership(ctx context.Context, arg CreateTeamMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, createTeamMembership,
		arg.ID,
		arg.TeamID,
		arg.UserID,
		arg.OrganizationID,
	)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeamMembership = `-- name: DeleteTeamMembership :exec
DELETE FROM team_memberships
WHERE team_id = $1
  AND user_id = $2
  AND organization_id = $3
`

type DeleteTeamMembershipParams struct {
	TeamID         uuid.UUID `json:"team_id"`
	UserID         uuid.UUID `json:"user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteTeamMembership(ctx context.Context, arg DeleteTeamMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteTeamMembership, arg.TeamID, arg.UserID, arg.OrganizationID)
	return err
}

const getTeamMembership = `-- name: GetTeamMembership :one
SELECT id, team_id, user_id, organization_id, created_at, updated_at
FROM team_memberships
WHERE team_id = $1
  AND user_id = $2
  AND organization_id = $3
LIMIT 1
`

type GetTeamMembershipParams struct {
	TeamID         uuid.UUID `json:"team_id"`
	UserID         uuid.UUID `json:"user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetTeamMembership(ctx context.Context, arg GetTeamMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, getTeamMembership, arg.TeamID, arg.UserID, arg.OrganizationID)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasTeamMembership = `-- name: HasTeamMembership :one
SELECT EXISTS(
    SELECT 1
    FROM team_memberships
    WHERE team_id = $1
      AND user_id = $2
      AND organization_id = $3
) AS has_membership
`

type HasTeamMembershipParams struct {
	TeamID         uuid.UUID `json:"team_id"`
	UserID         uuid.UUID `json:"user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) HasTeamMembership(ctx context.Context, arg HasTeamMembershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasTeamMembership, arg.TeamID, arg.UserID, arg.OrganizationID)
	var has_membership bool
	err := row.Scan(&has_membership)
	return has_membership, err
}
