// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (
    id,
    organization_id,
    name
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, organization_id, name, created_at, updated_at
`

type CreateTeamParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.ID, arg.OrganizationID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, organization_id, name, created_at, updated_at
FROM teams
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetTeamByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetTeamByID(ctx context.Context, arg GetTeamByIDParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, arg.ID, arg.OrganizationID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT id, organization_id, name, created_at, updated_at
FROM teams
WHERE organization_id = $1
  AND name = $2
LIMIT 1
`

type GetTeamByNameParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
}

func (q *Queries) GetTeamByName(ctx context.Context, arg GetTeamByNameParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByName, arg.OrganizationID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamsByOrganizationID = `-- name: ListTeamsByOrganizationID :many
SELECT id, organization_id, name, created_at, updated_at
FROM teams
WHERE organization_id = $1
ORDER BY name ASC
`

func (q *Queries) ListTeamsByOrganizationID(ctx context.Context, organizationID uuid.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
