// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_notification_rules.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserNotificationRule = `-- name: DeleteUserNotificationRule :exec
DELETE FROM user_notification_rules
WHERE organization_id = $1
  AND user_id = $2
  AND priority = $3
`

type DeleteUserNotificationRuleParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Priority       string    `json:"priority"`
}

func (q *Queries) DeleteUserNotificationRule(ctx context.Context, arg DeleteUserNotificationRuleParams) error {
	_, err := q.db.Exec(ctx, deleteUserNotificationRule, arg.OrganizationID, arg.UserID, arg.Priority)
	return err
}

const getUserNotificationRuleByPriority = `-- name: GetUserNotificationRuleByPriority :one
SELECT id, organization_id, user_id, priority, steps, created_at, updated_at
FROM user_notification_rules
WHERE organization_id = $1
  AND user_id = $2
  AND priority = $3
LIMIT 1
`

type GetUserNotificationRuleByPriorityParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Priority       string    `json:"priority"`
}

func (q *Queries) GetUserNotificationRuleByPriority(ctx context.Context, arg GetUserNotificationRuleByPriorityParams) (UserNotificationRule, error) {
	row := q.db.QueryRow(ctx, getUserNotificationRuleByPriority, arg.OrganizationID, arg.UserID, arg.Priority)
	var i UserNotificationRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Priority,
		&i.Steps,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserNotificationRules = `-- name: ListUserNotificationRules :many
SELECT id, organization_id, user_id, priority, steps, created_at, updated_at
FROM user_notification_rules
WHERE organization_id = $1
  AND user_id = $2
ORDER BY priority ASC
`

type ListUserNotificationRulesParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) ListUserNotificationRules(ctx context.Context, arg ListUserNotificationRulesParams) ([]UserNotificationRule, error) {
	rows, err := q.db.Query(ctx, listUserNotificationRules, arg.OrganizationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserNotificationRule{}
	for rows.Next() {
		var i UserNotificationRule
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Priority,
			&i.Steps,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserNotificationRule = `-- name: UpsertUserNotificationRule :one
INSERT INTO user_notification_rules (
    id,
    organization_id,
    user_id,
    priority,
    steps
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (organization_id, user_id, priority) DO UPDATE
SET steps = EXCLUDED.steps,
    updated_at = now()
RETURNING id, organization_id, user_id, priority, steps, created_at, updated_at
`

type UpsertUserNotificationRuleParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Priority       string    `json:"priority"`
	Steps          []byte    `json:"steps"`
}

func (q *Queries) UpsertUserNotificationRule(ctx context.Context, arg UpsertUserNotificationRuleParams) (UserNotificationRule, error) {
	row := q.db.QueryRow(ctx, upsertUserNotificationRule,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.Priority,
		arg.Steps,
	)
	var i UserNotificationRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Priority,
		&i.Steps,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
