// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*)::bigint AS count
FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScimUser = `-- name: CreateScimUser :one
INSERT INTO users (
    id,
    organization_id,
    email,
    password_hash,
    role,
    scim_external_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, organization_id, email, password_hash, role, scim_external_id, deprovisioned_at, created_at, updated_at
`

type CreateScimUserParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	Email          string      `json:"email"`
	PasswordHash   pgtype.Text `json:"password_hash"`
	Role           string      `json:"role"`
	ScimExternalID pgtype.Text `json:"scim_external_id"`
}

func (q *Queries) CreateScimUser(ctx context.Context, arg CreateScimUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createScimUser,
		arg.ID,
		arg.OrganizationID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.ScimExternalID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ScimExternalID,
		&i.DeprovisionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    organization_id,
    email,
    password_hash,
    role
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, organization_id, email, password_hash, role, scim_external_id, deprovisioned_at, created_at, updated_at
`

type CreateUserParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	Email          string      `json:"email"`
	PasswordHash   pgtype.Text `json:"password_hash"`
	Role           string      `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.OrganizationID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ScimExternalID,
		&i.DeprovisionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deprovisionUser = `-- name: DeprovisionUser :one
UPDATE users
SET deprovisioned_at = now(),
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND deprovisioned_at IS NULL
RETURNING id, organization_id, email, password_hash, role, scim_external_id, deprovisioned_at, created_at, updated_at
`

type DeprovisionUserParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeprovisionUser(ctx context.Context, arg DeprovisionUserParams) (User, error) {
	row := q.db.QueryRow(ctx, deprovisionUser, arg.ID, arg.OrganizationID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ScimExternalID,
		&i.DeprovisionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFirstAdminUserByOrganization = `-- name: GetFirstAdminUserByOrganization :one
SELECT id, organization_id, email, password_hash, role, scim_external_id, deprovisioned_at, created_at, updated_at
FROM users
WHERE organization_id = $1
  AND role = 'admin'
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetFirstAdminUserByOrganization(ctx context.Context, organizationID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getFirstAdminUserByOrganization, organizationID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ScimExternalID,
		&i.DeprovisionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, organization_id, email, password_hash, role, scim_external_id, deprovisioned_at, created_at, updated_at
FROM users
WHERE organization_id = $1
  AND email = $2
LIMIT 1
`

type GetUserByEmailParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Email          string    `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.OrganizationID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ScimExternalID,
		&i.DeprovisionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailForAuth = `-- name: GetUserByEmailForAuth :one
SELECT id, organization_id, email, password_hash, role, scim_external_id, deprovisioned_at, created_at, updated_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmailForAuth(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailForAuth, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ScimExternalID,
		&i.DeprovisionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, organization_id, email, password_hash, role, scim_external_id, deprovisioned_at, created_at, updated_at
FROM users
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetUserByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.OrganizationID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ScimExternalID,
		&i.DeprovisionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIDIncludingDeprovisioned = `-- name: GetUserByIDIncludingDeprovisioned :one
SELECT id, organization_id, email, password_hash, role, scim_external_id, deprovisioned_at, created_at, updated_at
FROM users
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetUserByIDIncludingDeprovisionedParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetUserByIDIncludingDeprovisioned(ctx context.Context, arg GetUserByIDIncludingDeprovisionedParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDIncludingDeprovisioned, arg.ID, arg.OrganizationID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ScimExternalID,
		&i.DeprovisionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByScimExternalID = `-- name: GetUserByScimExternalID :one
SELECT id, organization_id, email, password_hash, role, scim_external_id, deprovisioned_at, created_at, updated_at
FROM users
WHERE organization_id = $1
  AND scim_external_id = $2
LIMIT 1
`

type GetUserByScimExternalIDParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	ScimExternalID pgtype.Text `json:"scim_external_id"`
}

func (q *Queries) GetUserByScimExternalID(ctx context.Context, arg GetUserByScimExternalIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByScimExternalID, arg.OrganizationID, arg.ScimExternalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ScimExternalID,
		&i.DeprovisionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScimUsersByOrganizationID = `-- name: ListScimUsersByOrganizationID :many
SELECT id, organization_id, email, password_hash, role, scim_external_id, deprovisioned_at, created_at, updated_at
FROM users
WHERE organization_id = $1
  AND scim_external_id IS NOT NULL
ORDER BY email ASC
`

func (q *Queries) ListScimUsersByOrganizationID(ctx context.Context, organizationID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listScimUsersByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.ScimExternalID,
			&i.DeprovisionedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reprovisionScimUser = `-- name: ReprovisionScimUser :one
UPDATE users
SET email = $3,
    scim_external_id = $4,
    deprovisioned_at = NULL,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
RETURNING id, organization_id, email, password_hash, role, scim_external_id, deprovisioned_at, created_at, updated_at
`

type ReprovisionScimUserParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	Email          string      `json:"email"`
	ScimExternalID pgtype.Text `json:"scim_external_id"`
}

func (q *Queries) ReprovisionScimUser(ctx context.Context, arg ReprovisionScimUserParams) (User, error) {
	row := q.db.QueryRow(ctx, reprovisionScimUser,
		arg.ID,
		arg.OrganizationID,
		arg.Email,
		arg.ScimExternalID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ScimExternalID,
		&i.DeprovisionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScimUser = `-- name: UpdateScimUser :one
UPDATE users
SET email = $3,
    scim_external_id = $4,
    deprovisioned_at = $5,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
RETURNING id, organization_id, email, password_hash, role, scim_external_id, deprovisioned_at, created_at, updated_at
`

type UpdateScimUserParams struct {
	ID              uuid.UUID          `json:"id"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	Email           string             `json:"email"`
	ScimExternalID  pgtype.Text        `json:"scim_external_id"`
	DeprovisionedAt pgtype.Timestamptz `json:"deprovisioned_at"`
}

func (q *Queries) UpdateScimUser(ctx context.Context, arg UpdateScimUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateScimUser,
		arg.ID,
		arg.OrganizationID,
		arg.Email,
		arg.ScimExternalID,
		arg.DeprovisionedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ScimExternalID,
		&i.DeprovisionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users
SET password_hash = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordHashParams struct {
	ID           uuid.UUID   `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}
