// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Alert struct {
	ID             string        `json:"id"`
	OrganizationID string        `json:"organizationId"`
	ServiceID      string        `json:"serviceId"`
	Status         AlertStatus   `json:"status"`
	DedupKey       string        `json:"dedupKey"`
	Summary        string        `json:"summary"`
	Description    *string       `json:"description,omitempty"`
	Priority       AlertPriority `json:"priority"`
	EventCount     int           `json:"eventCount"`
	AcknowledgedAt *time.Time    `json:"acknowledgedAt,omitempty"`
	AcknowledgedBy *User         `json:"acknowledgedBy,omitempty"`
	ClosedAt       *time.Time    `json:"closedAt,omitempty"`
	CreatedAt      time.Time     `json:"createdAt"`
	UpdatedAt      time.Time     `json:"updatedAt"`
}

type CreateEscalationPolicyInput struct {
	ServiceID string                 `json:"serviceId"`
	Name      string                 `json:"name"`
	Steps     []*EscalationStepInput `json:"steps"`
}

type CreateRotationInput struct {
	ScheduleID     string   `json:"scheduleId"`
	Name           string   `json:"name"`
	Layer          int      `json:"layer"`
	Rrule          string   `json:"rrule"`
	ParticipantIds []string `json:"participantIds"`
}

type CreateScheduleInput struct {
	TeamID   string `json:"teamId"`
	Name     string `json:"name"`
	Timezone string `json:"timezone"`
}

type EscalationPolicy struct {
	ID             string            `json:"id"`
	OrganizationID string            `json:"organizationId"`
	ServiceID      string            `json:"serviceId"`
	Name           string            `json:"name"`
	Steps          []*EscalationStep `json:"steps"`
	CreatedAt      time.Time         `json:"createdAt"`
	UpdatedAt      time.Time         `json:"updatedAt"`
}

type EscalationStep struct {
	ID                 string    `json:"id"`
	EscalationPolicyID string    `json:"escalationPolicyId"`
	OrganizationID     string    `json:"organizationId"`
	StepOrder          int       `json:"stepOrder"`
	DelayMinutes       int       `json:"delayMinutes"`
	RepeatLastStep     bool      `json:"repeatLastStep"`
	MaxRepeats         *int      `json:"maxRepeats,omitempty"`
	CreatedAt          time.Time `json:"createdAt"`
	UpdatedAt          time.Time `json:"updatedAt"`
}

type EscalationStepInput struct {
	StepOrder      int   `json:"stepOrder"`
	DelayMinutes   int   `json:"delayMinutes"`
	RepeatLastStep *bool `json:"repeatLastStep,omitempty"`
	MaxRepeats     *int  `json:"maxRepeats,omitempty"`
}

type Health struct {
	Status string `json:"status"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginPayload struct {
	User *User `json:"user"`
}

type Mutation struct {
}

type Organization struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Query struct {
}

type Rotation struct {
	ID             string    `json:"id"`
	ScheduleID     string    `json:"scheduleId"`
	OrganizationID string    `json:"organizationId"`
	Name           string    `json:"name"`
	Layer          int       `json:"layer"`
	Rrule          string    `json:"rrule"`
	ParticipantIds []string  `json:"participantIds"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type Schedule struct {
	ID             string      `json:"id"`
	OrganizationID string      `json:"organizationId"`
	TeamID         string      `json:"teamId"`
	Name           string      `json:"name"`
	Timezone       string      `json:"timezone"`
	Rotations      []*Rotation `json:"rotations"`
	CreatedAt      time.Time   `json:"createdAt"`
	UpdatedAt      time.Time   `json:"updatedAt"`
}

type Service struct {
	ID             string    `json:"id"`
	OrganizationID string    `json:"organizationId"`
	TeamID         string    `json:"teamId"`
	Name           string    `json:"name"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type SetupInput struct {
	OrganizationName string `json:"organizationName"`
	Email            string `json:"email"`
	Password         string `json:"password"`
}

type SetupPayload struct {
	Organization *Organization `json:"organization"`
	User         *User         `json:"user"`
}

type Team struct {
	ID             string    `json:"id"`
	OrganizationID string    `json:"organizationId"`
	Name           string    `json:"name"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type UpdateEscalationPolicyInput struct {
	ID    string                 `json:"id"`
	Name  string                 `json:"name"`
	Steps []*EscalationStepInput `json:"steps"`
}

type UpdateRotationInput struct {
	ID             string   `json:"id"`
	Name           string   `json:"name"`
	Layer          int      `json:"layer"`
	Rrule          string   `json:"rrule"`
	ParticipantIds []string `json:"participantIds"`
}

type UpdateScheduleInput struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Timezone string `json:"timezone"`
}

type User struct {
	ID             string    `json:"id"`
	Email          string    `json:"email"`
	Role           UserRole  `json:"role"`
	OrganizationID string    `json:"organizationId"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

// Alert priority levels (doc 02).
type AlertPriority string

const (
	AlertPriorityLow  AlertPriority = "LOW"
	AlertPriorityHigh AlertPriority = "HIGH"
)

var AllAlertPriority = []AlertPriority{
	AlertPriorityLow,
	AlertPriorityHigh,
}

func (e AlertPriority) IsValid() bool {
	switch e {
	case AlertPriorityLow, AlertPriorityHigh:
		return true
	}
	return false
}

func (e AlertPriority) String() string {
	return string(e)
}

func (e *AlertPriority) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AlertPriority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AlertPriority", str)
	}
	return nil
}

func (e AlertPriority) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AlertPriority) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AlertPriority) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Alert lifecycle status (doc 02).
type AlertStatus string

const (
	AlertStatusTriggered    AlertStatus = "TRIGGERED"
	AlertStatusAcknowledged AlertStatus = "ACKNOWLEDGED"
	AlertStatusClosed       AlertStatus = "CLOSED"
)

var AllAlertStatus = []AlertStatus{
	AlertStatusTriggered,
	AlertStatusAcknowledged,
	AlertStatusClosed,
}

func (e AlertStatus) IsValid() bool {
	switch e {
	case AlertStatusTriggered, AlertStatusAcknowledged, AlertStatusClosed:
		return true
	}
	return false
}

func (e AlertStatus) String() string {
	return string(e)
}

func (e *AlertStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AlertStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AlertStatus", str)
	}
	return nil
}

func (e AlertStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AlertStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AlertStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Organization-level role for RBAC (doc 07).
type UserRole string

const (
	UserRoleAdmin  UserRole = "ADMIN"
	UserRoleMember UserRole = "MEMBER"
)

var AllUserRole = []UserRole{
	UserRoleAdmin,
	UserRoleMember,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleAdmin, UserRoleMember:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
