// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AddIncidentTimelineNoteInput struct {
	IncidentID string `json:"incidentId"`
	Body       string `json:"body"`
}

type Alert struct {
	ID             string        `json:"id"`
	OrganizationID string        `json:"organizationId"`
	ServiceID      string        `json:"serviceId"`
	Status         AlertStatus   `json:"status"`
	DedupKey       string        `json:"dedupKey"`
	Summary        string        `json:"summary"`
	Description    *string       `json:"description,omitempty"`
	Priority       AlertPriority `json:"priority"`
	EventCount     int           `json:"eventCount"`
	AcknowledgedAt *time.Time    `json:"acknowledgedAt,omitempty"`
	AcknowledgedBy *User         `json:"acknowledgedBy,omitempty"`
	ClosedAt       *time.Time    `json:"closedAt,omitempty"`
	IncidentID     *string       `json:"incidentId,omitempty"`
	Incident       *Incident     `json:"incident,omitempty"`
	CreatedAt      time.Time     `json:"createdAt"`
	UpdatedAt      time.Time     `json:"updatedAt"`
}

type AssignIncidentRoleInput struct {
	IncidentID       string `json:"incidentId"`
	RoleDefinitionID string `json:"roleDefinitionId"`
	UserID           string `json:"userId"`
}

type CreateEscalationPolicyInput struct {
	ServiceID string                 `json:"serviceId"`
	Name      string                 `json:"name"`
	Steps     []*EscalationStepInput `json:"steps"`
}

type CreateHeartbeatMonitorInput struct {
	ServiceID       string `json:"serviceId"`
	Name            string `json:"name"`
	IntervalSeconds int    `json:"intervalSeconds"`
	GraceSeconds    int    `json:"graceSeconds"`
}

type CreateIncidentInput struct {
	TeamID string `json:"teamId"`
	Title  string `json:"title"`
}

type CreateIncidentRoleDefinitionInput struct {
	Name      string `json:"name"`
	SortOrder *int   `json:"sortOrder,omitempty"`
}

type CreateIntegrationKeyInput struct {
	ServiceID  string         `json:"serviceId"`
	PluginName string         `json:"pluginName"`
	Config     map[string]any `json:"config"`
}

type CreateMaintenanceWindowInput struct {
	ServiceID             string    `json:"serviceId"`
	Description           string    `json:"description"`
	StartsAt              time.Time `json:"startsAt"`
	EndsAt                time.Time `json:"endsAt"`
	SuppressNotifications *bool     `json:"suppressNotifications,omitempty"`
	SuppressIngestion     *bool     `json:"suppressIngestion,omitempty"`
}

type CreateOverrideInput struct {
	ScheduleID string    `json:"scheduleId"`
	RotationID string    `json:"rotationId"`
	UserID     string    `json:"userId"`
	StartsAt   time.Time `json:"startsAt"`
	EndsAt     time.Time `json:"endsAt"`
}

type CreateRotationInput struct {
	ScheduleID     string   `json:"scheduleId"`
	Name           string   `json:"name"`
	Layer          int      `json:"layer"`
	Rrule          string   `json:"rrule"`
	ParticipantIds []string `json:"participantIds"`
}

type CreateScheduleInput struct {
	TeamID   string `json:"teamId"`
	Name     string `json:"name"`
	Timezone string `json:"timezone"`
}

type CreateServiceInput struct {
	TeamID string `json:"teamId"`
	Name   string `json:"name"`
}

type EscalationPolicy struct {
	ID             string            `json:"id"`
	OrganizationID string            `json:"organizationId"`
	ServiceID      string            `json:"serviceId"`
	Name           string            `json:"name"`
	Steps          []*EscalationStep `json:"steps"`
	CreatedAt      time.Time         `json:"createdAt"`
	UpdatedAt      time.Time         `json:"updatedAt"`
}

type EscalationStep struct {
	ID                 string    `json:"id"`
	EscalationPolicyID string    `json:"escalationPolicyId"`
	OrganizationID     string    `json:"organizationId"`
	StepOrder          int       `json:"stepOrder"`
	DelayMinutes       int       `json:"delayMinutes"`
	RepeatLastStep     bool      `json:"repeatLastStep"`
	MaxRepeats         *int      `json:"maxRepeats,omitempty"`
	CreatedAt          time.Time `json:"createdAt"`
	UpdatedAt          time.Time `json:"updatedAt"`
}

type EscalationStepInput struct {
	StepOrder      int                          `json:"stepOrder"`
	DelayMinutes   int                          `json:"delayMinutes"`
	RepeatLastStep *bool                        `json:"repeatLastStep,omitempty"`
	MaxRepeats     *int                         `json:"maxRepeats,omitempty"`
	Targets        []*EscalationStepTargetInput `json:"targets"`
}

type EscalationStepTargetInput struct {
	TargetType string  `json:"targetType"`
	UserID     *string `json:"userId,omitempty"`
	ScheduleID *string `json:"scheduleId,omitempty"`
	WebhookURL *string `json:"webhookUrl,omitempty"`
}

type Health struct {
	Status string `json:"status"`
}

type HeartbeatMonitor struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organizationId"`
	ServiceID      string `json:"serviceId"`
	Name           string `json:"name"`
	// Expected ping interval in seconds.
	IntervalSeconds int `json:"intervalSeconds"`
	// Grace period after a missed ping, in seconds.
	GraceSeconds int                    `json:"graceSeconds"`
	Status       HeartbeatMonitorStatus `json:"status"`
	// Display prefix for the ping token (doc 07).
	TokenPrefix string `json:"tokenPrefix"`
	// Plaintext ping token; only returned from createHeartbeatMonitor.
	Token      *string    `json:"token,omitempty"`
	LastPingAt *time.Time `json:"lastPingAt,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
	UpdatedAt  time.Time  `json:"updatedAt"`
}

// First-class incident aggregate grouping related alerts.
type Incident struct {
	ID              string                    `json:"id"`
	OrganizationID  string                    `json:"organizationId"`
	TeamID          string                    `json:"teamId"`
	Title           string                    `json:"title"`
	Status          IncidentStatus            `json:"status"`
	CreatedBy       *User                     `json:"createdBy"`
	ResolvedAt      *time.Time                `json:"resolvedAt,omitempty"`
	SlackChannelID  *string                   `json:"slackChannelId,omitempty"`
	Alerts          []*Alert                  `json:"alerts"`
	TimelineEvents  []*TimelineEvent          `json:"timelineEvents"`
	RoleAssignments []*IncidentRoleAssignment `json:"roleAssignments"`
	CreatedAt       time.Time                 `json:"createdAt"`
	UpdatedAt       time.Time                 `json:"updatedAt"`
}

// User assigned to a configurable role on an incident.
type IncidentRoleAssignment struct {
	ID         string                  `json:"id"`
	IncidentID string                  `json:"incidentId"`
	Role       *IncidentRoleDefinition `json:"role"`
	User       *User                   `json:"user"`
	AssignedBy *User                   `json:"assignedBy"`
	CreatedAt  time.Time               `json:"createdAt"`
}

// Configurable incident role definition for an organization.
type IncidentRoleDefinition struct {
	ID             string    `json:"id"`
	OrganizationID string    `json:"organizationId"`
	Name           string    `json:"name"`
	SortOrder      int       `json:"sortOrder"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

// Inbound integration key for a service.
type IntegrationKey struct {
	ID             string         `json:"id"`
	OrganizationID string         `json:"organizationId"`
	ServiceID      string         `json:"serviceId"`
	PluginName     string         `json:"pluginName"`
	Config         map[string]any `json:"config"`
	// Display prefix for the token (last-4 style).
	TokenPrefix string `json:"tokenPrefix"`
	// Plaintext webhook token; only returned from createIntegrationKey and rotateIntegrationKey.
	Token     *string    `json:"token,omitempty"`
	RevokedAt *time.Time `json:"revokedAt,omitempty"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Unauthenticated login method availability for the web app.
type LoginOptions struct {
	SamlEnabled  bool    `json:"samlEnabled"`
	SamlLoginURL *string `json:"samlLoginUrl,omitempty"`
	OidcEnabled  bool    `json:"oidcEnabled"`
	OidcLoginURL *string `json:"oidcLoginUrl,omitempty"`
}

type LoginPayload struct {
	User *User `json:"user"`
}

type MaintenanceWindow struct {
	ID                    string    `json:"id"`
	OrganizationID        string    `json:"organizationId"`
	ServiceID             string    `json:"serviceId"`
	Description           string    `json:"description"`
	StartsAt              time.Time `json:"startsAt"`
	EndsAt                time.Time `json:"endsAt"`
	SuppressNotifications bool      `json:"suppressNotifications"`
	SuppressIngestion     bool      `json:"suppressIngestion"`
	CreatedAt             time.Time `json:"createdAt"`
	UpdatedAt             time.Time `json:"updatedAt"`
}

// Registered mobile device for Expo push delivery.
type MobileDevice struct {
	ID          string  `json:"id"`
	Platform    *string `json:"platform,omitempty"`
	DeviceLabel *string `json:"deviceLabel,omitempty"`
	// Display prefix for the Expo push token (last-4 style).
	PushTokenPrefix  string     `json:"pushTokenPrefix"`
	RevokedAt        *time.Time `json:"revokedAt,omitempty"`
	LastRegisteredAt time.Time  `json:"lastRegisteredAt"`
	CreatedAt        time.Time  `json:"createdAt"`
	UpdatedAt        time.Time  `json:"updatedAt"`
}

type Mutation struct {
}

// Registered outbound notification channel and its JSON Schema config form.
type NotificationChannelDefinition struct {
	Name         string         `json:"name"`
	ConfigSchema map[string]any `json:"configSchema"`
}

// Ordered notification channel step for a user priority rule.
type NotificationRuleStep struct {
	Channel      string `json:"channel"`
	DelayMinutes int    `json:"delayMinutes"`
}

type NotificationRuleStepInput struct {
	Channel      string `json:"channel"`
	DelayMinutes int    `json:"delayMinutes"`
}

// On-call user for a single rotation layer.
type OnCallLayer struct {
	Layer      int    `json:"layer"`
	RotationID string `json:"rotationId"`
	UserID     string `json:"userId"`
}

// Current on-call assignment for a schedule's rotation layers.
type OnCallNow struct {
	ScheduleID string         `json:"scheduleId"`
	ComputedAt time.Time      `json:"computedAt"`
	Layers     []*OnCallLayer `json:"layers"`
}

// Emitted when schedule data changes that may affect on-call assignments.
type OnCallUpdatedEvent struct {
	ScheduleID     string `json:"scheduleId"`
	OrganizationID string `json:"organizationId"`
}

type Organization struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// One-off on-call swap that takes precedence over rotation for a time window.
type Override struct {
	ID              string    `json:"id"`
	ScheduleID      string    `json:"scheduleId"`
	RotationID      string    `json:"rotationId"`
	OrganizationID  string    `json:"organizationId"`
	UserID          string    `json:"userId"`
	ReplacedUserID  *string   `json:"replacedUserId,omitempty"`
	StartsAt        time.Time `json:"startsAt"`
	EndsAt          time.Time `json:"endsAt"`
	CreatedByUserID string    `json:"createdByUserId"`
	// Set when an approver confirms the override (Phase 5 approval workflow).
	ApprovedByUserID *string   `json:"approvedByUserId,omitempty"`
	CreatedAt        time.Time `json:"createdAt"`
	UpdatedAt        time.Time `json:"updatedAt"`
}

type PromoteAlertToIncidentInput struct {
	AlertID string `json:"alertId"`
	// Attach to an existing incident instead of creating one.
	IncidentID *string `json:"incidentId,omitempty"`
	// Title when creating a new incident; defaults to the alert summary.
	Title *string `json:"title,omitempty"`
}

type Query struct {
}

type RegisterMobileDeviceInput struct {
	ExpoPushToken string  `json:"expoPushToken"`
	Platform      *string `json:"platform,omitempty"`
	DeviceLabel   *string `json:"deviceLabel,omitempty"`
}

// Result of rotating the organization SCIM bearer token.
type RotateScimTokenPayload struct {
	ScimSettings *ScimSettings `json:"scimSettings"`
	// Plaintext SCIM bearer token; only returned from rotateScimToken.
	Token string `json:"token"`
}

type Rotation struct {
	ID             string    `json:"id"`
	ScheduleID     string    `json:"scheduleId"`
	OrganizationID string    `json:"organizationId"`
	Name           string    `json:"name"`
	Layer          int       `json:"layer"`
	Rrule          string    `json:"rrule"`
	ParticipantIds []string  `json:"participantIds"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

// Organization SAML SSO configuration (admin only).
type SamlSettings struct {
	Configured      bool    `json:"configured"`
	Enabled         bool    `json:"enabled"`
	IdpEntityID     *string `json:"idpEntityId,omitempty"`
	CertificateHint *string `json:"certificateHint,omitempty"`
	// Absolute URL to start SAML login when enabled.
	SamlLoginURL *string `json:"samlLoginUrl,omitempty"`
}

type SaveNotificationRuleInput struct {
	Priority AlertPriority                `json:"priority"`
	Steps    []*NotificationRuleStepInput `json:"steps"`
}

type SaveSamlSettingsInput struct {
	MetadataXML string `json:"metadataXml"`
	Enabled     bool   `json:"enabled"`
}

type SaveSlackSettingsInput struct {
	BotToken string `json:"botToken"`
}

type SaveUserContactMethodInput struct {
	Channel string         `json:"channel"`
	Config  map[string]any `json:"config"`
}

type Schedule struct {
	ID             string      `json:"id"`
	OrganizationID string      `json:"organizationId"`
	TeamID         string      `json:"teamId"`
	Name           string      `json:"name"`
	Timezone       string      `json:"timezone"`
	Rotations      []*Rotation `json:"rotations"`
	CreatedAt      time.Time   `json:"createdAt"`
	UpdatedAt      time.Time   `json:"updatedAt"`
}

// Organization SCIM provisioning configuration (admin only).
type ScimSettings struct {
	Configured bool `json:"configured"`
	// Display prefix for the SCIM bearer token (last-4 style).
	TokenHint *string `json:"tokenHint,omitempty"`
	// Absolute base URL for SCIM 2.0 provisioning endpoints.
	ScimBaseURL *string `json:"scimBaseUrl,omitempty"`
}

type Service struct {
	ID             string    `json:"id"`
	OrganizationID string    `json:"organizationId"`
	TeamID         string    `json:"teamId"`
	Name           string    `json:"name"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
	// Maintenance windows currently suppressing this service.
	ActiveMaintenanceWindows []*MaintenanceWindow `json:"activeMaintenanceWindows"`
	// Auto-promote rule: declare an incident when alert volume exceeds threshold.
	AutoPromoteRule *ServiceAutoPromoteRule `json:"autoPromoteRule"`
}

// Configurable auto-promote rule for a service.
type ServiceAutoPromoteRule struct {
	Enabled        bool `json:"enabled"`
	AlertThreshold int  `json:"alertThreshold"`
	WindowSeconds  int  `json:"windowSeconds"`
	// Alert priorities whose escalation is suppressed while grouped under an incident.
	SuppressEscalationPriorities []AlertPriority `json:"suppressEscalationPriorities"`
}

type SetupInput struct {
	OrganizationName string `json:"organizationName"`
	Email            string `json:"email"`
	Password         string `json:"password"`
}

type SetupPayload struct {
	Organization *Organization `json:"organization"`
	User         *User         `json:"user"`
}

// Organization Slack bot token configuration (hint only after save).
type SlackSettings struct {
	Configured bool    `json:"configured"`
	TokenHint  *string `json:"tokenHint,omitempty"`
	// Slack workspace name when installed via OAuth (Add to Slack). Null for manual token entry.
	WorkspaceName *string `json:"workspaceName,omitempty"`
	// Absolute URL to start Slack OAuth install when enabled; null when OAuth is not configured.
	OauthInstallURL *string `json:"oauthInstallUrl,omitempty"`
}

type Subscription struct {
}

type Team struct {
	ID             string    `json:"id"`
	OrganizationID string    `json:"organizationId"`
	Name           string    `json:"name"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

// Append-only incident timeline entry with actor and body.
type TimelineEvent struct {
	ID             string            `json:"id"`
	IncidentID     string            `json:"incidentId"`
	OrganizationID string            `json:"organizationId"`
	Actor          *User             `json:"actor,omitempty"`
	EventType      TimelineEventType `json:"eventType"`
	Body           string            `json:"body"`
	Metadata       map[string]any    `json:"metadata"`
	CreatedAt      time.Time         `json:"createdAt"`
}

type UpdateEscalationPolicyInput struct {
	ID    string                 `json:"id"`
	Name  string                 `json:"name"`
	Steps []*EscalationStepInput `json:"steps"`
}

type UpdateHeartbeatMonitorInput struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	IntervalSeconds int    `json:"intervalSeconds"`
	GraceSeconds    int    `json:"graceSeconds"`
}

type UpdateIncidentRoleDefinitionInput struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	SortOrder int    `json:"sortOrder"`
}

type UpdateIncidentStatusInput struct {
	ID     string         `json:"id"`
	Status IncidentStatus `json:"status"`
	// Optional note appended with the status change.
	Body *string `json:"body,omitempty"`
}

type UpdateMaintenanceWindowInput struct {
	ID                    string    `json:"id"`
	Description           string    `json:"description"`
	StartsAt              time.Time `json:"startsAt"`
	EndsAt                time.Time `json:"endsAt"`
	SuppressNotifications bool      `json:"suppressNotifications"`
	SuppressIngestion     bool      `json:"suppressIngestion"`
}

type UpdateRotationInput struct {
	ID             string   `json:"id"`
	Name           string   `json:"name"`
	Layer          int      `json:"layer"`
	Rrule          string   `json:"rrule"`
	ParticipantIds []string `json:"participantIds"`
}

type UpdateScheduleInput struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Timezone string `json:"timezone"`
}

type UpdateServiceInput struct {
	ID                                      string          `json:"id"`
	Name                                    *string         `json:"name,omitempty"`
	AutoPromoteEnabled                      *bool           `json:"autoPromoteEnabled,omitempty"`
	AutoPromoteAlertThreshold               *int            `json:"autoPromoteAlertThreshold,omitempty"`
	AutoPromoteWindowSeconds                *int            `json:"autoPromoteWindowSeconds,omitempty"`
	AutoPromoteSuppressEscalationPriorities []AlertPriority `json:"autoPromoteSuppressEscalationPriorities,omitempty"`
}

type User struct {
	ID             string    `json:"id"`
	Email          string    `json:"email"`
	Role           UserRole  `json:"role"`
	OrganizationID string    `json:"organizationId"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

// Per-user contact method configuration for a notification channel.
type UserContactMethod struct {
	ID        string         `json:"id"`
	UserID    string         `json:"userId"`
	Channel   string         `json:"channel"`
	Config    map[string]any `json:"config"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
}

// Per-user notification rule for an alert priority.
type UserNotificationRule struct {
	ID        string                  `json:"id"`
	UserID    string                  `json:"userId"`
	Priority  AlertPriority           `json:"priority"`
	Steps     []*NotificationRuleStep `json:"steps"`
	CreatedAt time.Time               `json:"createdAt"`
	UpdatedAt time.Time               `json:"updatedAt"`
}

// Alert priority levels (doc 02).
type AlertPriority string

const (
	AlertPriorityLow  AlertPriority = "LOW"
	AlertPriorityHigh AlertPriority = "HIGH"
)

var AllAlertPriority = []AlertPriority{
	AlertPriorityLow,
	AlertPriorityHigh,
}

func (e AlertPriority) IsValid() bool {
	switch e {
	case AlertPriorityLow, AlertPriorityHigh:
		return true
	}
	return false
}

func (e AlertPriority) String() string {
	return string(e)
}

func (e *AlertPriority) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AlertPriority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AlertPriority", str)
	}
	return nil
}

func (e AlertPriority) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AlertPriority) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AlertPriority) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Alert lifecycle status (doc 02).
type AlertStatus string

const (
	AlertStatusTriggered    AlertStatus = "TRIGGERED"
	AlertStatusAcknowledged AlertStatus = "ACKNOWLEDGED"
	AlertStatusClosed       AlertStatus = "CLOSED"
)

var AllAlertStatus = []AlertStatus{
	AlertStatusTriggered,
	AlertStatusAcknowledged,
	AlertStatusClosed,
}

func (e AlertStatus) IsValid() bool {
	switch e {
	case AlertStatusTriggered, AlertStatusAcknowledged, AlertStatusClosed:
		return true
	}
	return false
}

func (e AlertStatus) String() string {
	return string(e)
}

func (e *AlertStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AlertStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AlertStatus", str)
	}
	return nil
}

func (e AlertStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AlertStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AlertStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Heartbeat monitor status (doc 02).
type HeartbeatMonitorStatus string

const (
	HeartbeatMonitorStatusHealthy   HeartbeatMonitorStatus = "HEALTHY"
	HeartbeatMonitorStatusOverdue   HeartbeatMonitorStatus = "OVERDUE"
	HeartbeatMonitorStatusTriggered HeartbeatMonitorStatus = "TRIGGERED"
)

var AllHeartbeatMonitorStatus = []HeartbeatMonitorStatus{
	HeartbeatMonitorStatusHealthy,
	HeartbeatMonitorStatusOverdue,
	HeartbeatMonitorStatusTriggered,
}

func (e HeartbeatMonitorStatus) IsValid() bool {
	switch e {
	case HeartbeatMonitorStatusHealthy, HeartbeatMonitorStatusOverdue, HeartbeatMonitorStatusTriggered:
		return true
	}
	return false
}

func (e HeartbeatMonitorStatus) String() string {
	return string(e)
}

func (e *HeartbeatMonitorStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HeartbeatMonitorStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HeartbeatMonitorStatus", str)
	}
	return nil
}

func (e HeartbeatMonitorStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *HeartbeatMonitorStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e HeartbeatMonitorStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Incident lifecycle status (doc 02).
type IncidentStatus string

const (
	IncidentStatusInvestigating IncidentStatus = "INVESTIGATING"
	IncidentStatusIdentified    IncidentStatus = "IDENTIFIED"
	IncidentStatusMonitoring    IncidentStatus = "MONITORING"
	IncidentStatusResolved      IncidentStatus = "RESOLVED"
)

var AllIncidentStatus = []IncidentStatus{
	IncidentStatusInvestigating,
	IncidentStatusIdentified,
	IncidentStatusMonitoring,
	IncidentStatusResolved,
}

func (e IncidentStatus) IsValid() bool {
	switch e {
	case IncidentStatusInvestigating, IncidentStatusIdentified, IncidentStatusMonitoring, IncidentStatusResolved:
		return true
	}
	return false
}

func (e IncidentStatus) String() string {
	return string(e)
}

func (e *IncidentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IncidentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IncidentStatus", str)
	}
	return nil
}

func (e IncidentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *IncidentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e IncidentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Append-only incident timeline event type.
type TimelineEventType string

const (
	TimelineEventTypeDeclared       TimelineEventType = "DECLARED"
	TimelineEventTypeStatusChanged  TimelineEventType = "STATUS_CHANGED"
	TimelineEventTypeNote           TimelineEventType = "NOTE"
	TimelineEventTypeRoleAssigned   TimelineEventType = "ROLE_ASSIGNED"
	TimelineEventTypeRoleUnassigned TimelineEventType = "ROLE_UNASSIGNED"
)

var AllTimelineEventType = []TimelineEventType{
	TimelineEventTypeDeclared,
	TimelineEventTypeStatusChanged,
	TimelineEventTypeNote,
	TimelineEventTypeRoleAssigned,
	TimelineEventTypeRoleUnassigned,
}

func (e TimelineEventType) IsValid() bool {
	switch e {
	case TimelineEventTypeDeclared, TimelineEventTypeStatusChanged, TimelineEventTypeNote, TimelineEventTypeRoleAssigned, TimelineEventTypeRoleUnassigned:
		return true
	}
	return false
}

func (e TimelineEventType) String() string {
	return string(e)
}

func (e *TimelineEventType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TimelineEventType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TimelineEventType", str)
	}
	return nil
}

func (e TimelineEventType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TimelineEventType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TimelineEventType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Organization-level role for RBAC (doc 07).
type UserRole string

const (
	UserRoleAdmin  UserRole = "ADMIN"
	UserRoleMember UserRole = "MEMBER"
)

var AllUserRole = []UserRole{
	UserRoleAdmin,
	UserRoleMember,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleAdmin, UserRoleMember:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
