package main

import (
	"strings"
	"testing"
)

func TestValidMigrationName(t *testing.T) {
	tests := []struct {
		name  string
		valid bool
	}{
		{name: "bootstrap", valid: true},
		{name: "add_foo_column", valid: true},
		{name: "add_column_v2", valid: true},
		{name: "", valid: false},
		{name: "1starts_with_digit", valid: false},
		{name: "has-dash", valid: false},
		{name: "has space", valid: false},
	}

	for _, tc := range tests {
		if got := validMigrationName(tc.name); got != tc.valid {
			t.Fatalf("validMigrationName(%q) = %v, want %v", tc.name, got, tc.valid)
		}
	}
}

func TestPQEnvFromDSN(t *testing.T) {
	env, err := pqEnvFromDSN("postgres://escalite:secret@127.0.0.1:5433/escalite?sslmode=disable")
	if err != nil {
		t.Fatalf("pqEnvFromDSN: %v", err)
	}
	joined := strings.Join(env, " ")
	for _, want := range []string{
		"PGHOST=127.0.0.1",
		"PGPORT=5433",
		"PGUSER=escalite",
		"PGPASSWORD=secret",
		"PGDATABASE=escalite",
		"PGSSLMODE=disable",
	} {
		if !strings.Contains(joined, want) {
			t.Fatalf("missing %q in %q", want, joined)
		}
	}
}

func TestResolveServerDSN(t *testing.T) {
	t.Setenv("DATABASE_URL", "")
	t.Setenv("ESCALITE_DATABASE_URL", "")

	got, err := resolveServerDSN("")
	if err != nil {
		t.Fatalf("resolveServerDSN: %v", err)
	}
	if !strings.Contains(got, "127.0.0.1:5432") {
		t.Fatalf("unexpected default dsn: %q", got)
	}

	t.Setenv("DATABASE_URL", "postgres://a:b@c:5432/db?sslmode=disable")
	got, err = resolveServerDSN("")
	if err != nil || got != "postgres://a:b@c:5432/db?sslmode=disable" {
		t.Fatalf("resolveServerDSN from env = %q, %v", got, err)
	}
}

func TestFormatGooseMigration(t *testing.T) {
	out := formatGooseMigration("ALTER TABLE foo ADD COLUMN bar text;")
	if !strings.HasPrefix(out, "-- Code generated by tools/schema-diff; DO NOT EDIT.\n-- +goose Up\n") {
		t.Fatalf("missing goose Up header: %q", out)
	}
	if !strings.Contains(out, "-- +goose StatementBegin\nALTER TABLE foo ADD COLUMN bar text;\n-- +goose StatementEnd") {
		t.Fatalf("missing per-statement goose wrapper: %q", out)
	}
	if !strings.Contains(out, "-- +goose Down\n-- generated migration; manual rollback required") {
		t.Fatalf("missing goose Down footer: %q", out)
	}
}

func TestFormatGooseMigrationSplitsStatementsAndStripsHazards(t *testing.T) {
	plan := `/*
Statement 0
  - DELETES_DATA: Deletes all rows in the table (and the table itself)
*/
SET SESSION statement_timeout = 3000;
SET SESSION lock_timeout = 3000;
ALTER TABLE "public"."organizations" ADD COLUMN "marker" text;
DROP TABLE "public"."goose_db_version";`

	out := formatGooseMigration(plan)
	if strings.Contains(out, "DELETES_DATA") {
		t.Fatalf("hazard text leaked into migration: %q", out)
	}
	if strings.Contains(out, "goose_db_version") {
		t.Fatalf("goose_db_version DDL leaked into migration: %q", out)
	}
	if strings.Count(out, "-- +goose StatementBegin") != 1 {
		t.Fatalf("expected 1 goose statement after filtering noise, got:\n%s", out)
	}
}

func TestPlanHasNoDriftWhenFilteredPlanEmpty(t *testing.T) {
	plan := `/*
Statement 0
*/
SET SESSION statement_timeout = 1200000;
SET SESSION lock_timeout = 3000;
DROP TABLE "public"."goose_db_version";`

	if got := strings.TrimSpace(filterIgnoredPlanStatements(plan)); got != "" {
		t.Fatalf("expected no drift, got %q", got)
	}
}

func TestFilterIgnoredPlanStatementsDropsGooseVersionTable(t *testing.T) {
	plan := `/*
Statement 0
*/
SET SESSION statement_timeout = 1200000;
SET SESSION lock_timeout = 3000;
DROP TABLE "public"."goose_db_version";
ALTER TABLE "public"."organizations" ADD COLUMN "marker" text;`

	filtered := filterIgnoredPlanStatements(plan)
	if strings.Contains(filtered, "goose_db_version") {
		t.Fatalf("expected goose_db_version statement removed, got %q", filtered)
	}
	if !strings.Contains(filtered, `ADD COLUMN "marker"`) {
		t.Fatalf("expected real DDL kept, got %q", filtered)
	}
}
