package main

import (
	"strings"
	"testing"

	allure "github.com/allure-framework/allure-go/commons/gotest"
	"github.com/allure-framework/allure-go/testify/require"
)

func TestValidMigrationName(t *testing.T) {
	allure.Wrap(t, func(a *allure.Context) {
		tests := []struct {
			name  string
			valid bool
		}{
			{name: "bootstrap", valid: true},
			{name: "add_foo_column", valid: true},
			{name: "add_column_v2", valid: true},
			{name: "", valid: false},
			{name: "1starts_with_digit", valid: false},
			{name: "has-dash", valid: false},
			{name: "has space", valid: false},
		}

		for _, tc := range tests {
			require.Equal(a, tc.valid, validMigrationName(tc.name), "validMigrationName(%q)", tc.name)
		}
	})
}

func TestPQEnvFromDSN(t *testing.T) {
	allure.Wrap(t, func(a *allure.Context) {
		env, err := pqEnvFromDSN("postgres://escalite:secret@127.0.0.1:5433/escalite?sslmode=disable")
		require.NoError(a, err)

		joined := strings.Join(env, " ")
		for _, want := range []string{
			"PGHOST=127.0.0.1",
			"PGPORT=5433",
			"PGUSER=escalite",
			"PGPASSWORD=secret",
			"PGDATABASE=escalite",
			"PGSSLMODE=disable",
		} {
			require.Contains(a, joined, want)
		}
	})
}

func TestResolveServerDSN(t *testing.T) {
	allure.Wrap(t, func(a *allure.Context) {
		a.T().Setenv("DATABASE_URL", "")
		a.T().Setenv("ESCALITE_DATABASE_URL", "")

		got, err := resolveServerDSN("")
		require.NoError(a, err)
		require.Contains(a, got, "127.0.0.1:5432")

		a.T().Setenv("DATABASE_URL", "postgres://a:b@c:5432/db?sslmode=disable")
		got, err = resolveServerDSN("")
		require.NoError(a, err)
		require.Equal(a, "postgres://a:b@c:5432/db?sslmode=disable", got)
	})
}

func TestFormatGooseMigration(t *testing.T) {
	allure.Wrap(t, func(a *allure.Context) {
		out := formatGooseMigration("ALTER TABLE foo ADD COLUMN bar text;")
		require.True(a, strings.HasPrefix(out, "-- Code generated by tools/schema-diff; DO NOT EDIT.\n-- +goose Up\n"))
		require.Contains(a, out, "-- +goose StatementBegin\nALTER TABLE foo ADD COLUMN bar text;\n-- +goose StatementEnd")
		require.Contains(a, out, "-- +goose Down\n-- generated migration; manual rollback required")
	})
}

func TestFormatGooseMigrationSplitsStatementsAndStripsHazards(t *testing.T) {
	allure.Wrap(t, func(a *allure.Context) {
		plan := `/*
Statement 0
  - DELETES_DATA: Deletes all rows in the table (and the table itself)
*/
SET SESSION statement_timeout = 3000;
SET SESSION lock_timeout = 3000;
ALTER TABLE "public"."organizations" ADD COLUMN "marker" text;
DROP TABLE "public"."goose_db_version";`

		out := formatGooseMigration(plan)
		require.NotContains(a, out, "DELETES_DATA")
		require.NotContains(a, out, "goose_db_version")
		require.Equal(a, 1, strings.Count(out, "-- +goose StatementBegin"))
	})
}

func TestPlanHasNoDriftWhenFilteredPlanEmpty(t *testing.T) {
	allure.Wrap(t, func(a *allure.Context) {
		plan := `/*
Statement 0
*/
SET SESSION statement_timeout = 1200000;
SET SESSION lock_timeout = 3000;
DROP TABLE "public"."goose_db_version";`

		require.Empty(a, strings.TrimSpace(filterIgnoredPlanStatements(plan)))
	})
}

func TestFilterIgnoredPlanStatementsDropsGooseVersionTable(t *testing.T) {
	allure.Wrap(t, func(a *allure.Context) {
		plan := `/*
Statement 0
*/
SET SESSION statement_timeout = 1200000;
SET SESSION lock_timeout = 3000;
DROP TABLE "public"."goose_db_version";
ALTER TABLE "public"."organizations" ADD COLUMN "marker" text;`

		filtered := filterIgnoredPlanStatements(plan)
		require.NotContains(a, filtered, "goose_db_version")
		require.Contains(a, filtered, `ADD COLUMN "marker"`)
	})
}
