-- Code generated by tools/schema-diff; DO NOT EDIT.
-- +goose Up
-- +goose StatementBegin
ALTER TABLE "public"."incidents" ADD COLUMN "ticket_url" text COLLATE "pg_catalog"."default";
-- +goose StatementEnd
-- +goose StatementBegin
CREATE TABLE "public"."organization_ticketing_settings" (
	"organization_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"plugin_name" text COLLATE "pg_catalog"."default" NOT NULL,
	"config" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"api_token_ciphertext" bytea NOT NULL,
	"encryption_key_id" text COLLATE "pg_catalog"."default" NOT NULL,
	"token_hint" text COLLATE "pg_catalog"."default" NOT NULL
);
-- +goose StatementEnd
-- +goose StatementBegin
ALTER TABLE "public"."organization_ticketing_settings" ADD CONSTRAINT "organization_ticketing_settings_plugin_name_check" CHECK((plugin_name = ANY (ARRAY['jira'::text, 'servicenow'::text])));
-- +goose StatementEnd
-- +goose StatementBegin
CREATE UNIQUE INDEX organization_ticketing_settings_pkey ON public.organization_ticketing_settings USING btree (organization_id);
-- +goose StatementEnd
-- +goose StatementBegin
ALTER TABLE "public"."organization_ticketing_settings" ADD CONSTRAINT "organization_ticketing_settings_pkey" PRIMARY KEY USING INDEX "organization_ticketing_settings_pkey";
-- +goose StatementEnd
-- +goose StatementBegin
ALTER TABLE "public"."organization_ticketing_settings" ADD CONSTRAINT "organization_ticketing_settings_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE NOT VALID;
-- +goose StatementEnd
-- +goose StatementBegin
ALTER TABLE "public"."organization_ticketing_settings" VALIDATE CONSTRAINT "organization_ticketing_settings_organization_id_fkey";
-- +goose StatementEnd

-- +goose Down
-- generated migration; manual rollback required
