-- Code generated by tools/schema-diff; DO NOT EDIT.
-- DML backfill: migrate existing users into accounts before enforcing account_id NOT NULL.
-- +goose Up
-- +goose StatementBegin
CREATE TABLE "public"."accounts" (
	"id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"email" text COLLATE "pg_catalog"."default" NOT NULL,
	"password_hash" text COLLATE "pg_catalog"."default"
);
-- +goose StatementEnd
-- +goose StatementBegin
CREATE UNIQUE INDEX accounts_email_key ON public.accounts USING btree (email);
-- +goose StatementEnd
-- +goose StatementBegin
ALTER TABLE "public"."accounts" ADD CONSTRAINT "accounts_email_key" UNIQUE USING INDEX "accounts_email_key";
-- +goose StatementEnd
-- +goose StatementBegin
CREATE UNIQUE INDEX accounts_pkey ON public.accounts USING btree (id);
-- +goose StatementEnd
-- +goose StatementBegin
ALTER TABLE "public"."accounts" ADD CONSTRAINT "accounts_pkey" PRIMARY KEY USING INDEX "accounts_pkey";
-- +goose StatementEnd
-- +goose StatementBegin
CREATE INDEX accounts_email_idx ON public.accounts USING btree (email);
-- +goose StatementEnd
-- +goose StatementBegin
ALTER TABLE "public"."users" ADD COLUMN "account_id" uuid;
-- +goose StatementEnd
-- +goose StatementBegin
INSERT INTO accounts (id, email, password_hash, created_at, updated_at)
SELECT u.id, u.email, u.password_hash, u.created_at, u.updated_at
FROM users u;
-- +goose StatementEnd
-- +goose StatementBegin
UPDATE users
SET account_id = id;
-- +goose StatementEnd
-- +goose StatementBegin
ALTER TABLE "public"."users" ALTER COLUMN "account_id" SET NOT NULL;
-- +goose StatementEnd
-- +goose StatementBegin
ALTER TABLE "public"."users" DROP COLUMN "password_hash";
-- +goose StatementEnd
-- +goose StatementBegin
ALTER TABLE "public"."users" ADD CONSTRAINT "users_account_id_fkey" FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE NOT VALID;
-- +goose StatementEnd
-- +goose StatementBegin
ALTER TABLE "public"."users" VALIDATE CONSTRAINT "users_account_id_fkey";
-- +goose StatementEnd
-- +goose StatementBegin
CREATE UNIQUE INDEX users_account_id_organization_id_key ON public.users USING btree (account_id, organization_id);
-- +goose StatementEnd
-- +goose StatementBegin
ALTER TABLE "public"."users" ADD CONSTRAINT "users_account_id_organization_id_key" UNIQUE USING INDEX "users_account_id_organization_id_key";
-- +goose StatementEnd
-- +goose StatementBegin
CREATE INDEX users_account_id_idx ON public.users USING btree (account_id);
-- +goose StatementEnd

-- +goose Down
-- generated migration; manual rollback required
