// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: heartbeat_monitors.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createHeartbeatMonitor = `-- name: CreateHeartbeatMonitor :one
INSERT INTO heartbeat_monitors (
    id,
    organization_id,
    service_id,
    name,
    interval_seconds,
    grace_seconds,
    token_hash,
    prefix,
    status,
    last_ping_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, organization_id, service_id, name, interval_seconds, grace_seconds, token_hash, prefix, status, last_ping_at, created_at, updated_at
`

type CreateHeartbeatMonitorParams struct {
	ID              uuid.UUID          `json:"id"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	ServiceID       uuid.UUID          `json:"service_id"`
	Name            string             `json:"name"`
	IntervalSeconds int32              `json:"interval_seconds"`
	GraceSeconds    int32              `json:"grace_seconds"`
	TokenHash       string             `json:"token_hash"`
	Prefix          string             `json:"prefix"`
	Status          string             `json:"status"`
	LastPingAt      pgtype.Timestamptz `json:"last_ping_at"`
}

func (q *Queries) CreateHeartbeatMonitor(ctx context.Context, arg CreateHeartbeatMonitorParams) (HeartbeatMonitor, error) {
	row := q.db.QueryRow(ctx, createHeartbeatMonitor,
		arg.ID,
		arg.OrganizationID,
		arg.ServiceID,
		arg.Name,
		arg.IntervalSeconds,
		arg.GraceSeconds,
		arg.TokenHash,
		arg.Prefix,
		arg.Status,
		arg.LastPingAt,
	)
	var i HeartbeatMonitor
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.Name,
		&i.IntervalSeconds,
		&i.GraceSeconds,
		&i.TokenHash,
		&i.Prefix,
		&i.Status,
		&i.LastPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlertByServiceDedupKey = `-- name: GetAlertByServiceDedupKey :one
SELECT id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, acknowledged_by_user_id, closed_at, created_at, updated_at
FROM alerts
WHERE service_id = $1
  AND organization_id = $2
  AND dedup_key = $3
  AND status IN ('triggered', 'acknowledged')
ORDER BY created_at DESC
LIMIT 1
`

type GetAlertByServiceDedupKeyParams struct {
	ServiceID      uuid.UUID `json:"service_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	DedupKey       string    `json:"dedup_key"`
}

func (q *Queries) GetAlertByServiceDedupKey(ctx context.Context, arg GetAlertByServiceDedupKeyParams) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlertByServiceDedupKey, arg.ServiceID, arg.OrganizationID, arg.DedupKey)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.IntegrationKeyID,
		&i.Status,
		&i.DedupKey,
		&i.Summary,
		&i.Description,
		&i.Priority,
		&i.EventCount,
		&i.EscalationState,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHeartbeatMonitorsReadyToTrigger = `-- name: ListHeartbeatMonitorsReadyToTrigger :many
SELECT id, organization_id, service_id, name, interval_seconds, grace_seconds, token_hash, prefix, status, last_ping_at, created_at, updated_at
FROM heartbeat_monitors
WHERE status IN ('healthy', 'overdue')
  AND now() > COALESCE(last_ping_at, created_at)
      + ((interval_seconds + grace_seconds) * interval '1 second')
ORDER BY created_at
`

func (q *Queries) ListHeartbeatMonitorsReadyToTrigger(ctx context.Context) ([]HeartbeatMonitor, error) {
	rows, err := q.db.Query(ctx, listHeartbeatMonitorsReadyToTrigger)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeartbeatMonitor{}
	for rows.Next() {
		var i HeartbeatMonitor
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ServiceID,
			&i.Name,
			&i.IntervalSeconds,
			&i.GraceSeconds,
			&i.TokenHash,
			&i.Prefix,
			&i.Status,
			&i.LastPingAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHeartbeatMonitorTriggered = `-- name: MarkHeartbeatMonitorTriggered :one
UPDATE heartbeat_monitors
SET status = 'triggered',
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
  AND status IN ('healthy', 'overdue')
RETURNING id, organization_id, service_id, name, interval_seconds, grace_seconds, token_hash, prefix, status, last_ping_at, created_at, updated_at
`

type MarkHeartbeatMonitorTriggeredParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) MarkHeartbeatMonitorTriggered(ctx context.Context, arg MarkHeartbeatMonitorTriggeredParams) (HeartbeatMonitor, error) {
	row := q.db.QueryRow(ctx, markHeartbeatMonitorTriggered, arg.ID, arg.OrganizationID)
	var i HeartbeatMonitor
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.Name,
		&i.IntervalSeconds,
		&i.GraceSeconds,
		&i.TokenHash,
		&i.Prefix,
		&i.Status,
		&i.LastPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markHeartbeatMonitorsOverdue = `-- name: MarkHeartbeatMonitorsOverdue :execrows
UPDATE heartbeat_monitors
SET status = 'overdue',
    updated_at = now()
WHERE status = 'healthy'
  AND now() > COALESCE(last_ping_at, created_at) + (interval_seconds * interval '1 second')
`

func (q *Queries) MarkHeartbeatMonitorsOverdue(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markHeartbeatMonitorsOverdue)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
