// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (
    id,
    organization_id,
    team_id,
    title,
    status,
    created_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'investigating',
    $5
)
RETURNING id, organization_id, team_id, title, status, created_by_user_id, resolved_at, slack_channel_id, slack_thread_ts, created_at, updated_at
`

type CreateIncidentParams struct {
	ID              uuid.UUID `json:"id"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	TeamID          uuid.UUID `json:"team_id"`
	Title           string    `json:"title"`
	CreatedByUserID uuid.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.ID,
		arg.OrganizationID,
		arg.TeamID,
		arg.Title,
		arg.CreatedByUserID,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Title,
		&i.Status,
		&i.CreatedByUserID,
		&i.ResolvedAt,
		&i.SlackChannelID,
		&i.SlackThreadTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTimelineEvent = `-- name: CreateTimelineEvent :one
INSERT INTO timeline_events (
    id,
    incident_id,
    organization_id,
    actor_id,
    event_type,
    body,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, incident_id, organization_id, actor_id, event_type, body, metadata, created_at
`

type CreateTimelineEventParams struct {
	ID             uuid.UUID   `json:"id"`
	IncidentID     uuid.UUID   `json:"incident_id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	ActorID        pgtype.UUID `json:"actor_id"`
	EventType      string      `json:"event_type"`
	Body           string      `json:"body"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) CreateTimelineEvent(ctx context.Context, arg CreateTimelineEventParams) (TimelineEvent, error) {
	row := q.db.QueryRow(ctx, createTimelineEvent,
		arg.ID,
		arg.IncidentID,
		arg.OrganizationID,
		arg.ActorID,
		arg.EventType,
		arg.Body,
		arg.Metadata,
	)
	var i TimelineEvent
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.OrganizationID,
		&i.ActorID,
		&i.EventType,
		&i.Body,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getIncidentByID = `-- name: GetIncidentByID :one
SELECT id, organization_id, team_id, title, status, created_by_user_id, resolved_at, slack_channel_id, slack_thread_ts, created_at, updated_at
FROM incidents
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetIncidentByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetIncidentByID(ctx context.Context, arg GetIncidentByIDParams) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncidentByID, arg.ID, arg.OrganizationID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Title,
		&i.Status,
		&i.CreatedByUserID,
		&i.ResolvedAt,
		&i.SlackChannelID,
		&i.SlackThreadTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenIncidentForTeam = `-- name: GetOpenIncidentForTeam :one
SELECT id, organization_id, team_id, title, status, created_by_user_id, resolved_at, slack_channel_id, slack_thread_ts, created_at, updated_at
FROM incidents
WHERE organization_id = $1
  AND team_id = $2
  AND status <> 'resolved'
ORDER BY created_at DESC
LIMIT 1
`

type GetOpenIncidentForTeamParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	TeamID         uuid.UUID `json:"team_id"`
}

func (q *Queries) GetOpenIncidentForTeam(ctx context.Context, arg GetOpenIncidentForTeamParams) (Incident, error) {
	row := q.db.QueryRow(ctx, getOpenIncidentForTeam, arg.OrganizationID, arg.TeamID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Title,
		&i.Status,
		&i.CreatedByUserID,
		&i.ResolvedAt,
		&i.SlackChannelID,
		&i.SlackThreadTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenIncidentForTeamWithServiceAlerts = `-- name: GetOpenIncidentForTeamWithServiceAlerts :one
SELECT DISTINCT i.id, i.organization_id, i.team_id, i.title, i.status, i.created_by_user_id, i.resolved_at, i.slack_channel_id, i.slack_thread_ts, i.created_at, i.updated_at
FROM incidents i
INNER JOIN alerts a
  ON a.incident_id = i.id
 AND a.organization_id = i.organization_id
WHERE i.organization_id = $1
  AND i.team_id = $2
  AND i.status <> 'resolved'
  AND a.service_id = $3
ORDER BY i.created_at DESC
LIMIT 1
`

type GetOpenIncidentForTeamWithServiceAlertsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	TeamID         uuid.UUID `json:"team_id"`
	ServiceID      uuid.UUID `json:"service_id"`
}

func (q *Queries) GetOpenIncidentForTeamWithServiceAlerts(ctx context.Context, arg GetOpenIncidentForTeamWithServiceAlertsParams) (Incident, error) {
	row := q.db.QueryRow(ctx, getOpenIncidentForTeamWithServiceAlerts, arg.OrganizationID, arg.TeamID, arg.ServiceID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Title,
		&i.Status,
		&i.CreatedByUserID,
		&i.ResolvedAt,
		&i.SlackChannelID,
		&i.SlackThreadTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIncidentSlackChannelID = `-- name: UpdateIncidentSlackChannelID :one
UPDATE incidents
SET slack_channel_id = $3,
    updated_at = now()
WHERE id = $1
  AND organization_id = $2
RETURNING id, organization_id, team_id, title, status, created_by_user_id, resolved_at, slack_channel_id, slack_thread_ts, created_at, updated_at
`

type UpdateIncidentSlackChannelIDParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	SlackChannelID pgtype.Text `json:"slack_channel_id"`
}

func (q *Queries) UpdateIncidentSlackChannelID(ctx context.Context, arg UpdateIncidentSlackChannelIDParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncidentSlackChannelID, arg.ID, arg.OrganizationID, arg.SlackChannelID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Title,
		&i.Status,
		&i.CreatedByUserID,
		&i.ResolvedAt,
		&i.SlackChannelID,
		&i.SlackThreadTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
