// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_slack_settings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getOrganizationSlackSettings = `-- name: GetOrganizationSlackSettings :one
SELECT organization_id, bot_token_ciphertext, encryption_key_id, token_hint, workspace_id, workspace_name, bot_user_id, scope, created_at, updated_at
FROM organization_slack_settings
WHERE organization_id = $1
LIMIT 1
`

func (q *Queries) GetOrganizationSlackSettings(ctx context.Context, organizationID uuid.UUID) (OrganizationSlackSetting, error) {
	row := q.db.QueryRow(ctx, getOrganizationSlackSettings, organizationID)
	var i OrganizationSlackSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.BotTokenCiphertext,
		&i.EncryptionKeyID,
		&i.TokenHint,
		&i.WorkspaceID,
		&i.WorkspaceName,
		&i.BotUserID,
		&i.Scope,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
