// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_ticketing_settings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getOrganizationTicketingSettings = `-- name: GetOrganizationTicketingSettings :one
SELECT organization_id, plugin_name, config, api_token_ciphertext, encryption_key_id, token_hint, created_at, updated_at
FROM organization_ticketing_settings
WHERE organization_id = $1
LIMIT 1
`

func (q *Queries) GetOrganizationTicketingSettings(ctx context.Context, organizationID uuid.UUID) (OrganizationTicketingSetting, error) {
	row := q.db.QueryRow(ctx, getOrganizationTicketingSettings, organizationID)
	var i OrganizationTicketingSetting
	err := row.Scan(
		&i.OrganizationID,
		&i.PluginName,
		&i.Config,
		&i.ApiTokenCiphertext,
		&i.EncryptionKeyID,
		&i.TokenHint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
