// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) (Alert, error)
	BootstrapOrganizationWithAdmin(ctx context.Context, arg BootstrapOrganizationWithAdminParams) (BootstrapOrganizationWithAdminRow, error)
	CloseAlert(ctx context.Context, arg CloseAlertParams) (Alert, error)
	CountNotificationAttemptsByAlertID(ctx context.Context, arg CountNotificationAttemptsByAlertIDParams) (int64, error)
	CreateEscalationPolicy(ctx context.Context, arg CreateEscalationPolicyParams) (EscalationPolicy, error)
	CreateEscalationStep(ctx context.Context, arg CreateEscalationStepParams) (EscalationStep, error)
	CreateEscalationStepTarget(ctx context.Context, arg CreateEscalationStepTargetParams) (EscalationStepTarget, error)
	CreateNotificationAttempt(ctx context.Context, arg CreateNotificationAttemptParams) (NotificationAttempt, error)
	CreateRotation(ctx context.Context, arg CreateRotationParams) (Rotation, error)
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateTriggeredAlert(ctx context.Context, arg CreateTriggeredAlertParams) (Alert, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAlertByID(ctx context.Context, arg GetAlertByIDParams) (Alert, error)
	GetEscalationStepByPolicyAndOrder(ctx context.Context, arg GetEscalationStepByPolicyAndOrderParams) (EscalationStep, error)
	GetNotificationAttemptByID(ctx context.Context, arg GetNotificationAttemptByIDParams) (NotificationAttempt, error)
	GetScheduleByID(ctx context.Context, arg GetScheduleByIDParams) (Schedule, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	ListActiveOverridesByScheduleAt(ctx context.Context, arg ListActiveOverridesByScheduleAtParams) ([]Override, error)
	ListEscalationPoliciesByServiceID(ctx context.Context, arg ListEscalationPoliciesByServiceIDParams) ([]EscalationPolicy, error)
	ListEscalationStepTargetsByStepID(ctx context.Context, arg ListEscalationStepTargetsByStepIDParams) ([]EscalationStepTarget, error)
	ListNotificationAttemptsByAlertID(ctx context.Context, arg ListNotificationAttemptsByAlertIDParams) ([]NotificationAttempt, error)
	ListRotationsByScheduleID(ctx context.Context, arg ListRotationsByScheduleIDParams) ([]Rotation, error)
	ReEscalateAlert(ctx context.Context, arg ReEscalateAlertParams) (Alert, error)
	UpdateAlertEscalationState(ctx context.Context, arg UpdateAlertEscalationStateParams) (Alert, error)
}

var _ Querier = (*Queries)(nil)
