// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rotations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createRotation = `-- name: CreateRotation :one
INSERT INTO rotations (
    id,
    schedule_id,
    organization_id,
    name,
    layer,
    rrule,
    participants
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, schedule_id, organization_id, name, layer, rrule, participants, created_at, updated_at
`

type CreateRotationParams struct {
	ID             uuid.UUID `json:"id"`
	ScheduleID     uuid.UUID `json:"schedule_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	Layer          int32     `json:"layer"`
	Rrule          string    `json:"rrule"`
	Participants   []byte    `json:"participants"`
}

func (q *Queries) CreateRotation(ctx context.Context, arg CreateRotationParams) (Rotation, error) {
	row := q.db.QueryRow(ctx, createRotation,
		arg.ID,
		arg.ScheduleID,
		arg.OrganizationID,
		arg.Name,
		arg.Layer,
		arg.Rrule,
		arg.Participants,
	)
	var i Rotation
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.OrganizationID,
		&i.Name,
		&i.Layer,
		&i.Rrule,
		&i.Participants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRotationsByScheduleID = `-- name: ListRotationsByScheduleID :many
SELECT id, schedule_id, organization_id, name, layer, rrule, participants, created_at, updated_at
FROM rotations
WHERE schedule_id = $1
  AND organization_id = $2
ORDER BY layer
`

type ListRotationsByScheduleIDParams struct {
	ScheduleID     uuid.UUID `json:"schedule_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) ListRotationsByScheduleID(ctx context.Context, arg ListRotationsByScheduleIDParams) ([]Rotation, error) {
	rows, err := q.db.Query(ctx, listRotationsByScheduleID, arg.ScheduleID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rotation{}
	for rows.Next() {
		var i Rotation
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.OrganizationID,
			&i.Name,
			&i.Layer,
			&i.Rrule,
			&i.Participants,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
