// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (
    id,
    organization_id,
    team_id,
    name,
    timezone
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, organization_id, team_id, name, timezone, created_at, updated_at
`

type CreateScheduleParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	TeamID         uuid.UUID `json:"team_id"`
	Name           string    `json:"name"`
	Timezone       string    `json:"timezone"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.ID,
		arg.OrganizationID,
		arg.TeamID,
		arg.Name,
		arg.Timezone,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduleByID = `-- name: GetScheduleByID :one
SELECT id, organization_id, team_id, name, timezone, created_at, updated_at
FROM schedules
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetScheduleByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetScheduleByID(ctx context.Context, arg GetScheduleByIDParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, getScheduleByID, arg.ID, arg.OrganizationID)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
