// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, organization_id, team_id, name, dedup_window_seconds, auto_promote_enabled, auto_promote_alert_threshold, auto_promote_window_seconds, auto_promote_suppress_escalation_priorities, deleted_at, created_at, updated_at
FROM services
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetServiceByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetServiceByID(ctx context.Context, arg GetServiceByIDParams) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, arg.ID, arg.OrganizationID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.DedupWindowSeconds,
		&i.AutoPromoteEnabled,
		&i.AutoPromoteAlertThreshold,
		&i.AutoPromoteWindowSeconds,
		&i.AutoPromoteSuppressEscalationPriorities,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
