// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status_pages.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getStatusPageByID = `-- name: GetStatusPageByID :one
SELECT id, organization_id, slug, title, enabled, frame_ancestors_csp, created_at, updated_at
FROM status_pages
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetStatusPageByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetStatusPageByID(ctx context.Context, arg GetStatusPageByIDParams) (StatusPage, error) {
	row := q.db.QueryRow(ctx, getStatusPageByID, arg.ID, arg.OrganizationID)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Title,
		&i.Enabled,
		&i.FrameAncestorsCsp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStatusPageIncidentByID = `-- name: GetStatusPageIncidentByID :one
SELECT id, status_page_id, organization_id, incident_id, title, status, resolved_at, created_at, updated_at
FROM status_page_incidents
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetStatusPageIncidentByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetStatusPageIncidentByID(ctx context.Context, arg GetStatusPageIncidentByIDParams) (StatusPageIncident, error) {
	row := q.db.QueryRow(ctx, getStatusPageIncidentByID, arg.ID, arg.OrganizationID)
	var i StatusPageIncident
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.OrganizationID,
		&i.IncidentID,
		&i.Title,
		&i.Status,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStatusPageIncidentUpdateByID = `-- name: GetStatusPageIncidentUpdateByID :one
SELECT id, status_page_incident_id, organization_id, body, status, created_at
FROM status_page_incident_updates
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetStatusPageIncidentUpdateByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetStatusPageIncidentUpdateByID(ctx context.Context, arg GetStatusPageIncidentUpdateByIDParams) (StatusPageIncidentUpdate, error) {
	row := q.db.QueryRow(ctx, getStatusPageIncidentUpdateByID, arg.ID, arg.OrganizationID)
	var i StatusPageIncidentUpdate
	err := row.Scan(
		&i.ID,
		&i.StatusPageIncidentID,
		&i.OrganizationID,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveStatusPageSubscriptions = `-- name: ListActiveStatusPageSubscriptions :many
SELECT id, status_page_id, organization_id, email, unsubscribed_at, created_at
FROM status_page_subscriptions
WHERE status_page_id = $1
  AND organization_id = $2
  AND unsubscribed_at IS NULL
ORDER BY created_at ASC
`

type ListActiveStatusPageSubscriptionsParams struct {
	StatusPageID   uuid.UUID `json:"status_page_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) ListActiveStatusPageSubscriptions(ctx context.Context, arg ListActiveStatusPageSubscriptionsParams) ([]StatusPageSubscription, error) {
	rows, err := q.db.Query(ctx, listActiveStatusPageSubscriptions, arg.StatusPageID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPageSubscription{}
	for rows.Next() {
		var i StatusPageSubscription
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.OrganizationID,
			&i.Email,
			&i.UnsubscribedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
