// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test_seed.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bootstrapOrganizationWithAdmin = `-- name: BootstrapOrganizationWithAdmin :one
WITH new_org AS (
    INSERT INTO organizations (id, name)
    VALUES ($1, $2)
    RETURNING id, name
),
new_account AS (
    INSERT INTO accounts (id, email, password_hash)
    VALUES ($3, $4, $5)
    RETURNING id
),
new_user AS (
    INSERT INTO users (id, account_id, organization_id, email, role)
    VALUES (
        $6,
        (SELECT id FROM new_account),
        (SELECT id FROM new_org),
        $4,
        'admin'
    )
    RETURNING id, organization_id, email, role
)
SELECT
    new_org.id AS organization_id,
    new_org.name AS organization_name,
    new_user.id AS user_id,
    new_user.email AS user_email,
    new_user.role AS user_role
FROM new_org, new_user
`

type BootstrapOrganizationWithAdminParams struct {
	OrgID        uuid.UUID   `json:"org_id"`
	OrgName      string      `json:"org_name"`
	AccountID    uuid.UUID   `json:"account_id"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	UserID       uuid.UUID   `json:"user_id"`
}

type BootstrapOrganizationWithAdminRow struct {
	OrganizationID   uuid.UUID `json:"organization_id"`
	OrganizationName string    `json:"organization_name"`
	UserID           uuid.UUID `json:"user_id"`
	UserEmail        string    `json:"user_email"`
	UserRole         string    `json:"user_role"`
}

func (q *Queries) BootstrapOrganizationWithAdmin(ctx context.Context, arg BootstrapOrganizationWithAdminParams) (BootstrapOrganizationWithAdminRow, error) {
	row := q.db.QueryRow(ctx, bootstrapOrganizationWithAdmin,
		arg.OrgID,
		arg.OrgName,
		arg.AccountID,
		arg.Email,
		arg.PasswordHash,
		arg.UserID,
	)
	var i BootstrapOrganizationWithAdminRow
	err := row.Scan(
		&i.OrganizationID,
		&i.OrganizationName,
		&i.UserID,
		&i.UserEmail,
		&i.UserRole,
	)
	return i, err
}

const createEscalationPolicy = `-- name: CreateEscalationPolicy :one
INSERT INTO escalation_policies (id, organization_id, service_id, name)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, service_id, name, created_at, updated_at
`

type CreateEscalationPolicyParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	ServiceID      uuid.UUID `json:"service_id"`
	Name           string    `json:"name"`
}

func (q *Queries) CreateEscalationPolicy(ctx context.Context, arg CreateEscalationPolicyParams) (EscalationPolicy, error) {
	row := q.db.QueryRow(ctx, createEscalationPolicy,
		arg.ID,
		arg.OrganizationID,
		arg.ServiceID,
		arg.Name,
	)
	var i EscalationPolicy
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEscalationStep = `-- name: CreateEscalationStep :one
INSERT INTO escalation_steps (
    id,
    escalation_policy_id,
    organization_id,
    step_order,
    delay_minutes,
    repeat_last_step,
    max_repeats
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, escalation_policy_id, organization_id, step_order, delay_minutes, repeat_last_step, max_repeats, created_at, updated_at
`

type CreateEscalationStepParams struct {
	ID                 uuid.UUID   `json:"id"`
	EscalationPolicyID uuid.UUID   `json:"escalation_policy_id"`
	OrganizationID     uuid.UUID   `json:"organization_id"`
	StepOrder          int32       `json:"step_order"`
	DelayMinutes       int32       `json:"delay_minutes"`
	RepeatLastStep     bool        `json:"repeat_last_step"`
	MaxRepeats         pgtype.Int4 `json:"max_repeats"`
}

func (q *Queries) CreateEscalationStep(ctx context.Context, arg CreateEscalationStepParams) (EscalationStep, error) {
	row := q.db.QueryRow(ctx, createEscalationStep,
		arg.ID,
		arg.EscalationPolicyID,
		arg.OrganizationID,
		arg.StepOrder,
		arg.DelayMinutes,
		arg.RepeatLastStep,
		arg.MaxRepeats,
	)
	var i EscalationStep
	err := row.Scan(
		&i.ID,
		&i.EscalationPolicyID,
		&i.OrganizationID,
		&i.StepOrder,
		&i.DelayMinutes,
		&i.RepeatLastStep,
		&i.MaxRepeats,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEscalationStepTarget = `-- name: CreateEscalationStepTarget :one
INSERT INTO escalation_step_targets (
    id,
    escalation_step_id,
    organization_id,
    target_type,
    user_id,
    schedule_id,
    webhook_url,
    channels
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, escalation_step_id, organization_id, target_type, user_id, schedule_id, webhook_url, channels, created_at
`

type CreateEscalationStepTargetParams struct {
	ID               uuid.UUID   `json:"id"`
	EscalationStepID uuid.UUID   `json:"escalation_step_id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	TargetType       string      `json:"target_type"`
	UserID           pgtype.UUID `json:"user_id"`
	ScheduleID       pgtype.UUID `json:"schedule_id"`
	WebhookUrl       pgtype.Text `json:"webhook_url"`
	Channels         []byte      `json:"channels"`
}

func (q *Queries) CreateEscalationStepTarget(ctx context.Context, arg CreateEscalationStepTargetParams) (EscalationStepTarget, error) {
	row := q.db.QueryRow(ctx, createEscalationStepTarget,
		arg.ID,
		arg.EscalationStepID,
		arg.OrganizationID,
		arg.TargetType,
		arg.UserID,
		arg.ScheduleID,
		arg.WebhookUrl,
		arg.Channels,
	)
	var i EscalationStepTarget
	err := row.Scan(
		&i.ID,
		&i.EscalationStepID,
		&i.OrganizationID,
		&i.TargetType,
		&i.UserID,
		&i.ScheduleID,
		&i.WebhookUrl,
		&i.Channels,
		&i.CreatedAt,
	)
	return i, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (id, organization_id, team_id, name)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, team_id, name, dedup_window_seconds, auto_promote_enabled, auto_promote_alert_threshold, auto_promote_window_seconds, auto_promote_suppress_escalation_priorities, deleted_at, created_at, updated_at
`

type CreateServiceParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	TeamID         uuid.UUID `json:"team_id"`
	Name           string    `json:"name"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.ID,
		arg.OrganizationID,
		arg.TeamID,
		arg.Name,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.DedupWindowSeconds,
		&i.AutoPromoteEnabled,
		&i.AutoPromoteAlertThreshold,
		&i.AutoPromoteWindowSeconds,
		&i.AutoPromoteSuppressEscalationPriorities,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, organization_id, name)
VALUES ($1, $2, $3)
RETURNING id, organization_id, name, created_at, updated_at
`

type CreateTeamParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.ID, arg.OrganizationID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTriggeredAlert = `-- name: CreateTriggeredAlert :one
INSERT INTO alerts (
    id,
    organization_id,
    service_id,
    integration_key_id,
    status,
    dedup_key,
    summary,
    description,
    priority,
    escalation_state
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'triggered',
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, organization_id, service_id, integration_key_id, status, dedup_key, summary, description, priority, event_count, escalation_state, acknowledged_at, acknowledged_by_user_id, closed_at, resolved_at, resolved_integration, incident_id, created_at, updated_at
`

type CreateTriggeredAlertParams struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	ServiceID        uuid.UUID   `json:"service_id"`
	IntegrationKeyID pgtype.UUID `json:"integration_key_id"`
	DedupKey         string      `json:"dedup_key"`
	Summary          string      `json:"summary"`
	Description      pgtype.Text `json:"description"`
	Priority         string      `json:"priority"`
	EscalationState  []byte      `json:"escalation_state"`
}

func (q *Queries) CreateTriggeredAlert(ctx context.Context, arg CreateTriggeredAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createTriggeredAlert,
		arg.ID,
		arg.OrganizationID,
		arg.ServiceID,
		arg.IntegrationKeyID,
		arg.DedupKey,
		arg.Summary,
		arg.Description,
		arg.Priority,
		arg.EscalationState,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.IntegrationKeyID,
		&i.Status,
		&i.DedupKey,
		&i.Summary,
		&i.Description,
		&i.Priority,
		&i.EventCount,
		&i.EscalationState,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ClosedAt,
		&i.ResolvedAt,
		&i.ResolvedIntegration,
		&i.IncidentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, account_id, organization_id, email, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, account_id, organization_id, email, role, scim_external_id, deprovisioned_at, created_at, updated_at
`

type CreateUserParams struct {
	ID             uuid.UUID `json:"id"`
	AccountID      uuid.UUID `json:"account_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Email          string    `json:"email"`
	Role           string    `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.AccountID,
		arg.OrganizationID,
		arg.Email,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.ScimExternalID,
		&i.DeprovisionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
