// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getFirstAdminUserByOrganization = `-- name: GetFirstAdminUserByOrganization :one
SELECT id, account_id, organization_id, email, role, scim_external_id, deprovisioned_at, created_at, updated_at
FROM users
WHERE organization_id = $1
  AND role = 'admin'
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetFirstAdminUserByOrganization(ctx context.Context, organizationID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getFirstAdminUserByOrganization, organizationID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.ScimExternalID,
		&i.DeprovisionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, account_id, organization_id, email, role, scim_external_id, deprovisioned_at, created_at, updated_at
FROM users
WHERE id = $1
  AND organization_id = $2
LIMIT 1
`

type GetUserByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.OrganizationID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.ScimExternalID,
		&i.DeprovisionedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
