// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_contact_methods.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUserContactMethodByChannel = `-- name: GetUserContactMethodByChannel :one
SELECT id, organization_id, user_id, channel, config, created_at, updated_at
FROM user_contact_methods
WHERE organization_id = $1
  AND user_id = $2
  AND channel = $3
LIMIT 1
`

type GetUserContactMethodByChannelParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Channel        string    `json:"channel"`
}

func (q *Queries) GetUserContactMethodByChannel(ctx context.Context, arg GetUserContactMethodByChannelParams) (UserContactMethod, error) {
	row := q.db.QueryRow(ctx, getUserContactMethodByChannel, arg.OrganizationID, arg.UserID, arg.Channel)
	var i UserContactMethod
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Channel,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
