package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"net/mail"
	"strings"
	"time"

	"github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/mdg-labs/escalite/services/api/graph/model"
	"github.com/mdg-labs/escalite/services/api/internal/audit"
	"github.com/mdg-labs/escalite/services/api/internal/auth"
	"github.com/mdg-labs/escalite/services/api/internal/db"
	"github.com/mdg-labs/escalite/services/api/internal/gqlerr"
	"github.com/mdg-labs/escalite/services/api/internal/handlers"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginPayload, error) {
	email := strings.ToLower(strings.TrimSpace(input.Email))
	password := input.Password

	if email == "" {
		return nil, gqlerr.New(handlers.CodeValidation, "email is required")
	}
	if _, err := mail.ParseAddress(email); err != nil {
		return nil, gqlerr.New(handlers.CodeValidation, "email is invalid")
	}
	if password == "" {
		return nil, gqlerr.New(handlers.CodeValidation, "password is required")
	}

	queries := db.New(r.pool)
	requestMeta := audit.RequestMeta{}
	if req, ok := handlers.GraphQLRequestFromContext(ctx); ok {
		requestMeta = audit.RequestMetaFromHTTP(req)
	}
	requestMeta.Email = email

	user, err := queries.GetUserByEmailForAuth(ctx, email)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			r.recordFailedLogin(ctx, queries, nil, requestMeta)
			return nil, gqlerr.New(handlers.CodeUnauthenticated, invalidCredentialsMessage)
		}
		r.logger.Error("lookup user failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if !user.PasswordHash.Valid || user.PasswordHash.String == "" {
		r.recordFailedLogin(ctx, queries, &user, requestMeta)
		return nil, gqlerr.New(handlers.CodeUnauthenticated, invalidCredentialsMessage)
	}

	match, err := auth.VerifyPassword(password, user.PasswordHash.String)
	if err != nil {
		r.logger.Error("verify password failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}
	if !match {
		r.recordFailedLogin(ctx, queries, &user, requestMeta)
		return nil, gqlerr.New(handlers.CodeUnauthenticated, invalidCredentialsMessage)
	}

	sessionID := uuid.Must(uuid.NewV7())
	expiresAt := time.Now().UTC().Add(auth.DefaultSessionTTL)
	userAgent := ""
	if req, ok := handlers.GraphQLRequestFromContext(ctx); ok {
		userAgent = req.UserAgent()
	}

	_, err = queries.CreateSession(ctx, db.CreateSessionParams{
		ID:             sessionID,
		UserID:         user.ID,
		OrganizationID: user.OrganizationID,
		ExpiresAt:      pgtype.Timestamptz{Time: expiresAt, Valid: true},
		UserAgent:      pgtype.Text{String: userAgent, Valid: userAgent != ""},
	})
	if err != nil {
		r.logger.Error("create session failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if w, ok := handlers.GraphQLResponseWriterFromContext(ctx); ok {
		auth.SetSessionCookie(w, sessionID, expiresAt)
	}

	r.audit.Login(ctx, queries, user.OrganizationID, user.ID, requestMeta)

	return &model.LoginPayload{User: userFromDB(user)}, nil
}

// Setup is the resolver for the setup field.
func (r *mutationResolver) Setup(ctx context.Context, input model.SetupInput) (*model.SetupPayload, error) {
	orgName := strings.TrimSpace(input.OrganizationName)
	email := strings.ToLower(strings.TrimSpace(input.Email))
	password := input.Password

	if orgName == "" {
		return nil, gqlerr.New(handlers.CodeValidation, "organizationName is required")
	}
	if email == "" {
		return nil, gqlerr.New(handlers.CodeValidation, "email is required")
	}
	if _, err := mail.ParseAddress(email); err != nil {
		return nil, gqlerr.New(handlers.CodeValidation, "email is invalid")
	}
	if len(password) < minPasswordLength {
		return nil, gqlerr.New(handlers.CodeValidation, "password must be at least 8 characters")
	}

	queries := db.New(r.pool)

	userCount, err := queries.CountUsers(ctx)
	if err != nil {
		r.logger.Error("count users failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}
	if userCount > 0 {
		return nil, gqlerr.New(handlers.CodeForbidden, "setup is disabled after the first admin exists")
	}

	passwordHash, err := auth.HashPassword(password)
	if err != nil {
		r.logger.Error("hash password failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	orgID := uuid.Must(uuid.NewV7())
	userID := uuid.Must(uuid.NewV7())
	sessionID := uuid.Must(uuid.NewV7())
	expiresAt := time.Now().UTC().Add(auth.DefaultSessionTTL)
	userAgent := ""
	if req, ok := handlers.GraphQLRequestFromContext(ctx); ok {
		userAgent = req.UserAgent()
	}

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		r.logger.Error("begin transaction failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}
	defer func() {
		_ = tx.Rollback(ctx)
	}()

	txQueries := queries.WithTx(tx)

	_, err = txQueries.BootstrapOrganizationWithAdmin(ctx, db.BootstrapOrganizationWithAdminParams{
		OrgID:        orgID,
		OrgName:      orgName,
		UserID:       userID,
		Email:        email,
		PasswordHash: pgtype.Text{String: passwordHash, Valid: true},
	})
	if err != nil {
		r.logger.Error("bootstrap organization failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	_, err = txQueries.CreateSession(ctx, db.CreateSessionParams{
		ID:             sessionID,
		UserID:         userID,
		OrganizationID: orgID,
		ExpiresAt:      pgtype.Timestamptz{Time: expiresAt, Valid: true},
		UserAgent:      pgtype.Text{String: userAgent, Valid: userAgent != ""},
	})
	if err != nil {
		r.logger.Error("create session failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	requestMeta := audit.RequestMeta{}
	if req, ok := handlers.GraphQLRequestFromContext(ctx); ok {
		requestMeta = audit.RequestMetaFromHTTP(req)
	}
	r.audit.Login(ctx, txQueries, orgID, userID, requestMeta)

	if err := tx.Commit(ctx); err != nil {
		r.logger.Error("commit transaction failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if w, ok := handlers.GraphQLResponseWriterFromContext(ctx); ok {
		auth.SetSessionCookie(w, sessionID, expiresAt)
	}

	org, err := queries.GetOrganizationByID(ctx, orgID)
	if err != nil {
		r.logger.Error("load organization failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	user, err := queries.GetUserByID(ctx, db.GetUserByIDParams{
		ID:             userID,
		OrganizationID: orgID,
	})
	if err != nil {
		r.logger.Error("load user failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	return &model.SetupPayload{
		Organization: organizationFromDB(org),
		User:         userFromDB(user),
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	sc, ok := auth.SessionFromContext(ctx)
	if !ok {
		return nil, nil
	}
	return userFromDB(sc.User), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.Health, error) {
	return &model.Health{Status: "ok"}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
