package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"encoding/json"
	"errors"
	"net/mail"
	"strings"
	"time"

	"github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/mdg-labs/escalite/services/api/graph/model"
	"github.com/mdg-labs/escalite/services/api/internal/audit"
	"github.com/mdg-labs/escalite/services/api/internal/auth"
	"github.com/mdg-labs/escalite/services/api/internal/authz"
	"github.com/mdg-labs/escalite/services/api/internal/db"
	"github.com/mdg-labs/escalite/services/api/internal/escalation"
	"github.com/mdg-labs/escalite/services/api/internal/gqlerr"
	"github.com/mdg-labs/escalite/services/api/internal/handlers"
	"github.com/mdg-labs/escalite/services/engine/escalationapi"
	"github.com/mdg-labs/escalite/services/engine/oncall"
	"github.com/mdg-labs/escalite/services/integrations"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginPayload, error) {
	email := strings.ToLower(strings.TrimSpace(input.Email))
	password := input.Password

	if email == "" {
		return nil, gqlerr.New(handlers.CodeValidation, "email is required")
	}
	if _, err := mail.ParseAddress(email); err != nil {
		return nil, gqlerr.New(handlers.CodeValidation, "email is invalid")
	}
	if password == "" {
		return nil, gqlerr.New(handlers.CodeValidation, "password is required")
	}

	queries := db.New(r.pool)
	requestMeta := audit.RequestMeta{}
	if req, ok := handlers.GraphQLRequestFromContext(ctx); ok {
		requestMeta = audit.RequestMetaFromHTTP(req)
	}
	requestMeta.Email = email

	user, err := queries.GetUserByEmailForAuth(ctx, email)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			r.recordFailedLogin(ctx, queries, nil, requestMeta)
			return nil, gqlerr.New(handlers.CodeUnauthenticated, invalidCredentialsMessage)
		}
		r.logger.Error("lookup user failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if !user.PasswordHash.Valid || user.PasswordHash.String == "" {
		r.recordFailedLogin(ctx, queries, &user, requestMeta)
		return nil, gqlerr.New(handlers.CodeUnauthenticated, invalidCredentialsMessage)
	}

	match, err := auth.VerifyPassword(password, user.PasswordHash.String)
	if err != nil {
		r.logger.Error("verify password failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}
	if !match {
		r.recordFailedLogin(ctx, queries, &user, requestMeta)
		return nil, gqlerr.New(handlers.CodeUnauthenticated, invalidCredentialsMessage)
	}

	sessionID := uuid.Must(uuid.NewV7())
	expiresAt := time.Now().UTC().Add(auth.DefaultSessionTTL)
	userAgent := ""
	if req, ok := handlers.GraphQLRequestFromContext(ctx); ok {
		userAgent = req.UserAgent()
	}

	_, err = queries.CreateSession(ctx, db.CreateSessionParams{
		ID:             sessionID,
		UserID:         user.ID,
		OrganizationID: user.OrganizationID,
		ExpiresAt:      pgtype.Timestamptz{Time: expiresAt, Valid: true},
		UserAgent:      pgtype.Text{String: userAgent, Valid: userAgent != ""},
	})
	if err != nil {
		r.logger.Error("create session failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if w, ok := handlers.GraphQLResponseWriterFromContext(ctx); ok {
		auth.SetSessionCookie(w, sessionID, expiresAt)
	}

	r.audit.Login(ctx, queries, user.OrganizationID, user.ID, requestMeta)

	return &model.LoginPayload{User: userFromDB(user)}, nil
}

// Setup is the resolver for the setup field.
func (r *mutationResolver) Setup(ctx context.Context, input model.SetupInput) (*model.SetupPayload, error) {
	orgName := strings.TrimSpace(input.OrganizationName)
	email := strings.ToLower(strings.TrimSpace(input.Email))
	password := input.Password

	if orgName == "" {
		return nil, gqlerr.New(handlers.CodeValidation, "organizationName is required")
	}
	if email == "" {
		return nil, gqlerr.New(handlers.CodeValidation, "email is required")
	}
	if _, err := mail.ParseAddress(email); err != nil {
		return nil, gqlerr.New(handlers.CodeValidation, "email is invalid")
	}
	if len(password) < minPasswordLength {
		return nil, gqlerr.New(handlers.CodeValidation, "password must be at least 8 characters")
	}

	queries := db.New(r.pool)

	userCount, err := queries.CountUsers(ctx)
	if err != nil {
		r.logger.Error("count users failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}
	if userCount > 0 {
		return nil, gqlerr.New(handlers.CodeForbidden, "setup is disabled after the first admin exists")
	}

	passwordHash, err := auth.HashPassword(password)
	if err != nil {
		r.logger.Error("hash password failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	orgID := uuid.Must(uuid.NewV7())
	userID := uuid.Must(uuid.NewV7())
	sessionID := uuid.Must(uuid.NewV7())
	expiresAt := time.Now().UTC().Add(auth.DefaultSessionTTL)
	userAgent := ""
	if req, ok := handlers.GraphQLRequestFromContext(ctx); ok {
		userAgent = req.UserAgent()
	}

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		r.logger.Error("begin transaction failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}
	defer func() {
		_ = tx.Rollback(ctx)
	}()

	txQueries := queries.WithTx(tx)

	_, err = txQueries.BootstrapOrganizationWithAdmin(ctx, db.BootstrapOrganizationWithAdminParams{
		OrgID:        orgID,
		OrgName:      orgName,
		UserID:       userID,
		Email:        email,
		PasswordHash: pgtype.Text{String: passwordHash, Valid: true},
	})
	if err != nil {
		r.logger.Error("bootstrap organization failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	_, err = txQueries.CreateSession(ctx, db.CreateSessionParams{
		ID:             sessionID,
		UserID:         userID,
		OrganizationID: orgID,
		ExpiresAt:      pgtype.Timestamptz{Time: expiresAt, Valid: true},
		UserAgent:      pgtype.Text{String: userAgent, Valid: userAgent != ""},
	})
	if err != nil {
		r.logger.Error("create session failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	requestMeta := audit.RequestMeta{}
	if req, ok := handlers.GraphQLRequestFromContext(ctx); ok {
		requestMeta = audit.RequestMetaFromHTTP(req)
	}
	r.audit.Login(ctx, txQueries, orgID, userID, requestMeta)

	if err := tx.Commit(ctx); err != nil {
		r.logger.Error("commit transaction failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if w, ok := handlers.GraphQLResponseWriterFromContext(ctx); ok {
		auth.SetSessionCookie(w, sessionID, expiresAt)
	}

	org, err := queries.GetOrganizationByID(ctx, orgID)
	if err != nil {
		r.logger.Error("load organization failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	user, err := queries.GetUserByID(ctx, db.GetUserByIDParams{
		ID:             userID,
		OrganizationID: orgID,
	})
	if err != nil {
		r.logger.Error("load user failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	return &model.SetupPayload{
		Organization: organizationFromDB(org),
		User:         userFromDB(user),
	}, nil
}

// CreateHeartbeatMonitor is the resolver for the createHeartbeatMonitor field.
func (r *mutationResolver) CreateHeartbeatMonitor(ctx context.Context, input model.CreateHeartbeatMonitorInput) (*model.HeartbeatMonitor, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	name := strings.TrimSpace(input.Name)
	if name == "" {
		return nil, gqlerr.New(handlers.CodeValidation, "name is required")
	}
	if err := validatePositiveDurationSeconds(input.IntervalSeconds, "intervalSeconds"); err != nil {
		return nil, err
	}
	if err := validatePositiveDurationSeconds(input.GraceSeconds, "graceSeconds"); err != nil {
		return nil, err
	}

	serviceID, err := parseUUIDField(input.ServiceID, "serviceId")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	if _, err := queries.GetServiceByID(ctx, db.GetServiceByIDParams{
		ID:             serviceID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "service not found")
		}
		r.logger.Error("load service failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	plaintext, tokenHash, prefix, err := auth.NewHeartbeatToken()
	if err != nil {
		r.logger.Error("generate heartbeat token failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	monitorID := uuid.Must(uuid.NewV7())
	monitor, err := queries.CreateHeartbeatMonitor(ctx, db.CreateHeartbeatMonitorParams{
		ID:              monitorID,
		OrganizationID:  sc.User.OrganizationID,
		ServiceID:       serviceID,
		Name:            name,
		IntervalSeconds: int32(input.IntervalSeconds),
		GraceSeconds:    int32(input.GraceSeconds),
		TokenHash:       tokenHash,
		Prefix:          prefix,
		Status:          "healthy",
	})
	if err != nil {
		if isHeartbeatDurationCheckViolation(err) {
			return nil, gqlerr.New(handlers.CodeValidation, "intervalSeconds and graceSeconds must be positive")
		}
		r.logger.Error("create heartbeat monitor failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	r.audit.HeartbeatMonitorCreated(ctx, queries, sc.User.OrganizationID, sc.User.ID, monitorID)

	return heartbeatMonitorFromDB(monitor, &plaintext), nil
}

// UpdateHeartbeatMonitor is the resolver for the updateHeartbeatMonitor field.
func (r *mutationResolver) UpdateHeartbeatMonitor(ctx context.Context, input model.UpdateHeartbeatMonitorInput) (*model.HeartbeatMonitor, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	name := strings.TrimSpace(input.Name)
	if name == "" {
		return nil, gqlerr.New(handlers.CodeValidation, "name is required")
	}
	if err := validatePositiveDurationSeconds(input.IntervalSeconds, "intervalSeconds"); err != nil {
		return nil, err
	}
	if err := validatePositiveDurationSeconds(input.GraceSeconds, "graceSeconds"); err != nil {
		return nil, err
	}

	monitorID, err := parseUUIDField(input.ID, "id")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	if _, err := queries.GetHeartbeatMonitorByID(ctx, db.GetHeartbeatMonitorByIDParams{
		ID:             monitorID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "heartbeat monitor not found")
		}
		r.logger.Error("load heartbeat monitor failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	monitor, err := queries.UpdateHeartbeatMonitor(ctx, db.UpdateHeartbeatMonitorParams{
		ID:              monitorID,
		OrganizationID:  sc.User.OrganizationID,
		Name:            name,
		IntervalSeconds: int32(input.IntervalSeconds),
		GraceSeconds:    int32(input.GraceSeconds),
	})
	if err != nil {
		if isHeartbeatDurationCheckViolation(err) {
			return nil, gqlerr.New(handlers.CodeValidation, "intervalSeconds and graceSeconds must be positive")
		}
		r.logger.Error("update heartbeat monitor failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	r.audit.HeartbeatMonitorUpdated(ctx, queries, sc.User.OrganizationID, sc.User.ID, monitorID)

	return heartbeatMonitorFromDB(monitor, nil), nil
}

// DeleteHeartbeatMonitor is the resolver for the deleteHeartbeatMonitor field.
func (r *mutationResolver) DeleteHeartbeatMonitor(ctx context.Context, id string) (bool, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return false, err
	}

	monitorID, err := parseUUIDField(id, "id")
	if err != nil {
		return false, err
	}

	queries := db.New(r.pool)
	if _, err := queries.GetHeartbeatMonitorByID(ctx, db.GetHeartbeatMonitorByIDParams{
		ID:             monitorID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, gqlerr.New(handlers.CodeNotFound, "heartbeat monitor not found")
		}
		r.logger.Error("load heartbeat monitor failed", "error", err)
		return false, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if err := queries.DeleteHeartbeatMonitor(ctx, db.DeleteHeartbeatMonitorParams{
		ID:             monitorID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		r.logger.Error("delete heartbeat monitor failed", "error", err)
		return false, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	r.audit.HeartbeatMonitorDeleted(ctx, queries, sc.User.OrganizationID, sc.User.ID, monitorID)
	return true, nil
}

// CreateEscalationPolicy is the resolver for the createEscalationPolicy field.
func (r *mutationResolver) CreateEscalationPolicy(ctx context.Context, input model.CreateEscalationPolicyInput) (*model.EscalationPolicy, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	name := strings.TrimSpace(input.Name)
	if name == "" {
		return nil, gqlerr.New(handlers.CodeValidation, "name is required")
	}
	if err := validateEscalationStepInputs(input.Steps); err != nil {
		return nil, err
	}

	serviceID, err := parseUUIDField(input.ServiceID, "serviceId")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	if _, err := queries.GetServiceByID(ctx, db.GetServiceByIDParams{
		ID:             serviceID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "service not found")
		}
		r.logger.Error("load service failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	policyID := uuid.Must(uuid.NewV7())

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		r.logger.Error("begin transaction failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}
	defer func() {
		_ = tx.Rollback(ctx)
	}()

	txQueries := queries.WithTx(tx)

	policy, err := txQueries.CreateEscalationPolicy(ctx, db.CreateEscalationPolicyParams{
		ID:             policyID,
		OrganizationID: sc.User.OrganizationID,
		ServiceID:      serviceID,
		Name:           name,
	})
	if err != nil {
		r.logger.Error("create escalation policy failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	steps, err := insertEscalationSteps(ctx, txQueries, sc.User.OrganizationID, policyID, input.Steps)
	if err != nil {
		return nil, err
	}

	r.audit.EscalationPolicyCreated(ctx, txQueries, sc.User.OrganizationID, sc.User.ID, policyID)

	if err := tx.Commit(ctx); err != nil {
		r.logger.Error("commit transaction failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	return escalationPolicyFromDB(policy, steps), nil
}

// UpdateEscalationPolicy is the resolver for the updateEscalationPolicy field.
func (r *mutationResolver) UpdateEscalationPolicy(ctx context.Context, input model.UpdateEscalationPolicyInput) (*model.EscalationPolicy, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	name := strings.TrimSpace(input.Name)
	if name == "" {
		return nil, gqlerr.New(handlers.CodeValidation, "name is required")
	}
	if err := validateEscalationStepInputs(input.Steps); err != nil {
		return nil, err
	}

	policyID, err := parseUUIDField(input.ID, "id")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	if _, err := queries.GetEscalationPolicyByID(ctx, db.GetEscalationPolicyByIDParams{
		ID:             policyID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "escalation policy not found")
		}
		r.logger.Error("load escalation policy failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		r.logger.Error("begin transaction failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}
	defer func() {
		_ = tx.Rollback(ctx)
	}()

	txQueries := queries.WithTx(tx)

	policy, err := txQueries.UpdateEscalationPolicy(ctx, db.UpdateEscalationPolicyParams{
		ID:             policyID,
		OrganizationID: sc.User.OrganizationID,
		Name:           name,
	})
	if err != nil {
		r.logger.Error("update escalation policy failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if err := txQueries.DeleteEscalationStepsByPolicyID(ctx, db.DeleteEscalationStepsByPolicyIDParams{
		EscalationPolicyID: policyID,
		OrganizationID:     sc.User.OrganizationID,
	}); err != nil {
		r.logger.Error("delete escalation steps failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	steps, err := insertEscalationSteps(ctx, txQueries, sc.User.OrganizationID, policyID, input.Steps)
	if err != nil {
		return nil, err
	}

	r.audit.EscalationPolicyUpdated(ctx, txQueries, sc.User.OrganizationID, sc.User.ID, policyID)

	if err := tx.Commit(ctx); err != nil {
		r.logger.Error("commit transaction failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	return escalationPolicyFromDB(policy, steps), nil
}

// DeleteEscalationPolicy is the resolver for the deleteEscalationPolicy field.
func (r *mutationResolver) DeleteEscalationPolicy(ctx context.Context, id string) (bool, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return false, err
	}

	policyID, err := parseUUIDField(id, "id")
	if err != nil {
		return false, err
	}

	queries := db.New(r.pool)
	if _, err := queries.GetEscalationPolicyByID(ctx, db.GetEscalationPolicyByIDParams{
		ID:             policyID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, gqlerr.New(handlers.CodeNotFound, "escalation policy not found")
		}
		r.logger.Error("load escalation policy failed", "error", err)
		return false, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if err := queries.DeleteEscalationPolicy(ctx, db.DeleteEscalationPolicyParams{
		ID:             policyID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		r.logger.Error("delete escalation policy failed", "error", err)
		return false, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	r.audit.EscalationPolicyDeleted(ctx, queries, sc.User.OrganizationID, sc.User.ID, policyID)
	return true, nil
}

// AcknowledgeAlert is the resolver for the acknowledgeAlert field.
func (r *mutationResolver) AcknowledgeAlert(ctx context.Context, id string) (*model.Alert, error) {
	sc, err := requireAuthSession(ctx)
	if err != nil {
		return nil, err
	}

	alertID, err := parseUUIDField(id, "id")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	alert, err := queries.GetAlertByID(ctx, db.GetAlertByIDParams{
		ID:             alertID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "alert not found")
		}
		r.logger.Error("load alert failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if alert.Status == "closed" {
		return nil, gqlerr.New(handlers.CodeValidation, "cannot acknowledge a closed alert")
	}
	if alert.Status == "acknowledged" {
		return nil, gqlerr.New(handlers.CodeValidation, "alert is already acknowledged")
	}

	service, err := queries.GetServiceByID(ctx, db.GetServiceByIDParams{
		ID:             alert.ServiceID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		r.logger.Error("load service failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if _, err := authz.CheckTeamAccess(ctx, queries, sc.User, service.TeamID); err != nil {
		if errors.Is(err, authz.ErrNotFound) || errors.Is(err, authz.ErrForbidden) {
			return nil, gqlerr.New(handlers.CodeForbidden, "access denied")
		}
		r.logger.Error("check team access failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	state, err := escalation.ParseState(alert.EscalationState)
	if err != nil {
		r.logger.Error("parse escalation state failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}
	state = escalation.ClearedTimerState(state)

	raw, err := escalation.MarshalState(state)
	if err != nil {
		r.logger.Error("marshal escalation state failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	acknowledged, err := queries.AcknowledgeAlert(ctx, db.AcknowledgeAlertParams{
		ID:                   alertID,
		OrganizationID:       sc.User.OrganizationID,
		EscalationState:      raw,
		AcknowledgedByUserID: pgtype.UUID{Bytes: sc.User.ID, Valid: true},
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeValidation, "cannot acknowledge alert in its current state")
		}
		r.logger.Error("acknowledge alert failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	return alertFromDB(acknowledged, &sc.User), nil
}

// CloseAlert is the resolver for the closeAlert field.
func (r *mutationResolver) CloseAlert(ctx context.Context, id string) (*model.Alert, error) {
	sc, err := requireAuthSession(ctx)
	if err != nil {
		return nil, err
	}

	alertID, err := parseUUIDField(id, "id")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	alert, err := queries.GetAlertByID(ctx, db.GetAlertByIDParams{
		ID:             alertID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "alert not found")
		}
		r.logger.Error("load alert failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if alert.Status == "closed" {
		return nil, gqlerr.New(handlers.CodeValidation, "alert is already closed")
	}

	service, err := queries.GetServiceByID(ctx, db.GetServiceByIDParams{
		ID:             alert.ServiceID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		r.logger.Error("load service failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if _, err := authz.CheckTeamAccess(ctx, queries, sc.User, service.TeamID); err != nil {
		if errors.Is(err, authz.ErrNotFound) || errors.Is(err, authz.ErrForbidden) {
			return nil, gqlerr.New(handlers.CodeForbidden, "access denied")
		}
		r.logger.Error("check team access failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	state, err := escalation.ParseState(alert.EscalationState)
	if err != nil {
		r.logger.Error("parse escalation state failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}
	state = escalation.ClearedTimerState(state)

	raw, err := escalation.MarshalState(state)
	if err != nil {
		r.logger.Error("marshal escalation state failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	closed, err := queries.CloseAlert(ctx, db.CloseAlertParams{
		ID:              alertID,
		OrganizationID:  sc.User.OrganizationID,
		EscalationState: raw,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeValidation, "cannot close alert in its current state")
		}
		r.logger.Error("close alert failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	var acknowledgedBy *db.User
	if closed.AcknowledgedByUserID.Valid {
		user, err := queries.GetUserByID(ctx, db.GetUserByIDParams{
			ID:             uuid.UUID(closed.AcknowledgedByUserID.Bytes),
			OrganizationID: sc.User.OrganizationID,
		})
		if err == nil {
			acknowledgedBy = &user
		}
	}

	return alertFromDB(closed, acknowledgedBy), nil
}

// SnoozeAlert is the resolver for the snoozeAlert field.
func (r *mutationResolver) SnoozeAlert(ctx context.Context, id string, durationMinutes int) (*model.Alert, error) {
	sc, err := requireAuthSession(ctx)
	if err != nil {
		return nil, err
	}

	alertID, err := parseUUIDField(id, "id")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	alert, service, err := r.loadAlertWithTeamAccess(ctx, queries, sc, alertID)
	if err != nil {
		return nil, err
	}
	_ = service

	if err := escalationapi.SnoozeAlert(
		ctx,
		r.pool,
		r.jobs,
		alertID,
		sc.User.OrganizationID,
		int32(durationMinutes),
	); err != nil {
		if isEscalationValidationError(err) {
			return nil, gqlerr.New(handlers.CodeValidation, err.Error())
		}
		r.logger.Error("snooze alert failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	snoozed, err := queries.GetAlertByID(ctx, db.GetAlertByIDParams{
		ID:             alertID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		r.logger.Error("reload snoozed alert failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	state, err := escalation.ParseState(snoozed.EscalationState)
	if err != nil {
		r.logger.Error("parse escalation state failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}
	if state.NextEscalationAt != nil {
		r.audit.AlertEscalationSnoozed(
			ctx,
			queries,
			sc.User.OrganizationID,
			sc.User.ID,
			alert.ID,
			int32(durationMinutes),
			state.NextEscalationAt.UTC().Format(time.RFC3339),
		)
	}

	return alertFromDB(snoozed, nil), nil
}

// ReEscalateAlert is the resolver for the reEscalateAlert field.
func (r *mutationResolver) ReEscalateAlert(ctx context.Context, id string) (*model.Alert, error) {
	sc, err := requireAuthSession(ctx)
	if err != nil {
		return nil, err
	}

	alertID, err := parseUUIDField(id, "id")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	alert, service, err := r.loadAlertWithTeamAccess(ctx, queries, sc, alertID)
	if err != nil {
		return nil, err
	}
	_ = service

	if err := escalationapi.ReEscalateAlert(
		ctx,
		r.pool,
		r.jobs,
		alertID,
		sc.User.OrganizationID,
	); err != nil {
		if isEscalationValidationError(err) {
			return nil, gqlerr.New(handlers.CodeValidation, err.Error())
		}
		r.logger.Error("re-escalate alert failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	reEscalated, err := queries.GetAlertByID(ctx, db.GetAlertByIDParams{
		ID:             alertID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		r.logger.Error("reload re-escalated alert failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	r.audit.AlertReEscalated(ctx, queries, sc.User.OrganizationID, sc.User.ID, alert.ID)

	return alertFromDB(reEscalated, nil), nil
}

// CreateSchedule is the resolver for the createSchedule field.
func (r *mutationResolver) CreateSchedule(ctx context.Context, input model.CreateScheduleInput) (*model.Schedule, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	name := strings.TrimSpace(input.Name)
	if name == "" {
		return nil, gqlerr.New(handlers.CodeValidation, "name is required")
	}
	if err := validateTimezone(input.Timezone); err != nil {
		return nil, err
	}

	teamID, err := parseUUIDField(input.TeamID, "teamId")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	if _, err := queries.GetTeamByID(ctx, db.GetTeamByIDParams{
		ID:             teamID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "team not found")
		}
		r.logger.Error("load team failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	scheduleID := uuid.Must(uuid.NewV7())
	schedule, err := queries.CreateSchedule(ctx, db.CreateScheduleParams{
		ID:             scheduleID,
		OrganizationID: sc.User.OrganizationID,
		TeamID:         teamID,
		Name:           name,
		Timezone:       strings.TrimSpace(input.Timezone),
	})
	if err != nil {
		if isTimezoneCheckViolation(err) {
			return nil, gqlerr.New(handlers.CodeValidation, "timezone must be a valid IANA timezone")
		}
		r.logger.Error("create schedule failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	return scheduleFromDB(schedule, nil), nil
}

// UpdateSchedule is the resolver for the updateSchedule field.
func (r *mutationResolver) UpdateSchedule(ctx context.Context, input model.UpdateScheduleInput) (*model.Schedule, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	name := strings.TrimSpace(input.Name)
	if name == "" {
		return nil, gqlerr.New(handlers.CodeValidation, "name is required")
	}
	if err := validateTimezone(input.Timezone); err != nil {
		return nil, err
	}

	scheduleID, err := parseUUIDField(input.ID, "id")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	if _, err := queries.GetScheduleByID(ctx, db.GetScheduleByIDParams{
		ID:             scheduleID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "schedule not found")
		}
		r.logger.Error("load schedule failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	schedule, err := queries.UpdateSchedule(ctx, db.UpdateScheduleParams{
		ID:             scheduleID,
		OrganizationID: sc.User.OrganizationID,
		Name:           name,
		Timezone:       strings.TrimSpace(input.Timezone),
	})
	if err != nil {
		if isTimezoneCheckViolation(err) {
			return nil, gqlerr.New(handlers.CodeValidation, "timezone must be a valid IANA timezone")
		}
		r.logger.Error("update schedule failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	rotations, err := queries.ListRotationsByScheduleID(ctx, db.ListRotationsByScheduleIDParams{
		ScheduleID:     scheduleID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		r.logger.Error("list rotations failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	return scheduleFromDB(schedule, rotations), nil
}

// DeleteSchedule is the resolver for the deleteSchedule field.
func (r *mutationResolver) DeleteSchedule(ctx context.Context, id string) (bool, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return false, err
	}

	scheduleID, err := parseUUIDField(id, "id")
	if err != nil {
		return false, err
	}

	queries := db.New(r.pool)
	if _, err := queries.GetScheduleByID(ctx, db.GetScheduleByIDParams{
		ID:             scheduleID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, gqlerr.New(handlers.CodeNotFound, "schedule not found")
		}
		r.logger.Error("load schedule failed", "error", err)
		return false, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if err := queries.DeleteSchedule(ctx, db.DeleteScheduleParams{
		ID:             scheduleID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		r.logger.Error("delete schedule failed", "error", err)
		return false, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	return true, nil
}

// CreateRotation is the resolver for the createRotation field.
func (r *mutationResolver) CreateRotation(ctx context.Context, input model.CreateRotationInput) (*model.Rotation, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	name := strings.TrimSpace(input.Name)
	if name == "" {
		return nil, gqlerr.New(handlers.CodeValidation, "name is required")
	}
	if err := validateRotationLayer(input.Layer); err != nil {
		return nil, err
	}
	if err := validateRRule(input.Rrule); err != nil {
		return nil, err
	}

	scheduleID, err := parseUUIDField(input.ScheduleID, "scheduleId")
	if err != nil {
		return nil, err
	}

	participantIDs, err := parseParticipantIDs(input.ParticipantIds)
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	if _, err := queries.GetScheduleByID(ctx, db.GetScheduleByIDParams{
		ID:             scheduleID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "schedule not found")
		}
		r.logger.Error("load schedule failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if err := ensureParticipantsExist(ctx, queries, sc.User.OrganizationID, participantIDs); err != nil {
		return nil, err
	}

	participantsJSON, err := encodeParticipantIDs(participantIDs)
	if err != nil {
		r.logger.Error("encode participants failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	rotation, err := queries.CreateRotation(ctx, db.CreateRotationParams{
		ID:             uuid.Must(uuid.NewV7()),
		ScheduleID:     scheduleID,
		OrganizationID: sc.User.OrganizationID,
		Name:           name,
		Layer:          int32(input.Layer),
		Rrule:          strings.TrimSpace(input.Rrule),
		Participants:   participantsJSON,
	})
	if err != nil {
		if isRotationLayerConflict(err) {
			return nil, gqlerr.New(handlers.CodeValidation, "layer already exists on this schedule")
		}
		r.logger.Error("create rotation failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	gqlRotation, err := rotationFromDB(rotation)
	if err != nil {
		r.logger.Error("decode rotation participants failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}
	return gqlRotation, nil
}

// UpdateRotation is the resolver for the updateRotation field.
func (r *mutationResolver) UpdateRotation(ctx context.Context, input model.UpdateRotationInput) (*model.Rotation, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	name := strings.TrimSpace(input.Name)
	if name == "" {
		return nil, gqlerr.New(handlers.CodeValidation, "name is required")
	}
	if err := validateRotationLayer(input.Layer); err != nil {
		return nil, err
	}
	if err := validateRRule(input.Rrule); err != nil {
		return nil, err
	}

	rotationID, err := parseUUIDField(input.ID, "id")
	if err != nil {
		return nil, err
	}

	participantIDs, err := parseParticipantIDs(input.ParticipantIds)
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	if _, err := queries.GetRotationByID(ctx, db.GetRotationByIDParams{
		ID:             rotationID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "rotation not found")
		}
		r.logger.Error("load rotation failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if err := ensureParticipantsExist(ctx, queries, sc.User.OrganizationID, participantIDs); err != nil {
		return nil, err
	}

	participantsJSON, err := encodeParticipantIDs(participantIDs)
	if err != nil {
		r.logger.Error("encode participants failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	rotation, err := queries.UpdateRotation(ctx, db.UpdateRotationParams{
		ID:             rotationID,
		OrganizationID: sc.User.OrganizationID,
		Name:           name,
		Layer:          int32(input.Layer),
		Rrule:          strings.TrimSpace(input.Rrule),
		Participants:   participantsJSON,
	})
	if err != nil {
		if isRotationLayerConflict(err) {
			return nil, gqlerr.New(handlers.CodeValidation, "layer already exists on this schedule")
		}
		r.logger.Error("update rotation failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	gqlRotation, err := rotationFromDB(rotation)
	if err != nil {
		r.logger.Error("decode rotation participants failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}
	return gqlRotation, nil
}

// DeleteRotation is the resolver for the deleteRotation field.
func (r *mutationResolver) DeleteRotation(ctx context.Context, id string) (bool, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return false, err
	}

	rotationID, err := parseUUIDField(id, "id")
	if err != nil {
		return false, err
	}

	queries := db.New(r.pool)
	if _, err := queries.GetRotationByID(ctx, db.GetRotationByIDParams{
		ID:             rotationID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, gqlerr.New(handlers.CodeNotFound, "rotation not found")
		}
		r.logger.Error("load rotation failed", "error", err)
		return false, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if err := queries.DeleteRotation(ctx, db.DeleteRotationParams{
		ID:             rotationID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		r.logger.Error("delete rotation failed", "error", err)
		return false, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	return true, nil
}

// CreateOverride is the resolver for the createOverride field.
func (r *mutationResolver) CreateOverride(ctx context.Context, input model.CreateOverrideInput) (*model.Override, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	scheduleID, err := parseUUIDField(input.ScheduleID, "scheduleId")
	if err != nil {
		return nil, err
	}
	rotationID, err := parseUUIDField(input.RotationID, "rotationId")
	if err != nil {
		return nil, err
	}
	userID, err := parseUUIDField(input.UserID, "userId")
	if err != nil {
		return nil, err
	}

	startsAt := input.StartsAt.UTC()
	endsAt := input.EndsAt.UTC()
	if !endsAt.After(startsAt) {
		return nil, gqlerr.New(handlers.CodeValidation, "endsAt must be after startsAt")
	}

	queries := db.New(r.pool)

	schedule, err := queries.GetScheduleByID(ctx, db.GetScheduleByIDParams{
		ID:             scheduleID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "schedule not found")
		}
		r.logger.Error("load schedule failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	rotation, err := queries.GetRotationByID(ctx, db.GetRotationByIDParams{
		ID:             rotationID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "rotation not found")
		}
		r.logger.Error("load rotation failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}
	if rotation.ScheduleID != scheduleID {
		return nil, gqlerr.New(handlers.CodeValidation, "rotation does not belong to schedule")
	}

	if _, err := queries.GetUserByID(ctx, db.GetUserByIDParams{
		ID:             userID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeValidation, "user not found")
		}
		r.logger.Error("load override user failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	replacedUserID := computeReplacedUserID(schedule.Timezone, rotation, startsAt)

	overrideID := uuid.Must(uuid.NewV7())
	override, err := queries.CreateOverride(ctx, db.CreateOverrideParams{
		ID:              overrideID,
		ScheduleID:      scheduleID,
		RotationID:      rotationID,
		OrganizationID:  sc.User.OrganizationID,
		UserID:          userID,
		ReplacedUserID:  replacedUserID,
		StartsAt:        pgtype.Timestamptz{Time: startsAt, Valid: true},
		EndsAt:          pgtype.Timestamptz{Time: endsAt, Valid: true},
		CreatedByUserID: sc.User.ID,
	})
	if err != nil {
		r.logger.Error("create override failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	auditMeta := map[string]any{
		"schedule_id": scheduleID.String(),
		"rotation_id": rotationID.String(),
		"user_id":     userID.String(),
		"starts_at":   startsAt.Format(time.RFC3339),
		"ends_at":     endsAt.Format(time.RFC3339),
	}
	if replacedUserID.Valid {
		auditMeta["replaced_user_id"] = uuid.UUID(replacedUserID.Bytes).String()
	}
	r.audit.OverrideCreated(ctx, queries, sc.User.OrganizationID, sc.User.ID, overrideID, auditMeta)

	return overrideFromDB(override), nil
}

// DeleteOverride is the resolver for the deleteOverride field.
func (r *mutationResolver) DeleteOverride(ctx context.Context, id string) (bool, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return false, err
	}

	overrideID, err := parseUUIDField(id, "id")
	if err != nil {
		return false, err
	}

	queries := db.New(r.pool)
	if _, err := queries.GetOverrideByID(ctx, db.GetOverrideByIDParams{
		ID:             overrideID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, gqlerr.New(handlers.CodeNotFound, "override not found")
		}
		r.logger.Error("load override failed", "error", err)
		return false, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if _, err := queries.SoftDeleteOverride(ctx, db.SoftDeleteOverrideParams{
		ID:             overrideID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, gqlerr.New(handlers.CodeNotFound, "override not found")
		}
		r.logger.Error("delete override failed", "error", err)
		return false, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	r.audit.OverrideDeleted(ctx, queries, sc.User.OrganizationID, sc.User.ID, overrideID)
	return true, nil
}

// SaveUserContactMethod is the resolver for the saveUserContactMethod field.
func (r *mutationResolver) SaveUserContactMethod(ctx context.Context, input model.SaveUserContactMethodInput) (*model.UserContactMethod, error) {
	sc, err := requireAuthSession(ctx)
	if err != nil {
		return nil, err
	}

	if err := validateNotificationChannelConfig(input.Channel, input.Config); err != nil {
		return nil, gqlerr.New(handlers.CodeValidation, err.Error())
	}

	config := input.Config
	if config == nil {
		config = map[string]any{}
	}

	rawConfig, err := json.Marshal(config)
	if err != nil {
		return nil, gqlerr.New(handlers.CodeValidation, "config must be a JSON object")
	}

	queries := db.New(r.pool)
	method, err := queries.UpsertUserContactMethod(ctx, db.UpsertUserContactMethodParams{
		ID:             uuid.Must(uuid.NewV7()),
		OrganizationID: sc.User.OrganizationID,
		UserID:         sc.User.ID,
		Channel:        strings.TrimSpace(input.Channel),
		Config:         rawConfig,
	})
	if err != nil {
		r.logger.Error("save user contact method failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	return userContactMethodFromDB(method)
}

// SaveNotificationRule is the resolver for the saveNotificationRule field.
func (r *mutationResolver) SaveNotificationRule(ctx context.Context, input model.SaveNotificationRuleInput) (*model.UserNotificationRule, error) {
	sc, err := requireAuthSession(ctx)
	if err != nil {
		return nil, err
	}

	priority, err := alertPriorityToDB(input.Priority)
	if err != nil {
		return nil, gqlerr.New(handlers.CodeValidation, err.Error())
	}

	steps, err := validateNotificationRuleSteps(input.Steps)
	if err != nil {
		return nil, gqlerr.New(handlers.CodeValidation, err.Error())
	}

	rawSteps, err := notificationRuleStepsToRaw(steps)
	if err != nil {
		return nil, gqlerr.New(handlers.CodeValidation, "steps must be a JSON array")
	}

	queries := db.New(r.pool)
	rule, err := queries.UpsertUserNotificationRule(ctx, db.UpsertUserNotificationRuleParams{
		ID:             uuid.Must(uuid.NewV7()),
		OrganizationID: sc.User.OrganizationID,
		UserID:         sc.User.ID,
		Priority:       priority,
		Steps:          rawSteps,
	})
	if err != nil {
		r.logger.Error("save notification rule failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	return userNotificationRuleFromDB(rule)
}

// DeleteNotificationRule is the resolver for the deleteNotificationRule field.
func (r *mutationResolver) DeleteNotificationRule(ctx context.Context, priority model.AlertPriority) (bool, error) {
	sc, err := requireAuthSession(ctx)
	if err != nil {
		return false, err
	}

	priorityDB, err := alertPriorityToDB(priority)
	if err != nil {
		return false, gqlerr.New(handlers.CodeValidation, err.Error())
	}

	queries := db.New(r.pool)
	if err := queries.DeleteUserNotificationRule(ctx, db.DeleteUserNotificationRuleParams{
		OrganizationID: sc.User.OrganizationID,
		UserID:         sc.User.ID,
		Priority:       priorityDB,
	}); err != nil {
		r.logger.Error("delete notification rule failed", "error", err)
		return false, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	return true, nil
}

// SaveSlackSettings is the resolver for the saveSlackSettings field.
func (r *mutationResolver) SaveSlackSettings(ctx context.Context, input model.SaveSlackSettingsInput) (*model.SlackSettings, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}
	if r.secrets == nil {
		return nil, gqlerr.New(handlers.CodeInternal, "encryption is not configured")
	}

	botToken := strings.TrimSpace(input.BotToken)
	if err := validateSlackBotToken(botToken); err != nil {
		return nil, gqlerr.New(handlers.CodeValidation, err.Error())
	}

	params, err := encryptSlackBotToken(r.secrets, botToken)
	if err != nil {
		r.logger.Error("encrypt slack bot token failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}
	params.OrganizationID = sc.User.OrganizationID

	queries := db.New(r.pool)
	settings, err := queries.UpsertOrganizationSlackSettings(ctx, params)
	if err != nil {
		r.logger.Error("save slack settings failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	return slackSettingsFromDB(&settings), nil
}

// CreateIntegrationKey is the resolver for the createIntegrationKey field.
func (r *mutationResolver) CreateIntegrationKey(ctx context.Context, input model.CreateIntegrationKeyInput) (*model.IntegrationKey, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	pluginName := strings.TrimSpace(input.PluginName)
	if pluginName == "" {
		return nil, gqlerr.New(handlers.CodeValidation, "pluginName is required")
	}

	serviceID, err := parseUUIDField(input.ServiceID, "serviceId")
	if err != nil {
		return nil, err
	}

	configBytes, err := json.Marshal(input.Config)
	if err != nil {
		return nil, gqlerr.New(handlers.CodeValidation, "config must be a JSON object")
	}
	if err := integrations.ValidateConfig(pluginName, configBytes); err != nil {
		return nil, gqlerr.New(handlers.CodeValidation, "invalid integration config")
	}

	queries := db.New(r.pool)
	if _, err := queries.GetServiceByID(ctx, db.GetServiceByIDParams{
		ID:             serviceID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "service not found")
		}
		r.logger.Error("load service failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	plaintext, tokenHash, prefix, err := auth.NewIntegrationKeyToken()
	if err != nil {
		r.logger.Error("generate integration key token failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	keyID := uuid.Must(uuid.NewV7())
	key, err := queries.CreateIntegrationKey(ctx, db.CreateIntegrationKeyParams{
		ID:             keyID,
		ServiceID:      serviceID,
		OrganizationID: sc.User.OrganizationID,
		Token:          tokenHash,
		Prefix:         prefix,
		PluginName:     pluginName,
		Config:         configBytes,
	})
	if err != nil {
		r.logger.Error("create integration key failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	r.audit.IntegrationKeyCreated(ctx, queries, sc.User.OrganizationID, sc.User.ID, keyID)

	return integrationKeyFromDB(key, &plaintext), nil
}

// RevokeIntegrationKey is the resolver for the revokeIntegrationKey field.
func (r *mutationResolver) RevokeIntegrationKey(ctx context.Context, id string) (*model.IntegrationKey, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	keyID, err := parseUUIDField(id, "id")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	key, err := queries.RevokeIntegrationKey(ctx, db.RevokeIntegrationKeyParams{
		ID:             keyID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "integration key not found")
		}
		r.logger.Error("revoke integration key failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	r.audit.IntegrationKeyRevoked(ctx, queries, sc.User.OrganizationID, sc.User.ID, keyID)
	return integrationKeyFromDB(key, nil), nil
}

// RotateIntegrationKey is the resolver for the rotateIntegrationKey field.
func (r *mutationResolver) RotateIntegrationKey(ctx context.Context, id string) (*model.IntegrationKey, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	keyID, err := parseUUIDField(id, "id")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	existing, err := queries.GetIntegrationKeyByID(ctx, db.GetIntegrationKeyByIDParams{
		ID:             keyID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "integration key not found")
		}
		r.logger.Error("load integration key failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}
	if existing.RevokedAt.Valid {
		return nil, gqlerr.New(handlers.CodeValidation, "integration key is already revoked")
	}

	plaintext, tokenHash, prefix, err := auth.NewIntegrationKeyToken()
	if err != nil {
		r.logger.Error("generate integration key token failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	newKeyID := uuid.Must(uuid.NewV7())
	newKey, err := queries.CreateIntegrationKey(ctx, db.CreateIntegrationKeyParams{
		ID:             newKeyID,
		ServiceID:      existing.ServiceID,
		OrganizationID: sc.User.OrganizationID,
		Token:          tokenHash,
		Prefix:         prefix,
		PluginName:     existing.PluginName,
		Config:         existing.Config,
	})
	if err != nil {
		r.logger.Error("create rotated integration key failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	if _, err := queries.RevokeIntegrationKey(ctx, db.RevokeIntegrationKeyParams{
		ID:             keyID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		r.logger.Error("revoke rotated integration key failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	r.audit.IntegrationKeyCreated(ctx, queries, sc.User.OrganizationID, sc.User.ID, newKeyID)
	r.audit.IntegrationKeyRevoked(ctx, queries, sc.User.OrganizationID, sc.User.ID, keyID)

	return integrationKeyFromDB(newKey, &plaintext), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	sc, ok := auth.SessionFromContext(ctx)
	if !ok {
		return nil, nil
	}
	return userFromDB(sc.User), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.Health, error) {
	return &model.Health{Status: "ok"}, nil
}

// EscalationPolicy is the resolver for the escalationPolicy field.
func (r *queryResolver) EscalationPolicy(ctx context.Context, id string) (*model.EscalationPolicy, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	policyID, err := parseUUIDField(id, "id")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	policy, err := queries.GetEscalationPolicyByID(ctx, db.GetEscalationPolicyByIDParams{
		ID:             policyID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		r.logger.Error("load escalation policy failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	steps, err := queries.ListEscalationStepsByPolicyID(ctx, db.ListEscalationStepsByPolicyIDParams{
		EscalationPolicyID: policyID,
		OrganizationID:     sc.User.OrganizationID,
	})
	if err != nil {
		r.logger.Error("list escalation steps failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	return escalationPolicyFromDB(policy, steps), nil
}

// EscalationPolicies is the resolver for the escalationPolicies field.
func (r *queryResolver) EscalationPolicies(ctx context.Context, serviceID string) ([]*model.EscalationPolicy, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	svcID, err := parseUUIDField(serviceID, "serviceId")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	if _, err := queries.GetServiceByID(ctx, db.GetServiceByIDParams{
		ID:             svcID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "service not found")
		}
		r.logger.Error("load service failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	policies, err := queries.ListEscalationPoliciesByServiceID(ctx, db.ListEscalationPoliciesByServiceIDParams{
		ServiceID:      svcID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		r.logger.Error("list escalation policies failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	result := make([]*model.EscalationPolicy, 0, len(policies))
	for _, policy := range policies {
		steps, err := queries.ListEscalationStepsByPolicyID(ctx, db.ListEscalationStepsByPolicyIDParams{
			EscalationPolicyID: policy.ID,
			OrganizationID:     sc.User.OrganizationID,
		})
		if err != nil {
			r.logger.Error("list escalation steps failed", "error", err)
			return nil, gqlerr.New(handlers.CodeInternal, "internal error")
		}
		result = append(result, escalationPolicyFromDB(policy, steps))
	}

	return result, nil
}

// HeartbeatMonitor is the resolver for the heartbeatMonitor field.
func (r *queryResolver) HeartbeatMonitor(ctx context.Context, id string) (*model.HeartbeatMonitor, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	monitorID, err := parseUUIDField(id, "id")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	monitor, err := queries.GetHeartbeatMonitorByID(ctx, db.GetHeartbeatMonitorByIDParams{
		ID:             monitorID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		r.logger.Error("load heartbeat monitor failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	return heartbeatMonitorFromDB(monitor, nil), nil
}

// HeartbeatMonitors is the resolver for the heartbeatMonitors field.
func (r *queryResolver) HeartbeatMonitors(ctx context.Context, serviceID string) ([]*model.HeartbeatMonitor, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	svcID, err := parseUUIDField(serviceID, "serviceId")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	if _, err := queries.GetServiceByID(ctx, db.GetServiceByIDParams{
		ID:             svcID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "service not found")
		}
		r.logger.Error("load service failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	monitors, err := queries.ListHeartbeatMonitorsByServiceID(ctx, db.ListHeartbeatMonitorsByServiceIDParams{
		ServiceID:      svcID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		r.logger.Error("list heartbeat monitors failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	result := make([]*model.HeartbeatMonitor, 0, len(monitors))
	for _, monitor := range monitors {
		result = append(result, heartbeatMonitorFromDB(monitor, nil))
	}

	return result, nil
}

// Schedule is the resolver for the schedule field.
func (r *queryResolver) Schedule(ctx context.Context, id string) (*model.Schedule, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	scheduleID, err := parseUUIDField(id, "id")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	schedule, err := queries.GetScheduleByID(ctx, db.GetScheduleByIDParams{
		ID:             scheduleID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		r.logger.Error("load schedule failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	rotations, err := queries.ListRotationsByScheduleID(ctx, db.ListRotationsByScheduleIDParams{
		ScheduleID:     scheduleID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		r.logger.Error("list rotations failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	return scheduleFromDB(schedule, rotations), nil
}

// Schedules is the resolver for the schedules field.
func (r *queryResolver) Schedules(ctx context.Context, teamID string) ([]*model.Schedule, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	teamUUID, err := parseUUIDField(teamID, "teamId")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	if _, err := queries.GetTeamByID(ctx, db.GetTeamByIDParams{
		ID:             teamUUID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "team not found")
		}
		r.logger.Error("load team failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	schedules, err := queries.ListSchedulesByTeamID(ctx, db.ListSchedulesByTeamIDParams{
		TeamID:         teamUUID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		r.logger.Error("list schedules failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	result := make([]*model.Schedule, 0, len(schedules))
	for _, schedule := range schedules {
		rotations, err := queries.ListRotationsByScheduleID(ctx, db.ListRotationsByScheduleIDParams{
			ScheduleID:     schedule.ID,
			OrganizationID: sc.User.OrganizationID,
		})
		if err != nil {
			r.logger.Error("list rotations failed", "error", err)
			return nil, gqlerr.New(handlers.CodeInternal, "internal error")
		}
		result = append(result, scheduleFromDB(schedule, rotations))
	}

	return result, nil
}

// OnCallNow is the resolver for the onCallNow field.
func (r *queryResolver) OnCallNow(ctx context.Context, scheduleID string, at *time.Time) (*model.OnCallNow, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	scheduleUUID, err := parseUUIDField(scheduleID, "scheduleId")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	schedule, err := queries.GetScheduleByID(ctx, db.GetScheduleByIDParams{
		ID:             scheduleUUID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		r.logger.Error("load schedule failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	loc, err := time.LoadLocation(schedule.Timezone)
	if err != nil {
		r.logger.Error("load schedule timezone failed", "error", err, "timezone", schedule.Timezone)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	evalAt := time.Now().UTC()
	if at != nil {
		evalAt = at.UTC()
	}

	rotations, err := queries.ListRotationsByScheduleID(ctx, db.ListRotationsByScheduleIDParams{
		ScheduleID:     scheduleUUID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		r.logger.Error("list rotations failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	activeOverrides, err := queries.ListActiveOverridesByScheduleAt(ctx, db.ListActiveOverridesByScheduleAtParams{
		ScheduleID:     scheduleUUID,
		OrganizationID: sc.User.OrganizationID,
		StartsAt:       pgtype.Timestamptz{Time: evalAt, Valid: true},
	})
	if err != nil {
		r.logger.Error("list active overrides failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}
	overrideByRotation := overridesByRotation(activeOverrides)

	layers := make([]*model.OnCallLayer, 0, len(rotations))
	for _, rotation := range rotations {
		if override, ok := overrideByRotation[rotation.ID]; ok {
			layers = append(layers, &model.OnCallLayer{
				Layer:      int(rotation.Layer),
				RotationID: rotation.ID.String(),
				UserID:     override.UserID.String(),
			})
			continue
		}

		participantIDs, err := decodeParticipantIDs(rotation.Participants)
		if err != nil {
			r.logger.Error("decode rotation participants failed", "error", err, "rotationId", rotation.ID)
			return nil, gqlerr.New(handlers.CodeInternal, "internal error")
		}

		userID, err := oncall.CurrentOnCallUser(
			rotation.Rrule,
			timeFromDB(rotation.CreatedAt),
			loc,
			evalAt,
			participantIDs,
		)
		if err != nil {
			if oncall.IsNoActiveShift(err) {
				continue
			}
			r.logger.Error("compute on-call user failed", "error", err, "rotationId", rotation.ID)
			return nil, gqlerr.New(handlers.CodeInternal, "internal error")
		}

		layers = append(layers, &model.OnCallLayer{
			Layer:      int(rotation.Layer),
			RotationID: rotation.ID.String(),
			UserID:     userID,
		})
	}

	return &model.OnCallNow{
		ScheduleID: schedule.ID.String(),
		ComputedAt: evalAt,
		Layers:     layers,
	}, nil
}

// Overrides is the resolver for the overrides field.
func (r *queryResolver) Overrides(ctx context.Context, scheduleID string) ([]*model.Override, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	scheduleUUID, err := parseUUIDField(scheduleID, "scheduleId")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	if _, err := queries.GetScheduleByID(ctx, db.GetScheduleByIDParams{
		ID:             scheduleUUID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "schedule not found")
		}
		r.logger.Error("load schedule failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	overrides, err := queries.ListActiveOverridesByScheduleID(ctx, db.ListActiveOverridesByScheduleIDParams{
		ScheduleID:     scheduleUUID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		r.logger.Error("list overrides failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	result := make([]*model.Override, 0, len(overrides))
	for _, override := range overrides {
		result = append(result, overrideFromDB(override))
	}
	return result, nil
}

// NotificationChannels is the resolver for the notificationChannels field.
func (r *queryResolver) NotificationChannels(ctx context.Context) ([]*model.NotificationChannelDefinition, error) {
	if _, err := requireAuthSession(ctx); err != nil {
		return nil, err
	}
	return notificationChannelDefinitions(), nil
}

// NotificationRules is the resolver for the notificationRules field.
func (r *queryResolver) NotificationRules(ctx context.Context) ([]*model.UserNotificationRule, error) {
	sc, err := requireAuthSession(ctx)
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	rules, err := queries.ListUserNotificationRules(ctx, db.ListUserNotificationRulesParams{
		OrganizationID: sc.User.OrganizationID,
		UserID:         sc.User.ID,
	})
	if err != nil {
		r.logger.Error("list notification rules failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	out := make([]*model.UserNotificationRule, 0, len(rules))
	for _, rule := range rules {
		gqlRule, err := userNotificationRuleFromDB(rule)
		if err != nil {
			r.logger.Error("map notification rule failed", "error", err)
			return nil, gqlerr.New(handlers.CodeInternal, "internal error")
		}
		out = append(out, gqlRule)
	}
	return out, nil
}

// SlackSettings is the resolver for the slackSettings field.
func (r *queryResolver) SlackSettings(ctx context.Context) (*model.SlackSettings, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	settings, err := queries.GetOrganizationSlackSettings(ctx, sc.User.OrganizationID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return slackSettingsFromDB(nil), nil
		}
		r.logger.Error("load slack settings failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	return slackSettingsFromDB(&settings), nil
}

// IntegrationKeys is the resolver for the integrationKeys field.
func (r *queryResolver) IntegrationKeys(ctx context.Context, serviceID string) ([]*model.IntegrationKey, error) {
	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	svcID, err := parseUUIDField(serviceID, "serviceId")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	if _, err := queries.GetServiceByID(ctx, db.GetServiceByIDParams{
		ID:             svcID,
		OrganizationID: sc.User.OrganizationID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, gqlerr.New(handlers.CodeNotFound, "service not found")
		}
		r.logger.Error("load service failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	keys, err := queries.ListIntegrationKeysByServiceID(ctx, db.ListIntegrationKeysByServiceIDParams{
		ServiceID:      svcID,
		OrganizationID: sc.User.OrganizationID,
	})
	if err != nil {
		r.logger.Error("list integration keys failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	result := make([]*model.IntegrationKey, 0, len(keys))
	for _, key := range keys {
		result = append(result, integrationKeyFromDB(key, nil))
	}

	return result, nil
}

// AlertUpdated is the resolver for the alertUpdated field.
func (r *subscriptionResolver) AlertUpdated(ctx context.Context, orgID string) (<-chan *model.Alert, error) {
	_, orgUUID, err := requireOrgSubscriptionAccess(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return r.streamAlertUpdates(ctx, orgUUID)
}

// OnCallUpdated is the resolver for the onCallUpdated field.
func (r *subscriptionResolver) OnCallUpdated(ctx context.Context, orgID string) (<-chan *model.OnCallUpdatedEvent, error) {
	_, orgUUID, err := requireOrgSubscriptionAccess(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return r.streamOnCallUpdates(ctx, orgUUID)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
