package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"

	"github.com/mdg-labs/escalite/services/api/graph/model"
	"github.com/mdg-labs/escalite/services/api/internal/db"
	"github.com/mdg-labs/escalite/services/api/internal/gqlerr"
	"github.com/mdg-labs/escalite/services/api/internal/handlers"
)

// ActiveMaintenanceWindows is the resolver for the activeMaintenanceWindows field on Service.
func (r *serviceResolver) ActiveMaintenanceWindows(ctx context.Context, obj *model.Service) ([]*model.MaintenanceWindow, error) {
	if obj == nil {
		return nil, nil
	}

	sc, err := requireAdminSession(ctx)
	if err != nil {
		return nil, err
	}

	serviceID, err := parseUUIDField(obj.ID, "id")
	if err != nil {
		return nil, err
	}

	queries := db.New(r.pool)
	windows, err := queries.ListActiveMaintenanceWindowsByServiceID(ctx, db.ListActiveMaintenanceWindowsByServiceIDParams{
		ServiceID:      serviceID,
		OrganizationID: sc.User.OrganizationID,
		StartsAt:       pgtype.Timestamptz{Time: time.Now().UTC(), Valid: true},
	})
	if err != nil {
		r.logger.Error("list active maintenance windows failed", "error", err)
		return nil, gqlerr.New(handlers.CodeInternal, "internal error")
	}

	return maintenanceWindowsFromDB(windows), nil
}

// Service returns ServiceResolver implementation.
func (r *Resolver) Service() ServiceResolver { return &serviceResolver{r} }

type serviceResolver struct{ *Resolver }
