name: Main

on:
  push:
    branches:
      - main

concurrency:
  group: main-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
